### ISSUE TITLE
Theme Switcher (NavBar) resets to default only

### ISSUE THREAD

**Issue by chang-zhao** [LotarProject/dokuwiki-template-bootstrap3#1]
When I set Theme Switcher in NavBar,
and try to use it,
that always resets a page to default theme,
regardless of what theme I choose.
(Except that when I choose Default, it sets the page to the currently set theme).
But on refresh or on any other page, the previous theme (set in DW settings) is shown again.
My DW version is the last dev snapshot.

**Comment by LotarProject** [comment]
Thanks for reporting this issue! I have fixed the problem in last commit.
