### ISSUE TITLE
Add custom javascript and css

### ISSUE THREAD

**Issue by mluettecke** [LotarProject/dokuwiki-template-bootstrap3#10]
How/Where would be the best way to add custom javascript and css?

**Comment by LotarProject** [comment]
Hi. This template does not use particular mechanism to add custom CSS and JS.
At this moment the best method to add custom JS and CSS is to create the files in the "dokuwiki-install-dir/conf":
  * conf/userscript.js
  * conf/userstyle.css (for Screen media)
  * conf/userprint.css (for Print media)
  * conf/userall.css (for All media)

In alternative for CSS, you can customize the "style.ini" file in the template directory.

For more information:
  * https://www.dokuwiki.org/devel:javascript
  * https://www.dokuwiki.org/devel:css#user_styles

**Comment by mluettecke** [comment]
Thanks that works flawless.

**Comment by gozzilli** [comment]
The `style.ini` file in `bootstrap3` says:
```ini
; To extend this file or make changes to it, it is recommended to create
; a local conf/tpl/<template-folder-name>/style.ini file to prevent losing
; any changes after an upgrade.
```

Is this supposed to be inside the `bootstrap3` theme folder:

    <root>/lib/tpl/bootstrap3/conf/tpl/<template folder name>/style.ini

or in the dokuwiki root?

    <root>/conf/tpl/<template folder name>/style.ini

I'm asking because I don't have a `tpl` folder either `conf` folders. Thanks and great work!
