### ISSUE TITLE
Edit/last revisions/links-icons on right side no longer visible, if width is expanded with Expand/Reduce-icon in topbar.

### ISSUE THREAD

**Issue by virk** [LotarProject/dokuwiki-template-bootstrap3#100]
This happens with browser Safari and Firefox. Perhaps somebody can confirm?!

**Comment by polyzen** [comment]
Can you still scroll to the right and see them? I'm having a similar problem when viewing this on my phone.

**Comment by polyzen** [comment]
How difficult would it be to make the temporary fix optional?
