### ISSUE TITLE
No tooltip for rename page button from plugin:move

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#101]
https://ptpb.pw/lUpQ.png
[FWIW](https://github.com/michitux/dokuwiki-plugin-move/blob/master/action/rename.php#L50)

**Comment by polyzen** [comment]
Thank you :)

**Comment by rtvb** [comment]
Using **Release 2015-08-10a "Detritus"**, latest [Move plugin](https://www.dokuwiki.org/plugin:move) and latest bootstrap theme, I (still?) cannot see the move icon for a specific page.

![default](https://cloud.githubusercontent.com/assets/559346/16329418/91ee6304-39e2-11e6-9983-84609499d752.png)

![bootstrap](https://cloud.githubusercontent.com/assets/559346/16329423/95c78d02-39e2-11e6-83cc-e5323309b917.png)

**Comment by AlekSet** [comment]
@rtvb try cleanup cache, it works on my page very well
![tools](https://cloud.githubusercontent.com/assets/16212999/16329670/08f9715e-39e4-11e6-96e2-57fb65193959.jpg)

**Comment by rtvb** [comment]
I cleared my browser cache, touched the config file (https://www.dokuwiki.org/caching) and purged the js.php cache (https://www.dokuwiki.org/devel:caching).Without any effect.

**Comment by rtvb** [comment]
I have tested it with a local wiki (http://localhost/~username/dokuwiki) and that shows the rename icon.

Still wondering what's different between the local installation and the hosted wiki.

**Comment by rtvb** [comment]
I completely reinstalled the software on my server and now it's working as expected.
