### ISSUE TITLE
Add user namespace option to showUserHomeLink

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#102]
It is nice to have user namespaces like in https://www.dokuwiki.org/acl#user_wildcards, and it would be great if showUserHomeLink could reflect that.

**Comment by polyzen** [comment]
Basically just want an option for the link to be user:%USER%:start as opposed to user:%USER%

**Comment by LotarProject** [comment]
Hi! The user home link is defined in the ``interwiki.conf`` file:
````
user      :user:{NAME}
````
The template follow this config for build the link.

At your disposal.
Joseph

**Comment by polyzen** [comment]
Silly me. Thanks again!
