### ISSUE TITLE
Table of Content and sidebar problem

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#103]
Hello.
Thank you for creating this template. It is very wonderful!
I have two question with toc(table of content) in your template.

1. I want to change 'expanded' toc box(div) in desktop version.

2. I want to change 'collapsed(folded)' toc box(div) in mobile version.

3. An error appears in the sidebar(collapsed(folded) in mobile version)
when I scroll up or down, sidebar automatically closes.
(OK in IE and FireFox, error in Chrome and Opera)

Thanks for reading and please request to check.

**Comment by polyzen** [comment]
@lattekun, is this fixed for you? I'm confused as to what your problem/s is/are. Your third bullet still seems to be occurring.
