### ISSUE TITLE
Some text gets cut off in responsive mode (certain browsers)

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#104]
[Screenshot](https://ptpb.pw/cIMJ.png)
[Source](https://ptpb.pw/RiWp.txt)

The device is a Nexus 5 which is considered small by responsive design.

**Comment by polyzen** [comment]
[Shot of nspages](https://ptpb.pw/_rel.png)

**Comment by LotarProject** [comment]
Hi! I have tested your code, with different smartphone and mobile browser (Firefox, Chrome, Opera) and don't have problems.

Did you execute your test with the default Android browser ? Because i have sometimes problem with this browser.

At your disposal.
Best regards,
Joseph

**Comment by polyzen** [comment]
Ahh, this does look good in [Fennec](https://f-droid.org/wiki/page/org.mozilla.fennec_fdroid). The issue had occurred in the default browser in [CopperheadOS](https://coperhead.co/android) (a security-enhanced fork of Cyanogenmod).

Sorry for such a late response; I lost track of this :package :p

**Comment by LotarProject** [comment]
No problem! Android stock browser have more problems with Bootstrap (from the documentation):

*Out of the box, Android 4.1 (and even some newer releases apparently) ship with the Browser app as the default web browser of choice (as opposed to Chrome). Unfortunately, the Browser app has lots of bugs and inconsistencies with CSS in general.*

PS: interesting ROM :)

**Comment by polyzen** [comment]
Ahhh I see.

Yes, it is :p Fwiw, the main dev behind CopperheadOS mentioned that [CM will be switching to a fork of Chromium](https://github.com/copperhead/android/issues/5#issuecomment-141115951)
