### ISSUE TITLE
Home button in navbar

### ISSUE THREAD

**Issue by chtiland** [LotarProject/dokuwiki-template-bootstrap3#109]
It would be nice to have a setting to hide/disable Home button (link) in navigation bar.

**Comment by LotarProject** [comment]
Hi! The default location of Home button link is the navbar logo.
The template don't provides option for enable or disable this link, but provides two way to add/remove this link:
  * ``navbar.html`` hook (out-of-the-box)
  * inside a DokuWiki page with the new navbar hook (see #91)

At your disposal,
Joseph

**Comment by chtiland** [comment]
How do I missed this post (#91) ?

Thanks a lot :-)
