### ISSUE TITLE
Navbar + Search on a new line (medium width) => "youarehere" disappear

### ISSUE THREAD

**Issue by chtiland** [LotarProject/dokuwiki-template-bootstrap3#111]
As you can see with medium width "youarehere" disappear: 

![capture d ecran 2015-11-03 a 17 19 07](https://cloud.githubusercontent.com/assets/298526/10913671/41f662e8-824f-11e5-979b-76c77867f672.png)

As it should be:
![capture d ecran 2015-11-03 a 17 23 36](https://cloud.githubusercontent.com/assets/298526/10913760/a7936cae-824f-11e5-9cca-78e988ffd380.png)

(Note that's one of the reason for #110) ;-)

**Comment by LotarProject** [comment]
Hi! This is an old Bootstrap problem (eg. twbs/bootstrap/issues/#9566). The solution is change on-the-fly of the space between the navbar and breadcrumbs or hide/remove certain links or elements via configuration manager.

At your disposal,
Joseph

**Comment by chtiland** [comment]
Hi !
As there's no problem in a 1024x768 resolution and on some smartphones I tried,  it's ok for me ;)

But an option for navbar only in small resolutions would really be nice :) (#110)

**Comment by LotarProject** [comment]
Is not possible to create a general patch. I suggest to fix this behavior via CSS (``userall.css``).
