### ISSUE TITLE
Small width + inverseNavbar : bars in top right button menu are white on white background

### ISSUE THREAD

**Issue by chtiland** [LotarProject/dokuwiki-template-bootstrap3#112]
Better with screen shot ;)

![capture d ecran 2015-11-03 a 17 28 44](https://cloud.githubusercontent.com/assets/298526/10913994/a28bb224-8250-11e5-883e-3ca92bada3e2.png)

**Comment by LotarProject** [comment]
Hi! I think is a Bootswatch issue. What theme are you use ?

At your disposal,
Joseph

**Comment by chtiland** [comment]
Hello !

Bootswatch : Celurean theme.

By the way I temporary fixed it with userstyle.css
