### ISSUE TITLE
Inlinetoc support

### ISSUE THREAD

**Issue by coastgnu** [LotarProject/dokuwiki-template-bootstrap3#115]
bootstrap3 misses support for the inlinetoc plugin https://www.dokuwiki.org/plugin:inlinetoc 

In dokuwiki's default template inlinetoch prevents the regular toc to show up
In bootstrap3 inlinetoc _and_ the regular toc shows up, that's a least one toc too much. :-)

the JS-Code for this is in inlinetoc.js
```javascript
function hideDokuwikiToc() {
    if(document.getElementById('inlinetoc2')) {
        var elements = document.getElementsByTagName('div');
        for(var i=0; i < elements.length; i++) {
            if(elements[i].id == 'dw__toc') {
                elements[i].style.display = 'none';
                break;
            }
        }
    }
}
 
jQuery(hideDokuwikiToc);
```

regards, 
thomas

**Comment by raychani** [comment]
I think the space is still remained by this code.
There is some new function for remove the div of toc. not hide.

**Comment by baxq** [comment]
I've tried everything I can think of, and this still isn't working for me; my pages always have both TOCs visible. Any ideas what I might be doing wrong/what's going on here?

![screen shot 2016-08-07 at 23 13 13](https://cloud.githubusercontent.com/assets/18325348/17465627/91b3d420-5cf4-11e6-8ec0-991640b0000b.png)

## Dokuwiki Setup
**DW Version:** 2016-06-26a "Elenor of Tsort"
**Bootstrap3 Template Version:** 2016-07-05
**Theme:** Using Yeti, but the issue occurs with all the themes
**InlineTOC Version:** 2015-06-19

## Test Page Content

```
# Page Heading

{{INLINETOC}}

## Subheading 1

## Subheading 2

## Subheading 3
```
