### ISSUE TITLE
Un-clicking "Display User Home-Page link in navbar"

### ISSUE THREAD

**Issue by armanabraham** [LotarProject/dokuwiki-template-bootstrap3#118]
Hello, 

If my understanding is correct, disabling "Display User Home-Page link in navbar"" should  remove the Home button from the navbar. However, it remains there. Is this a bug or a different behavior is expected? 

Thank you, 
Arman

**Comment by LotarProject** [comment]
Hi Arman! This option disable the link of personal user-home-page. The home-page link in placed inside the navbar hook (``navbar.html`` and/or ``:navbar`` wiki page).

At your disposal,
Joseph

**Comment by armanabraham** [comment]
Got it, Joseph! Thank you!
Arman

**Comment by polyzen** [comment]
@LotarProject, I take it using :navbar come with a little overhead?

@armanabraham, please close this :)
