### ISSUE TITLE
Right sidebar and ACL

### ISSUE THREAD

**Issue by armanabraham** [LotarProject/dokuwiki-template-bootstrap3#119]
Hi Joseph, 

I am trying to use the rightsidebar with ACL. Want the rightsidebar to appear only when user has access permission to the file "rightsidebar". However, when I setup ACL for rightsidebar, and try to load the page without logging in (no permission to access the rightsidebar), it throws "Permission Denied" page. Is it possible for the bootstrap3 to not display the rightsidebar when permissions do not allow.  

Thank you, 
Arman

**Comment by LotarProject** [comment]
Hi Arman! You can write your ACL to replicate and test this issue ?
In my test i have the opposite behavior. I see the right sidebar in the page and permission denied when open the rightsidebar directly.

At your disposal,
Joseph
