### ISSUE TITLE
Navbar Hook Mobile Layout Displays Wide

### ISSUE THREAD

**Issue by joshuarlowry** [LotarProject/dokuwiki-template-bootstrap3#120]
When adding navigation to the navbar using the `[[:navbar]]` page hook it causes the layout to display wider than the mobile screen size. 

I think this has something to do with another issue I have seen where the first line of the :navbar page has to be blank or I get a plain link instead of a navbar button that makes my navbar taller than it should be.

**Comment by LotarProject** [comment]
Hi! To replicate in my dev environment, You can send a snippet of ``:navbar`` ?

At your disposal,
Joseph

**Comment by joshuarlowry** [comment]
```

  * [[ORG:portal|Leadership Portal]]
  * [[Local Routes]]
```

**Comment by LotarProject** [comment]
@joshuarlowry, this problem still in newer version of template ?

Sorry for my delay :P

Thanks
Joseph
