### ISSUE TITLE
Problem with plugin davcal

### ISSUE THREAD

**Issue by kernam** [LotarProject/dokuwiki-template-bootstrap3#121]
Hi,

during my tests with this cool theme I came across an incompatibility with the davcal plugin. This plugin renders a calendar view. This calendar is shown rather condensed (please see attached screenshot). I tested it with the default theme and with the arctic theme. Both rendered the calender correctly so I think the problem located in bootstrap3. It would be nice if someone could help me out of this.
![davcal](https://cloud.githubusercontent.com/assets/15692946/11146693/bde2e7a0-8a10-11e5-9736-94c8284ac393.png)
 
Thanks in advance

Achim

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. Probably is the same behavior of #112. I discovered the problem and solution.

Stay tuned ;)
Joseph

**Comment by kernam** [comment]
Hi Lothar,

thank you very much. This works like a charm. 

Greetings

Achim
