### ISSUE TITLE
JavaScript not working at all after latest commit?

### ISSUE THREAD

**Issue by per-hed** [LotarProject/dokuwiki-template-bootstrap3#122]
After 79884a27aea92b496acf18234ba24ddcfb3220eb, with the following changelog...:

*Moved all template configuration from TPL_CONFIG to DokuWiki JSINFO JavaScript object*

...JavaScript is not working at all on our DokuWiki-install. No dropdown menus, no AnchorJS. This is pretty much a showstopper. Had to downgrade to previous commit.

JS-console says "TPL_CONFIG is not defined"?

**Comment by LotarProject** [comment]
Hi! Sometimes the problem is the DokuWiki cache. Can you flush the DokuWiki and browser cache?

For flush the JS DokuWiki cache, follow the URL ``<dokuwiki>/lib/exe/js.php?purge=true`` or "touch" the configuration.

At your disposal,
Joseph

**Comment by per-hed** [comment]
Yup, works now! Thanks! :+1:
