### ISSUE TITLE
Body font-size small being applied to bootswatches

### ISSUE THREAD

**Issue by tysoncecka** [LotarProject/dokuwiki-template-bootstrap3#125]
Lumen looks different on our site as body { font-size: small } is being applied by css.php?t=bootstrap3&tseed=3ae63a744092d2c42d773505eee2548f

I tried to overwrite with a custom theme and remove body { font-size: small } from template.less but didn't have any success

Any help? Thanks

**Comment by LotarProject** [comment]
Hi! In this commit the body font-size uses the original sizes defined in templates. The "small" size, is for  Bootstrap vanilla template.

**Comment by tysoncecka** [comment]
Thanks! Looks like that works
