### ISSUE TITLE
browserTitle - adding some part of namespace

### ISSUE THREAD

**Issue by LotarProject** [LotarProject/dokuwiki-template-bootstrap3#129]
(requested by Alekk from https://www.dokuwiki.org/template:bootstrap3)

Hi. Is there any way to add some part of namespace to ```<title>``` tag?
I have dozens of pages witch same ID but in different namespaces. It would be nice to display in page title mayby two last namespaces. 

Now:

URL | Title
----|----
http://abcd.ef/favorite/dogs/timmi | Timmi [MyWiki]
http://abcd.ef/disliked/cartoons/timmi | Timmi [MyWiki]

Nicer it would look like this: 

URL | Title
----|----
http://abcd.ef/favorite/dogs/timmi | Timmi - Favorite - Dogs - [MyWiki]
http://abcd.ef/disliked/cartoons/timmi |Timmi - Disliked - Cartoons - [MyWiki]

**Comment by polyzen** [comment]
This is something I've also wanted :)

Another option would be u/d/n/page instead of @TITLE@ (eg., :path:to:page
would show as "p/t/Page  [MyWiki]")

**Comment by polyzen** [comment]
Awesome :). I'm a little confused as to how this works. Apparently it's disabled by default? browserTitleShowNS enables it?

**Comment by LotarProject** [comment]
Hi! I don't have completed the documentation in DokuWiki. Sorry!
Yes, enable ``browserTitleShowNS`` option for a new title.

At your disposal,
Joseph

Giuseppe Di Terlizzi

2015-12-15 16:36 GMT+01:00 Daniel M. Capella <notifications@github.com>:

**Comment by polyzen** [comment]
Not sure if I'm doing something wrong, but enabled that didn't appear to
have an effect.

**Comment by LotarProject** [comment]
Hi Daniel! Fixed and improvements in latest commits.

At your disposal,
Joseph

**Comment by polyzen** [comment]
Great work as per usual :+1:
