### ISSUE TITLE
Lose of toolbar dropdown menus when activating Bootstrap Wrapper Plugin

### ISSUE THREAD

**Issue by Laurent3170** [LotarProject/dokuwiki-template-bootstrap3#130]
Hi,
I am new to dokuwiki. I have played around with templates and plugins. I've chosen boostrap3 template because... it's bootstrap3 ;-) and the template is really good.
However I wanted to also use "Bootstrap Wrapper Plugin" but when it's activated i can't have anymore the dropdowns menus in the top toolbar.
It runs under firefox 43.0 and Ubuntu 14.04.
Thanks for your job (template and plugins) and for your help
Laurent

**Comment by bitrampage** [comment]
If you enclose your unordered list of links (with the dropdown) in the :navbar hook page in \<nav>...\</nav> tags, the top navbar dropdowns will display, open and function again in the bootstrap template.

Not sure this is the intended behavior on the template's part, but it is at least a quick fix/workaround. Apparently Bootstrap Wrapper Plugin's nav functionality overrides the template's own navbar function.

Peter

**Comment by Laurent3170** [comment]
Thanks. I'll try this and let you know.

**Comment by Laurent3170** [comment]
So I have created a :navbar page but I can't enclose the Dokuwiki's menu as it' built-in. I can add my own but that's not my goal (for the time being).
Maybe I have misunderstood something...

**Comment by Laurent3170** [comment]
I don't know how neither why (maybe the new version 2016-01-18) but I've re-installed it and it works :-)

**Comment by LotarProject** [comment]
:+1:

**Comment by Laurent3170** [comment]
Back with this problem... I said the 23rd of January that my toolbar was back, but in fact not... It was a mistake but as it was not really important, I've left it. But today, I've found where it comes from.
There's a kind of bug with the template and bootswrapper.
In the conf/local.php, the line 
`$conf['plugin']['bootswrapper']['loadBootstrap'] = 1;`
makes the lose of the dropdowns, with it, no dropdowns, without, dropdowns.

BUT... life's no easy as it seems :-(
If I want to enable the custom template with bootstrap, and sets
`$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'custom';`
The css interpretation blocks and fails... without the line for bootswrapper...

**Comment by Laurent3170** [comment]
In fact the point in explained in the config page under the Bootswrapper section. So ith should be disabled as I'm using Bootstrap3 template. So there is "only" the problem taht it should be loaded for custom theme.

**Comment by Laurent3170** [comment]
Ok I got it with issue #169.
In fact when you specify custom theme it needs a full theme in the url custom path. I was only using conf/userstyle.css as specified in https://www.dokuwiki.org/template:bootstrap3#customize_the_theme.
Now I can create my theme using bootstrap magic, save the css and use the custom theme.

**Comment by Laurent3170** [comment]
So this time it's "really" closed :-)
