### ISSUE TITLE
Sidebar shows spaces

### ISSUE THREAD

**Issue by dz-igner** [LotarProject/dokuwiki-template-bootstrap3#136]
Hello,

first of all, thank you for this wonderfule template.

I've a liitle issue with the my sidebar (see screenshot below). There is some spaces above and below the sidebar entrys and I don't know, how to get rid of these spaces:

![2016-01-21_070208](https://cloud.githubusercontent.com/assets/15924199/12472922/812eedd0-c00d-11e5-80be-8545eddf9989.jpg)

Kind regards
dz-igner

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. Can you send a snippet of your sidebar page to test in my dev environment?

Best regards,
Joseph

**Comment by dz-igner** [comment]
I'm using the indexmenu plugin to generate the content of my sidebar (from namespaces). The content of the sidebar page ist just

~ ~ NOCACHE~ ~
{{indexmenu>:|js#gnome.png}} 

Kind regards
dz-igner

**Comment by LotarProject** [comment]
I have make a test in my dev env and this issue is not reproducible. can you execute an "export_raw" of your sidebar page (eg. ``http://dokuwiki/foo:sidebar?do=export_raw``) and send me via email ?

At your disposal,
Joseph

**Comment by dz-igner** [comment]
Hello, I've changed the content of my sidebar.txt to

{{indexmenu>..#1|js#gnome.png navbar tsort msort}}

and now - surprise - the spaces are gone.

Thank your for testing.

Kind regards
dz-igner
