### ISSUE TITLE
Ordered list items all using one ol type

### ISSUE THREAD

**Issue by Valiantiam** [LotarProject/dokuwiki-template-bootstrap3#139]
I am by no means an expert in CSS, however one issue I found is that OL type for this theme is set to use numerics no matter the indent.

Is it possible to share where I could update the code so that each level uses a different style?

Currently:
```
1.
2.
  1.
  2.
     1.
     2.
3.
```

I'd like if it could be....

```
1.
2.
  a.
  b.
     i.
     ii.
3.
```

**Comment by LotarProject** [comment]
Hi! Thanks for the idea! Now the template use the same style of default DokuWiki template:

```
  1.
  2.
    a.
    b.
      I.
      II.
        A.
        B.
          i.
          ii.
```

Best regards,
Joseph

**Comment by polyzen** [comment]
:+1:
