### ISSUE TITLE
TOC position in "article"

### ISSUE THREAD

**Issue by webmurkser** [LotarProject/dokuwiki-template-bootstrap3#140]
Hi Lotar,

thanks for this great implementation - but since last update the TOC is no more as overlay (z-index?) within the page. Can you push them outside the box or set the TOC as overlay?

![toc_position2](https://cloud.githubusercontent.com/assets/8065885/12848008/651b0ece-cc17-11e5-89cf-199ef2aa9aa0.jpg)
![toc_position1](https://cloud.githubusercontent.com/assets/8065885/12848007/651a6b36-cc17-11e5-988c-ee8362d8b68c.jpg)

**Comment by polyzen** [comment]
Joseph fixed this in the developer branch.
