### ISSUE TITLE
IE 11 Navbar Menus Collapsing

### ISSUE THREAD

**Issue by MOEditor** [LotarProject/dokuwiki-template-bootstrap3#143]
I absolutely love your theme package. Thank you very much for the hard work!

I'm having this issue in IE 11:
![capture](https://cloud.githubusercontent.com/assets/16724278/12984644/7eca439a-d0a3-11e5-8fff-f7495763ea3b.PNG)

The "Additional Plugins" portion of the menu is being covered by the "Administrative Tools".

EDIT: I should probably mention that this happens in all themes, not just Lumen.

**Comment by LotarProject** [comment]
Hi! Thanks for your patch. Merged!
