### ISSUE TITLE
Scroll Bar hiding Buttons

### ISSUE THREAD

**Issue by light4ever** [LotarProject/dokuwiki-template-bootstrap3#146]
Hi,
In Internet explorer 11 the scroll bar is hiding the quick edit buttons. How do I disable the quick buttons or get the buttons to slide to the right to prevent the scroll bar from hiding the buttons.
Thanks
Rob
![scrollbar hidding buttons](https://cloud.githubusercontent.com/assets/7833798/13145302/c69237bc-d61d-11e5-8d39-bb2b5a95fd3c.PNG)

**Comment by LotarProject** [comment]
Hi! I have resolved this issue in 5e5aa55 commit on v2016-04-13. Sorry for my delay!
