### ISSUE TITLE
Question: How to add Glyphicon, Fugue or custom .png to buttons?

### ISSUE THREAD

**Issue by dior1** [LotarProject/dokuwiki-template-bootstrap3#147]
Hi,

`<btn type="success" icon="fa fa-globe">[[http://google.com|Google]]</btn>`
 ist working . 

But how do I add an Icon from Fugue or a .png from my Wiki into a button?

Kind regards
dior

**Comment by polyzen** [comment]
Not sure about the latter, but iirc Joseph's icon plugin supports Fugue.

Perhaps you could just use this[] and resize your png?
[]https://www.dokuwiki.org/wiki:syntax#media_files
