### ISSUE TITLE
TOC levels

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#148]
Hello ! 

Today I've noticed that the TOC only displays max 2 levels even if the "maxtoclevel" setting has a greater value. Is this a normal behavior ?

Thank you
Vincent

**Comment by LotarProject** [comment]
Hi!
The default TOC behavior is to collapse the 3 levels (and more) to save space in TOC . For disable this behavior switch off the ``tocCollapseSubSections`` option.

At your disposal,
Joseph
