### ISSUE TITLE
Integration of the translation plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#149]
Hi Lotar,

the warning of the translation plugin for old revisions destroys the navbar:
![schuemmer-2016-02-23 10_43_21-clipboard](https://cloud.githubusercontent.com/assets/1800472/13247547/72d39714-da1a-11e5-8c79-7a4d7480c118.png)

Regards Juergen

**Comment by LotarProject** [comment]
Hi, fixed in develop branch.

Thanks,
Joseph
