### ISSUE TITLE
Broken, no error

### ISSUE THREAD

**Issue by kevin39** [LotarProject/dokuwiki-template-bootstrap3#15]
Hi,
My dokuwiki is up to date.
I installed this template using extension manager but it doesn't work. I'v only the header page.

The page is blank and end with :   
```
    <ul class="nav navbar-nav">
    <li>
```

**Comment by LotarProject** [comment]
Hi, i have replicated this issue in a new DokuWiki installation and don't have a problem.

I suggest to download the theme manually and unzip into the "<dokuwiki>/lib/tpl"

Best regards
Joseph

**Comment by kevin39** [comment]
Ok, problem solved. Not you fault, it's mine :)
