### ISSUE TITLE
Printing in colour

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#153]
Hi Lotar,

when printing out wiki pages the text colour always is black. I´ve tried to add some code in the userprint.css, but had no success. So what can I do to print out e.g. all headlines in colour?

Best regards
Juergen

**Comment by Soeldner** [comment]
not tested, insert in conf/userall.css ?

```
@media print {
  h1, h2, h3, h4 {
    color:#FF0000;
    background-color:#fff;
  }
}
```

**Comment by Juergen-aus-Koeln** [comment]
OK, thank you! With the _!important_ - flag it works.
