### ISSUE TITLE
Tables generated with tag plugin don't use Bootstrap style

### ISSUE THREAD

**Issue by duenni** [LotarProject/dokuwiki-template-bootstrap3#154]
Hi there,

well, I got another issue with styling. When generating tables with the tag plugin using the `count` syntax ([link](https://www.dokuwiki.org/plugin:tag#count)) the resulting tables won't render in bootstrap style. I'm pretty sure this worked in past versions.
Thanks for looking into this!

Regards

duenni

**Comment by blacklord049** [comment]
There is a similar problem with the CSV plugin.
https://github.com/cosmocode/csv/issues/9

**Comment by duenni** [comment]
Hi,
thanks for the quick fix. Unfortunately, some pages now have unnecessary columns which are emtpy.
Already cleared the cache of this pages. Any ideas?

<img width="1198" alt="bildschirmfoto" src="https://cloud.githubusercontent.com/assets/4258185/13405967/52d13d52-df21-11e5-98bf-fa9117537951.png">

**Comment by duenni** [comment]
Ok, this affects all pages which have more than one `count` command on the page.

- One times `count` - all is good
- Two times `count`- all columns doubled, all columns but the first are empty
- Three times `count` - all columns three times, all columns but the first are empty
- ...
