### ISSUE TITLE
Printing out with a lot of space

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#157]
When printing out a page there is a lot of space above the first text line of the wiki content:
![ticket](https://cloud.githubusercontent.com/assets/1800472/13326219/499461c2-dbe5-11e5-8cd9-aa8479ba1780.png)

Is there a solution to avoid this?

Best regards
Juergen

**Comment by Soeldner** [comment]
I cant confirm that. What settings you have active under the item template? For example "enable border around the page" etc.

![screenshot_git](https://cloud.githubusercontent.com/assets/1868211/13328363/86b561ba-dbee-11e5-992f-2fd71364bb1c.jpg)

**Comment by Soeldner** [comment]
although that may be the breadcrumb ... or the tags ...

Teste mal in der userall.css
```
@media print {
main {
  margin-top: -80px !important;
}
}
```

**Comment by Juergen-aus-Koeln** [comment]
Thank you, but this has no effect on the top area. 

What I can see are two lines above the page name and then above this the big white space:
![ticket](https://cloud.githubusercontent.com/assets/1800472/13348547/75cf30c0-dc74-11e5-9a44-6d52ae67f2e0.png)

Neither changing the template design nor changing the flags "pageOnPanel", "showPageId" and "tagsOnTop" have effect on the behaviour.
