### ISSUE TITLE
Edit Button not showing for many sites

### ISSUE THREAD

**Issue by garyee** [LotarProject/dokuwiki-template-bootstrap3#16]
Hi, I just installed your Template when I went back to a page, there were no more edit buttons of any kind...
It isn't a user-right restriction problem, I reseted them all.
I'am using the current version of doku-wiki

**Comment by garyee** [comment]
More precise:

If a page has just one line, dokuwiki shows no edit button(blue) and just the buttons in the red area.
But as the buttons in the red area are not present ... there is no way to edit the article
![unbenannt](https://cloud.githubusercontent.com/assets/5537949/7180020/dbf75056-e43d-11e4-8032-7f9e07496037.PNG)

**Comment by LotarProject** [comment]
Hi. Thanks for using my template.
The edit action (and other actions) is in the tools menu on navbar.

Best regards,
Joseph

**Comment by garyee** [comment]
Ah found it thanks!
