### ISSUE TITLE
Unclickable Page Icon

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-template-bootstrap3#161]
Hi.
There is one unclicable icon in PageIcons, icon suggest rss feed and title suggest last changes, but nothig is happens when click it.

![lastchanges](https://cloud.githubusercontent.com/assets/16212999/13409077/676537ae-df31-11e5-884d-193cde144fe2.png)

EDIT:
Temporarily I changed in the file `tpl_page_icons.php` line 32:
`<a href="#" title="<?php echo $lang['btn_recent'] ?>"><i class="fa fa-fw fa-rss" style="color:#f26522"></i></a>`
to
`<a href="/feed.php" title="<?php echo $lang['btn_recent'] ?>"><i class="fa fa-fw fa-rss" style="color:#f26522"></i></a>`
It may be the next update.

**Comment by LotarProject** [comment]
Sorry! I have introduced this feature but i have missed the URL :P

Joseph

**Comment by AlekSet** [comment]
TY.
One more thing. According to me, it would be better gray RSS icon as the other.
Or any icon would be of a different color, for example:
![coloredicons](https://cloud.githubusercontent.com/assets/16212999/13446004/4af57a9a-e010-11e5-8e6a-bc10c0b351c0.png)

**Comment by polyzen** [comment]
@AlekSet, great idea.
