### ISSUE TITLE
TOC behavior in the last version

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#162]
Hello,

I made a screenshot to easily describe the "problem".
http://image.noelshack.com/fichiers/2016/09/1456819927-toc.jpg

It would be nice to have the toc fixed on the right like when it's collapsed.  I don't know if it's possible.
Thank you !

**Comment by asmith3006** [comment]
I would love an option in the admin interface to prevent the menu from collapsing if this is possible?

**Comment by blacklord049** [comment]
Plus an option to have the toc always collapsed when landing on another page.

**Comment by blacklord049** [comment]
(As you can see on my screenshot the jumbotron is not reduced when the TOC is over, but the text is shifted to the left)

**Comment by blacklord049** [comment]
Some more screenshots : 

http://image.noelshack.com/fichiers/2016/12/1458657943-whatwehave.png
http://image.noelshack.com/fichiers/2016/12/1458657943-whatweshouldhave.png

**Comment by blacklord049** [comment]
Will there be some kind of fix ? :-)

**Comment by blacklord049** [comment]
Another screenshot to see the problem : 
![another](https://cloud.githubusercontent.com/assets/16919700/15319996/62327618-1c2e-11e6-883f-ef314a684237.png)

**Comment by tysoncecka** [comment]
I get this too on the Lumen theme where when the affix-top class is applied the TOC doesn't "float" over the rest of the page like it does when it is affixed...

**Comment by blacklord049** [comment]
Any news for this enhancement ?

**Comment by tysoncecka** [comment]
As I temporary fix I added this to my userall.css

` body.lumen #dokuwiki__toc_wrapper.affix-top {
 	position: fixed;
 }`

Which just makes the TOC always be affixed to the upper right. The positioning for me isn't the best but it doesn't mess up the page elements now.

**Comment by blacklord049** [comment]
Strange because it doesn't change anything. I used the Advanced config to add the style and purge CSS cache but the TOC is not on the upper right like it should.

**Comment by blacklord049** [comment]
Sorry now working , I just changed lumen with the bootstrap theme I use

**Comment by LotarProject** [comment]
Hi! Sorry for my delay!
In this period i have a created and fixed some issue for TOC. To test and see this TOC, checkout ``feature/toc`` branch.

**Comment by tysoncecka** [comment]
Thanks! I tried out the branch version and on my theme (lumen, not fluid) I'm still getting the body text moving around when the TOC collapses. It's different now since the TOC seems to adjust the column width rather than just wrap the text around it but it still isn't desirable for me. I would like the option to have the TOC be entirely in the empty space to the right of my body content so that it doesn't adjust the size/positioning of any page contents.

**Comment by tysoncecka** [comment]
Hello, is it possible to get an option for starting with the TOC collapsed? I think that would solve a lot of my issues with the TOC right now. 

Thanks

**Comment by polyzen** [comment]
@tysoncecka, if that is a separate request, please open another issue. It's tricky keeping track of all these different TOC issues. :p
