### ISSUE TITLE
Performance when using tabs

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#164]
When using tabs the performance of page reproduction is suboptimal. First the tab headers are listed one below the other:
![bild_1](https://cloud.githubusercontent.com/assets/1800472/13569870/fa66bf44-e46a-11e5-8975-1a487f94a944.png)

Afterwards this the page is rebuild in the right way:
![bild_2](https://cloud.githubusercontent.com/assets/1800472/13569874/fdb346cc-e46a-11e5-927a-9d0c41918c71.png)

This takes some seconds, and the screen is in motion again and again.

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi. The tabs are added on-the-fly via JS and is very slow.
In the last commit i have introduced a new PHP function to increase the performance during rendering of the page.

At your disposal,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Ok, thank you!
Then I'll look forward to the next release

**Comment by polyzen** [comment]
@Juergen-aus-Koeln, if you'd like, you can install [this](https://github.com/LotarProject/dokuwiki-template-bootstrap3/archive/develop.zip) to test it.

**Comment by LotarProject** [comment]
Hi! In the next release i have increased the general template performance by moving some JS code in PHP for this Bootstrap components:
  * Tabs
  * Page Heading (for H1-H2 heading)
  * Tables (including "bordered", "responsive", "hover", etc classes)
  * Alerts
  * Search Hits

Joseph
