### ISSUE TITLE
Inline images not works

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-template-bootstrap3#165]
Today I noticed that the images are not displayed inline and before that it was so, as in a standard template DokuWiki

**Comment by LotarProject** [comment]
Hi! In the last release i have introduced a regression for the image alignment. I have re-fixed this issue with 41c9984 commit (see #26).

Is necessary to reinstall the template from Extension Manager to correct this fix.

At your disposal,
Joseph

**Comment by AlekSet** [comment]
Yes! TY! After reinstal and purge works great!
Sorry, I did not noticed #26
