### ISSUE TITLE
If you use headers in the sidebar ToC will scroll to that instead of the one in the page

### ISSUE THREAD

**Issue by HanFox** [LotarProject/dokuwiki-template-bootstrap3#166]
For example if you set a header in the sidebar to be called "Cake" and there's a section in your page with the header "Cake" clicking the "Cake" link in the ToC will scroll to the sidebar instead of the page.

Really it's a mild failing on Dokuwiki's side because they should probably be prefixing headers in the sidebar with _sidebar__ to avoid duplicate IDs in a page... They shouldn't expect an end user to know proper web standards ;)

Regardless, I fixed this to a degree with this theme by changing in js/template.js:

```
      var body_offset      = (parseInt(jQuery('body').css('paddingTop')) || 0),
          section_position = (jQuery(jQuery.attr(this, 'href')).offset().top - body_offset);
```

to

```
      var body_offset      = (parseInt(jQuery('body').css('paddingTop')) || 0),
          section_position = (jQuery('#dokuwiki__content ' + jQuery.attr(this, 'href')).offset().top - body_offset + 10);
```

It's not perfect though and probably highly flawed knowing me...

**Comment by LotarProject** [comment]
Resolved issue
