### ISSUE TITLE
Datatables are squished

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#167]
https://ptpb.pw/5CSj.png

The issue has been in effect since at least Feb 27th. I'm pretty sure I had only updated this template.

**Comment by LotarProject** [comment]
Hi, I have fixed this behavior with this commit  [c8f2c47](https://github.com/LotarProject/dokuwiki-plugin-datatables/commit/c8f2c471fda0c0734d336180dd31808ad3d8cc36) in DataTables plugin.

At your disposal,
Joseph

**Comment by polyzen** [comment]
Thank you :)
