### ISSUE TITLE
How to setup a custom existing Bootstrap theme?

### ISSUE THREAD

**Issue by umbomas** [LotarProject/dokuwiki-template-bootstrap3#169]
Hello,
I would like to select a Bootstrap theme not in the Bootswatch ones available out-of-the-box (specifically: http://yago.github.io/Bootsketch).

I was not able to figure out how to set the configuration variables (I don't even know if this is possible only working on configuration variables).

_Disclaimer: I am an absolute Bootstrap newbie. Indeed I am using your lovely template as an easy way to build websites with the Bootstrap look and feel._

**Comment by LotarProject** [comment]
Hi, this is the correct procedure to add a custom theme:
- Open "Configuration Settings"
- Set ``bootstrapTheme`` option to ``custom`` (Customized Bootstrap Theme)
- Set ``customTheme`` with the URL of custom Bootstrap Theme (for Bootsketch set ``http://yago.github.io/Bootsketch/build/css/bootsketch.css``)

I have tested this theme and work fine.

At your disposal
Joseph

**Comment by umbomas** [comment]
Thanks, Joseph, it works smoothly also for me.

**Next step:** I am using "Dokuwiki on a Stick", so my wiki is hosted locally and _occasionally_ I work offline. If I start the wiki server when offline, the CSS file is unreachable and the theme does not work. (By the way: if I start the server when online and then switch off the network, the theme is ok - I think that some form of caching occurs in this case).

Now I see that the default bootstrap theme as well as the bootswatch themes have their CSS files stored in subfolders of lib/tpl/bootstrap3/assets/. Further, the Bootsketch theme (as from the ZIP file downloaded from their site) has a "build" folder with a structure resembling the one of the default bootstrap theme.

So my question is: is it possible to have Bootsketch as a locally stored theme?

I tried this: 

1. copied the contents of the "build" folder of Bootsketch into lib/tpl/bootstrap3/assets/bootsketch,

1. modified the function bootstrap3_metaheaders, switch block, case 'optional' as follows:
    case 'optional':
      $bootstrap_styles[] = tpl_basedir().'assets/bootsketch/css/bootsketch.css';
    break;

It is not enough: some elements of the theme are active but at least the "pencil" font of Bootsketch is not used.

**Comment by LotarProject** [comment]
I don't have a USB stick to test but i think this is a procedure:

  * Clone the repository https://github.com/Yago/Bootsketch.git
  * Rename the ``build`` directory in ``bootsketch`` and copy your USB stick (eg. "D:/dokuwiki/")
  * In configuration manager set the new URL ``http://localhost:8080/bootsketch/css/bootsketch.css``

At your disposal
Joseph

**Comment by umbomas** [comment]
Thank you very much, Joseph - it works like a charm!
