### ISSUE TITLE
On pages with lists of tags, the tags get listed at the top instead of beside the page name

### ISSUE THREAD

**Issue by pmainvil** [LotarProject/dokuwiki-template-bootstrap3#17]
Hello,

When using the keyword {{topic>tagname}} , the tags belonging to a specifc page in the table are listed in the top area of the page instead of besides the page name and date in the list area.  I end up with a lot of redundant tags at the top of the page.

If I use the &notag option in topic, the problem does not appear, but I loose the names on individual pages which is a useful features for managing the tags.

Another small cosmetic issue: With the sidebar, the icon for external link overlaps with the beginning of the text.

What is the easiest way to increase the percentage of the screen used for large displays instead of having large white areas on each side?

Nice work!

**Comment by LotarProject** [comment]
Hi, Thanks for reporting the issue.

I have fixed the problem for tags plugin in my last commit.

For the last question i have added a new option to enable the fluid container (default: off) for the full-width of the page.

I am to work to resolve the issue for the external link icon (and other icons) in the sidebar.

Best regards,
Joseph

**Comment by pmainvil** [comment]
Everything works well with the new version including the icon spacing.

I like the fluid container option.

Grazie mille
Paul.
