### ISSUE TITLE
Missing google analytics in detail.php

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-template-bootstrap3#170]
I do not know if it's intentional action, but there is no call **bootstrap3_google_analytics** () in _detail.php_
I want to know how many people watch details of images, so I added line
`<?php bootstrap3_google_analytics() ?>`
after
`<?php tpl_metaheaders()?>`
in _detail.php_

If the purpose is not included in the details, it would be nice to be able to include this in the configuration.

**Comment by LotarProject** [comment]
Hi! Is not an intentional action but i have forgot to add :P
