### ISSUE TITLE
detail.php improvements

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-template-bootstrap3#171]
I have three ideas for improvement, all relating to detail.php
  1. Option to show navbar 
  2. Option to show details in a modal dialog, something like lightbox, but showing the file detail page, not only image.
  3. Option to force download files (not only zip's etc. also images) in details after click on the image or a separate button

All points should work together, except 1. with 2.
These improvements make it easier to browse the photo gallery and downloading originals.

These ideas fell into my mind when creating the [game wallpapers gallery](http://kody.magazynek.org/game-wallpapers/start)
I do not use gallery module, only classic links with [Bootstrap Wrapper component with attribute shape="thumbnail"](http://lotar.altervista.org/dokuwiki/wiki/plugin/bootswrapper/image#shapes) , eg.
```
<image shape="thumbnail">
{{some-file-1.jpg?310x175|}}
{{some-file-2.jpg?310x175|}}
{{some-file-3.jpg?310x175|}}
</image>
```
I would like to know your opinions on this subject.

**Comment by LotarProject** [comment]
Good idea!

**Comment by LotarProject** [comment]
Hi! I have created a new branch (feature/detail) to test this new functionality.

**Comment by AlekSet** [comment]
WOW! That was so very fast!!!

I thought about it a little differently, but that's fine.
Even though there is a place for advertising.
As for me - firecracker.
Good job.
Today I apply changes to my website.

**Comment by LotarProject** [comment]
Your website is impressive! Good work!
