### ISSUE TITLE
Ugly Formatting Toolbar

### ISSUE THREAD

**Issue by drguildo** [LotarProject/dokuwiki-template-bootstrap3#172]
I have Bootstrap3 configured to use the Cosmo theme and when editing pages the formatting toolbar looks like this:

![Cosmo Formatting Toolbar](https://0x0.st/KYJ.png)

Apart from not looking very nice, it also makes it pretty hard to distinguish the icons.

**Comment by LotarProject** [comment]
Hi! This is a default color of Cosmo theme for ``.btn-default`` ... but is orrible in toolbar!
I have changed the color of buttons.

Thanks!
Joseph

**Comment by tablatronix** [comment]
This needs a way to handle this in the theme, it is a problem with any dark button themes.
specificity target overrides ?

```
<button class="toolbutton btn btn-default" title="Bold Text [B]" aria-controls="wiki__text" accesskey="b"><img src="/wiki/lib/images/toolbar/bold.png" alt="" width="16" height="16"></button>
```

**Comment by apidevlab** [comment]
I have been able to update the spacelab theme following the changes posted but agree with @tablatronix this could benefit from a more appropriate handling.
