### ISSUE TITLE
How to display the sidebar ?

### ISSUE THREAD

**Issue by ZHANGYANKUN** [LotarProject/dokuwiki-template-bootstrap3#173]
I can't display the sidebar , Please teach me ? THX.
@LotarProject

**Comment by AlekSet** [comment]
Just create in the root namespace page named **sidebar**.
More You can read here:
http://lotar.altervista.org/dokuwiki/wiki/template/bootstrap3/hooks?s[]=sidebar#dokuwiki_hooks
or 
http://lotar.altervista.org/dokuwiki/wiki/template/bootstrap3/hooks?s[]=sidebar#html_hooks

**Comment by ZHANGYANKUN** [comment]
Yep, now i can see the sidebar with using indexmenu  plugins , thx the heavy & powerful bootstrap3 template!
