### ISSUE TITLE
Pagetools are behind the scrollbar on IE11

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#174]
Hi,

Bootstrap3 (with Cerulean theme) and latest Dokuwiki Version.
http://image.noelshack.com/fichiers/2016/12/1458657193-sideicons.png

In IE11 the pagetools are behind the scrollbar
Thanks !

**Comment by blacklord049** [comment]
Hi, I added the `-ms-overflow-style` style into the CSS file, cleared IE11 cache, restarted Apache server, but it doesn't change anything.

**Comment by LotarProject** [comment]
Hi, can you purge DokuWiki cache (via ``<dokuwiki>/lib/exe/css.php?purge=true`` url) ?

At your disposal,
Joseph

**Comment by blacklord049** [comment]
It's working ! Thank you ;-)
