### ISSUE TITLE
Use of deprecated symbol DOKU_TPL

### ISSUE THREAD

**Issue by umbomas** [LotarProject/dokuwiki-template-bootstrap3#175]
Hi,
I was trying to use bootstrap3 template together with [plugin loadskin](https://www.dokuwiki.org/plugin:loadskin) in order to have different templates in different sections of my wiki.

I had some problems at first try. I then read the loadskin instructions and found that the use of **DOKU_TPL** is deprecated, function **tpl_basedir()** should be used instead.

In the bootstrap3 files, DOKU_TPL is referenced only in tpl_functions.php file. I replaced it with tpl_basedir() and now the template works well with loadskin.

Is it possible to commit these changes in the bootstrap3 distribution?

**Comment by LotarProject** [comment]
Thanks ;)
