### ISSUE TITLE
Text is centered in Update my profile page

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#177]
I don't remember if it's centered with the default dokuwiki template, but with Bootstrap3 and Cerulean, textboxes, labels, buttons, are centered on these pages (Firefox 45) : 
- Profile update : http://image.noelshack.com/fichiers/2016/12/1458823093-centered.png
- Login : http://image.noelshack.com/fichiers/2016/12/1458823377-centered2.png

Is there a way to change it easily ? Would be nice to have this behavior on mobile devices but not with a PC browser. Thank you !

**Comment by LotarProject** [comment]
Hi! By default DokuWiki "center" all form elements. I have changed the alignment on mobile devices.

Thanks for idea!

Best regards,
Joseph

**Comment by blacklord049** [comment]
In fact I didn't explain myself as expected.
Would be better to have : 
- Centered text on mobile devices 
- Left alignment on bigger devices like PC
:-)
