### ISSUE TITLE
Double clicking <code> block selects Edit button

### ISSUE THREAD

**Issue by nkukard** [LotarProject/dokuwiki-template-bootstrap3#179]
Hi guys,

When using the bootstrap3 template and double clicking to select all text in a **code** block, or when dragging over all lines including the last line the "Edit" text from the edit button is somehow put into the clipboard buffer.

When selecting the contents of the **code** block, the edit button text "Edit" should not be put into the clipboard buffer.

Tested using Debian Jessie, Ubuntu 15.10 and Ubuntu 16.04 beta.

-N

**Comment by LotarProject** [comment]
Hi! This is the same behavior of default DokuWiki template. I have find a solution via CSS with ``user-select`` property (see https://css-tricks.com/almanac/properties/u/user-select/), but not work properly in WebKit browsers.

**Comment by LotarProject** [comment]
@nkukard , this problem still present in newer version of template ? In my test with develop branch (the upcoming release) don't see this problem (tested with FF). 

Sorry for my delay
Joseph
