### ISSUE TITLE
TOC behaviour since update

### ISSUE THREAD

**Issue by Kossygin** [LotarProject/dokuwiki-template-bootstrap3#180]
Hi!
I'm having trouble with the TOC since I updated to the newest version of Bootstrap3. 

The TOC pushes the rest of the page down instead of placing it between the sidebar and TOC.

Unfortunately I don't have a screenshot of this before the update, but now it is this: 

 (![bootstrap3](https://cloud.githubusercontent.com/assets/18144663/14110812/615ea31a-f5c8-11e5-9822-4cbf74d8eab4.png)

Thnx in advance!

**Comment by goochem4u** [comment]
The same problem at my company. Please help! 

If you need more information, i'm more than willing to deliver.

**Comment by LotarProject** [comment]
Hi! I think the problem is in the sidebar. Can you send me a snippet or full source of your sidebar to reproduce in my dev environment ?

I don't understand the Configuration Manager with the sidebar. The sidebar is not visible in Admin mode.

At your disposal,
Joseph

**Comment by goochem4u** [comment]
Hello LotarProject,

First of all, thanks for the quick reply. I can confirm that if the TOC and the left sidebar are active,m the problem occurs.

The left sidebar is a plugin named: SidebarNG Plugin

The DIV below is the left sidebar.

```
<div class="left_sidebar">
<div class="main_sidebar sidebar_box">

<h3 class="sectionedit1" id="home">Home<a class="anchorjs-link " href="#home" aria-label="Anchor link for: home" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h3>
<div class="level3">
<ul class="fix-media-list-overlap">
<li class="level1"><div class="li"> 1</div>
</li>
<li class="level1"><div class="li"> 2</div>
</li>
<li class="level1"><div class="li"> 3</div>
</li>
<li class="level1"><div class="li"> 3</div>
</li>
<li class="level1"><div class="li"> 4</div>
</li>
</ul>

<p>
<strong>links</strong>
</p>
<ul class="fix-media-list-overlap">
<li class="level1"><div class="li"> <a href="https://support.kentis.nl/otrs/index.pl" class="urlextern" title="https://support.kentis.nl/otrs/index.pl" rel="nofollow">Ticketsysteem</a></div>
</li>
<li class="level1"><div class="li"> <a href="http://bcrit.bytesnet.nl/intern/login.php" class="urlextern" title="http://bcrit.bytesnet.nl/intern/login.php" rel="nofollow">Bcrit</a></div>
</li>
</ul>

</div>
<div class="secedit"><form class="btn_secedit form-inline" method="get" action="/doku.php"><div class="no"><input type="hidden" name="do" value="edit"><input type="hidden" name="rev" value=""><input type="hidden" name="0" value="post"><input type="hidden" name="id" value="sidebar"><button type="submit" title="Edit" class="btn btn-default btn-xs">Edit</button></div></form></div>
</div>
<div class="group_sidebar sidebar_box">

<h3 class="sectionedit1" id="admin_menu">Admin Menu<a class="anchorjs-link " href="#admin_menu" aria-label="Anchor link for: admin_menu" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h3>
<div class="level3">
<ul class="fix-media-list-overlap">
<li class="level1"><div class="li"> <a href="/doku.php?id=wiki_onderhoud" class="wikilink1" title="wiki_onderhoud"> Index volledige wiki</a></div>
</li>
<li class="level1"><div class="li"> <a href="/doku.php?id=group:admin:sidebar" class="wikilink1" title="group:admin:sidebar">Admin menu</a></div>
</li>
<li class="level1"><div class="li"> <a href="/doku.php?id=speeltuin" class="wikilink1" title="speeltuin">speeltuin</a></div>
</li>
</ul>

</div>

<h4 id="aanpassen_menus">Aanpassen menus<a class="anchorjs-link " href="#aanpassen_menus" aria-label="Anchor link for: aanpassen_menus" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h4>
<div class="level4">
<ul class="fix-media-list-overlap">
<li class="level1"><div class="li"> 1</div>
</li>
<li class="level1"><div class="li"> 2</div>
</li>
<li class="level1"><div class="li"> 3</div>
</li>
<li class="level1"><div class="li"> 43</div>
</li>
<li class="level1"><div class="li"> 54</div>
</li>
<li class="level1"><div class="li"> 456</div>
</li>
<li class="level1"><div class="li"> 87</div>
</li>
<li class="level1"><div class="li"> 98</div>
</li>
<li class="level1"><div class="li"> 80</div>
</li>
<li class="level1"><div class="li"> 0</div>
</li>
<li class="level1"><div class="li"> 67</div>
</li>
<li class="level1"><div class="li"> 45</div>
</li>
<li class="level1"><div class="li"> </div>
</li>
</ul>

</div>
<div class="secedit"><form class="btn_secedit form-inline" method="get" action="/doku.php"><div class="no"><input type="hidden" name="do" value="edit"><input type="hidden" name="rev" value=""><input type="hidden" name="0" value="post"><input type="hidden" name="id" value="group:admin:sidebar"><button type="submit" title="Edit" class="btn btn-default btn-xs">Edit</button></div></form></div>
</div>
</div>
```

**Comment by Digitalin** [comment]
Hi, 

I am curious about this issue. Do you mean that you are using this [old plugin](https://www.dokuwiki.org/plugin:sidebarng) to get a sidebar ? 
Sidebar is already  in Dokuwiki as a wiki page and Bootstrap3 gives you a hook to have it easely by namespaces and with options (right sidebar...). See [Availlable Hooks](https://www.dokuwiki.org/template:bootstrap3#available_hooks) and [Options](https://www.dokuwiki.org/template:bootstrap3#sidebar).
You can have a sidebar by namespaces if you create a start page for each namespace (or whatever name you give to the "start page" in the config manager)
`:start
:sidebar
:foo:start
:foo:sidebar
bar:start
bar:sidebar`
...
which is also true for navbar, pageheader.....

@LotarProject gives you wings :-)

**Comment by Kossygin** [comment]
Hi All,

Thank you for your time!

Just tested it, indeed, the native sidebar doens't have this problem. 

I'm using this old plugin because of the group/user support like an admin/technical/accountancy sidebar (using it at a small company)
Does the native sidebar support that? I can't find anything on it.

**Comment by Digitalin** [comment]
Hello, 

This old plugin had some good tricks :-) I understand why you use it. 
I am not sure you can still have now so easely. You can probably build something with the [include plugin](https://www.dokuwiki.org/plugin:include)  to display according the ACL with the macros @USER, @GROUP. (never use those macros with the include plugin). 

Lotar could have more ideas about this. 

You have also the [userhomepage plugin ](https://www.dokuwiki.org/plugin:userhomepage). It is not exactly the purpose but it can give you help to work around. 

Would be pleased to learn what solution you are going to implement...

**Comment by goochem4u** [comment]
Hello, 

We were gonna use the native sidebar from the Wiki except the native sidebar doesn't support the collapse and expand option given in the bootstrap3 template.

See the screenshot below for more information. As you can see, the sidebar is not working well on the left while it works when it is shown as main page. 

In any case, thanks for the information given above. 

With kind regards

![sidebarimg](https://cloud.githubusercontent.com/assets/18145361/14250117/49f64b42-fa7d-11e5-8af0-9f0e43b002ab.png)

**Comment by LotarProject** [comment]
Hi! This is a Bootstrap Wrapper Plugin bug. I have opened an issue.

**Comment by LotarProject** [comment]
Fixed

**Comment by Kossygin** [comment]
Thanks a lot!
I also fixed it with the native sidebar. 

One question though:
is it possible to have a dropdown menu within a dropdown menu? :)
example sidebar: 
<nav stacked="true">
  * [[menu item 1]]
  * Menu item 2
    * [[item 1]]
    * [[item 2]]
    * Item 3
      * [[subitem 3.1]]
      * [[subitem 3.2]]
</nav> 

if not possible: no problem :)

**Comment by LotarProject** [comment]
Hi! Bootstrap don't have submenu component to preserve usability on mobile/tablet devices (see http://stackoverflow.com/a/18024991).

**Comment by Kossygin** [comment]
Good reason, no problem, thnx for tour time!
Cheers!
