### ISSUE TITLE
TOC with white space does not work

### ISSUE THREAD

**Issue by msjang** [LotarProject/dokuwiki-template-bootstrap3#181]
DOM element cannot have space in its id-attribute.
But, dokuwiki create id-attribute when h1~h6 has string with spaces.

Could you replace space with %20 before running anchorjs?
http://stackoverflow.com/questions/853804

ref)
test page: http://www.shuggie.kr/wiki/test

**Comment by LotarProject** [comment]
Hi! By default DokuWiki replace the spaces with underscore "_" in heading syntax. I think this is a Markdown plugin issue.

At your disposal.
Joseph
