### ISSUE TITLE
TOC space between sections

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#182]
Hello,

The attached screenshot will explain it better than me. To summarize, the space between sections is sometimes wrong. I don't even really know if you'll see it but for me it's pretty obvious : 
http://image.noelshack.com/fichiers/2016/14/1459748678-spacebetween.jpg

Do you know what could cause this behavior ? 
Thank you :-)

**Comment by blacklord049** [comment]
No news for more than a month now ;-)

**Comment by LotarProject** [comment]
Hi! Sorry for my delay :)
I have replicated this issue in my dev enviroment but i don't see the space between the sections. Can you send me (via mail) the original source of the page and the version of template ?

At your disposal,
Joseph
