### ISSUE TITLE
Scrollbar inside the TOC

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#183]
I don't know if it's possible to do that but I'd like to share my thoughts still : if the TOC contains too much elements, it still grows but you know it's impossible to see the end of it. It goes out the limit of the area. The idea is to have a kind of scrollbar inside the TOC itself, and make the content scrollable.

**Comment by blacklord049** [comment]
Well maybe my cache was not up to date but there already is a scrollbar. Sorry for that useless post :-)

**Comment by LotarProject** [comment]
No problem :+1:
