### ISSUE TITLE
Table margin-bottom, css.php

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#184]
Hello,

I've set a 10px margin-bottom for .table{} in my Cerulean CSS but the rule is overriden by "css.php" -> `/lib/exe/css.php?t=bootstrap3&tseed=9700cdf8aa3ca9b99d11df6955eda1aa`
See : http://image.noelshack.com/fichiers/2016/14/1459764508-inspector.png

CSS.php purge done, Browser cache erased, server restarted, but still it does a 20px bottom-margin. Any idea ? 

Thank you

**Comment by AlekSet** [comment]
Did You try with `!important`?
Easly add 
```
.table {
  margin-bottom: 10px !important;}
```
in DOKU_ROOT/conf/userstyle.css works for me.
![table-margin](https://cloud.githubusercontent.com/assets/16212999/14245469/da1133ac-fa61-11e5-9094-f6b47c7ed6c8.png)

**Comment by blacklord049** [comment]
Yeah thank you for the trick ;-) it works
