### ISSUE TITLE
Ability to enable and display the new page form

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-template-bootstrap3#186]
There is a way to add the Addnewpage (https://www.dokuwiki.org/plugin:addnewpage) plugin to a site template.
`<?php echo p_render('xhtml',p_get_instructions('{{NEWPAGE}}'),$info) ?>`

Would be nice to include this, with a proper code and maybe a setting to chose its position.

**Comment by blacklord049** [comment]
In the meantime I added the code on the main.php page... 

```
echo '<div class="dw-content">';
echo $content;
			  			  		
if (!plugin_isdisabled('addnewpage') && $ACT == 'show')
	echo '<p><br />' . p_render('xhtml',p_get_instructions('{{NEWPAGE>'.getNS(getID()).'}}'),$info) . '</p>' ;			

echo '</div>';	
```

Obviously you know better the structure of your template so I prefer to let you do the integration ;-)

**Comment by LotarProject** [comment]
Hi! This plugin is very useful but the problem is the position. I have visited different DokuWiki installations with this plugin installed, and the maintainers of Wiki use this plugin via ``{{NEWPAGE}}`` syntax. The solution is to use the template hooks (HTML or DokuWiki page) or sidebars.

At your disposal,
Joseph

**Comment by blacklord049** [comment]
Thank you :-)  I'll do that

**Comment by LotarProject** [comment]
Hi @blacklord049 , i have reopened this issue/request because i have a new place for this plugin:

![image](https://cloud.githubusercontent.com/assets/1824717/20107638/884b0f2e-a5d9-11e6-9147-0028f0e85308.png)

**Comment by polyzen** [comment]
For some reason it appears to be off:
![](https://ptpb.pw/3r2A.png)

**Comment by LotarProject** [comment]
Hi @polyzen ,
i have added missing style. Please checkout develop branch and flush DokuWiki cache.

Sorry :stuck_out_tongue:

**Comment by polyzen** [comment]
[Looking good](https://ptpb.pw/kw1c.png) :+1:, though I seem to have found an upstream bug.. After disabling & re-enabling the plugin, it doesn't offer the root namespace in the dropdown.

**Comment by LotarProject** [comment]
Hi @polyzen sorry! To enable **root** namespace you can enable ``plugin»addnewpage»addpage_showroot`` option.

**Comment by polyzen** [comment]
Ahh, sorry about that. :p
