### ISSUE TITLE
Media manager not displaying when using IE11, users can't add images or files, urgent HELP !

### ISSUE THREAD

**Issue by help53** [LotarProject/dokuwiki-template-bootstrap3#188]
Hello,

I am using dokuwiki latest version and Template bootstrap3 (might i add a very cool Template).

I need some help from you as i have a big problem :users can't insert images to wiki pages as media manager window (with button select a file and search a file) is not visible when using the browser IE11, As you can see in the image below :

![mediamanager_not_visible](https://cloud.githubusercontent.com/assets/18329131/14351632/abb04996-fcd0-11e5-8166-c801fa4ee6ac.PNG)

Actually when the users click on the top menu media manager, the page is displayed, so the users can add images and files to media manager. However when** they want to add an image while writing a wiki page**, they click on the button insert an image in the toolbar, a pop up page opens, only the namespaces are visible (so only the "sidebar" of the pop up is visible), **the middle of the page with the button upload an image and search an image does not apppear, it is blank**. When i checked the source code, the div containing the buttons appears.

 Here is the source code that i retrieved from IE11 👍 
```
<!DOCTYPE html>
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr"
   lang="fr" dir="ltr" class="popup no-js">
 <head>
   <meta charset="UTF-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <title>Sélection de fichiers [DokuWiki]</title>
   <script>(function(H){H.className=H.className.replace(/\bno-js\b/,'js')})(document.documentElement)</script>
   <meta name="viewport" content="width=device-width,initial-scale=1" />
   <link rel="shortcut icon" href="/lib/tpl/bootstrap3/images/favicon.ico" />
 <link rel="apple-touch-icon" href="/lib/tpl/bootstrap3/images/apple-touch-icon.png" />
     <meta name="generator" content="DokuWiki"/>
 <meta name="robots" content="noindex,nofollow"/>
 <link type="text/css" rel="stylesheet" href="/lib/tpl/bootstrap3/assets/bootswatch/simplex/bootstrap.min.css"/>
 <link rel="search" type="application/opensearchdescription+xml" href="/lib/exe/opensearch.php" title="DokuWiki"/>
 <link rel="start" href="/"/>
 <link rel="alternate" type="text/html" title="HTML brut" href="/doku.php?do=export_xhtml&amp;id="/>
 <link rel="stylesheet" type="text/css" href="/lib/exe/css.php?t=bootstrap3&amp;tseed=019467cbcc6139d34559c1f7fda23e8b"/>
 <link type="text/css" rel="stylesheet" href="/lib/tpl/bootstrap3/assets/font-awesome/css/font-awesome.min.css"/>
 <script type="text/javascript">/*<![CDATA[*/var NS='';var SIG=' --- //[[root@lohr.fr|Administrator]] 07/04/201606:52//';var JSINFO = {"id":"","namespace":"","bootstrap3":{"tableFullWidth":1,"tableStyle":["striped","condensed","responsive"],"tagsOnTop":1,"useAnchorJS":1,"mode":null}};
 /*!]]>*/</script>
 <script type="text/javascript" charset="utf-8" src="/lib/exe/js.php?t=bootstrap3&amp;tseed=019467cbcc6139d34559c1f7fda23e8b"></script>
 <script type="text/javascript" src="/lib/tpl/bootstrap3/assets/bootstrap/js/bootstrap.min.js"></script>
 <script type="text/javascript" src="/lib/tpl/bootstrap3/assets/anchorjs/anchor.min.js"></script>
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
     <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
   <![endif]-->
   <style type="text/css">
     body { position: initial; }
   </style>
 </head>
 <body class="container">
   <!--[if IE 8 ]><div id="IE8"><![endif]-->
   <div id="dw__msgarea">
       </div>
   <div id="media__manager" class="dokuwiki mode_ tpl_bootstrap3 loggedIn notFound  row">

     <div id="mediamgr__aside" class="col-xs-4">
       <h1>Sélection de fichiers</h1>

             <div id="media__opts"></div>
         <div id="media__tree">

 <ul class="idx">
 <li class="media level0 open"><img src="/lib/images/minus.gif" alt="−" /><div class="li"><a href="/lib/exe/mediamanager.php?ns=" class="idx_dir">[racine]</a></div>
 <ul class="idx">
 <li class="media level1 closed"><img src="/lib/images/plus.gif" alt="+" /><div class="li"><a href="/lib/exe/mediamanager.php?ns=manuel_utilisateur" class="idx_dir">manuel_utilisateur</a></div></li>
 <li class="media level1 closed"><img src="/lib/images/plus.gif" alt="+" /><div class="li"><a href="/lib/exe/mediamanager.php?ns=nomenclature" class="idx_dir">nomenclature</a></div></li>
 <li class="media level1 closed"><img src="/lib/images/plus.gif" alt="+" /><div class="li"><a href="/lib/exe/mediamanager.php?ns=wiki" class="idx_dir">wiki</a></div></li>
 </ul></li>
 </ul>
 </div>
       </div>

       <div id="mediamgr__content" class="col-xs-8">
         <div id="media__content">
 <h1 id="media__ns">:</h1>
 <div class="upload">Envoyez un fichier dans la catégorie actuelle. Pour créer des sous-catégories, préfixez en le nom du fichier séparées par un double-point, après avoir choisis le(s) fichier(s). Le(s) fichier(s) peuvent également être envoyé(s) par glisser-déposer (drag &amp; drop)</div><div class="no"><input type="hidden" name="sectok" value="bdee5efdc113fbe62104500267dbc208" /></div>

 <div id="mediamanager__uploader">
 <form id="dw__upload" enctype="multipart/form-data" action="/lib/exe/mediamanager.php" method="post" accept-charset="utf-8"><div class="no">
 <input type="hidden" name="sectok" value="bdee5efdc113fbe62104500267dbc208" /><input type="hidden" name="ns" value="" /><div class="no"><input type="hidden" name="sectok" value="bdee5efdc113fbe62104500267dbc208" /></div>
 <p >
 <label for="upload__file"><span>Sélectionnez un fichier à envoyer:</span> <input type="file" id="upload__file" name="upload" class="edit" /></label>
 </p>
 <p >
 <label for="upload__name"><span>Envoyer en tant que (optionnel):</span> <input type="text" id="upload__name" name="mediaid" class="edit" /></label>
 <button type="submit">Téléverser</button>
 </p>
 <p >
 <label class="check" for="dw__ow"><input type="checkbox" id="dw__ow" name="ow" value="1" /> <span>Écraser le fichier cible (s'il existe)</span></label>
 </p>
 </div></form>
 </div>
 <p class="maxsize">Taille d'envoi maximale : 2 MB par fichier</p>
 <form id="dw__mediasearch" action="/lib/exe/mediamanager.php" method="post" accept-charset="utf-8"><div class="no">
 <input type="hidden" name="sectok" value="bdee5efdc113fbe62104500267dbc208" /><input type="hidden" name="ns" value="" /><input type="hidden" name="do" value="searchlist" /><p >
 <label><span>Chercher le nom de fichier :</span> <input type="text" name="q" class="edit" title="Chercher dans :*" /></label>
 <button type="submit">Rechercher</button>
 </p>
 </div></form>
 <div class="nothing">Pas de réponse.</div>
 </div>
       </div>

   </div>
   <!--[if IE 8 ]></div"><![endif]-->
 </body>
 </html>
```

**I opened the media manager from the toolbar using Mozilla Firefox and surprisingly : it works**, i could add images and files to my page. 

 So **how to make that page IE11 compatible**, because in my company we use only IE11 and can't use any other browser. 

 Please help me out as i need to present this wiki in working condition to my boss :(

 Thank you for your help

**Comment by LotarProject** [comment]
Hi! Fixed in dev and master branch.
Can you update or reinstall via Extension Manager ?

After update, purge DokuWiki cache (via ``lib/exe/css.php?purge`` and ``lib/exe/js.php?purge`` URL) and browser cache.

(Finally i have resurrected a Win7 VM to fix IE issues)

At your disposal,
Joseph

**Comment by help53** [comment]
Hello, 

**Thank you for your quick reply**, do i ve to update whole dokuwiki or only the Template bootstrap3? How can i update the Template ? 
Actually i have changed a lot of colours and stuff (css) so if i reinstall the whole Template i ll loose all those changes which is quite problematic as i don't remember all the changes i did.

Thank you for your reactivity .

**Comment by LotarProject** [comment]
Update only the template (bootstrap3) via Extension Manager > Installed Template > Bootstrap3 Template > Re-Install (or Update).
If you have customized DokuWiki files in ``conf`` directory (eg. ``userscreen.css``, ``userscript.js``) will be preserved during upgrade of template.

At your disposal,
Joseph

**Comment by help53** [comment]
Ok, actually i am using Template simplex (bootswatch) and i modified the colours and font style in bootstrap.min.css located in simplex folder. 
I think i modified the css the wrong way, do i ve to create the file usercreen.css and do all the changes in that or what is the right way to change the css ?
I searched in dokuwiki but it was quite confusing, so i did how i thought...

sorry to disturb you with my questions but as i am a newbie i really needed help from experts :)

**Comment by LotarProject** [comment]
No problem ;)

Generally is not correct to edit directly ``bootstrap.css`` (and other files in ``asset`` directory) because will be overvrited in upgrade of template or for new Bootstrap's release.

The correct way to preserve the customization is create a CSS file in ``conf`` directory.

Recently i have created a new DokuWiki plugin (https://www.dokuwiki.org/plugin:advanced) to manage and edit the files presents in ``conf`` directory directly from DokuWiki Admin page.

At your disposal,
Joseph
