### ISSUE TITLE
h1 word break error in ie

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#189]
Long time no see.
I have a question with ie11 browser.

My homepage url is http://www.animint.net/
If you access my homepage with ie11 in mobile,
you can see h1's word break because of toc.

I used 'line-break:keep-all' css,
It is worked with Chrome in mobile,
(H1 is positioned toc's bottom side.)
but IE is breaking.

My homepage language is korean.
How can I change css?

**Comment by LotarProject** [comment]
Not reproducible
