### ISSUE TITLE
Config-parameters not shown properly when using a darker Bootswatch Theme (e.g. SLATE)

### ISSUE THREAD

**Issue by oscon** [LotarProject/dokuwiki-template-bootstrap3#191]
When using a darker Bootswatch Thme (e.g. SLATE), config-parameters in ADMIN are not shown properly: Is there a possibility (hack, hint or something else) to overrule this manually?

![2016-04-14 17_42_14-konfiguration oswald web](https://cloud.githubusercontent.com/assets/478932/14534343/080868f2-0269-11e6-9ffe-fd1f5e4a9852.jpg)

**Comment by help53** [comment]
Hello, 

I think you ve to change the css of the fonts (colour of headings, contents, label ...)

I hope i ve helped you :)

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. Resolved in last commit on dev branch.
