### ISSUE TITLE
QUESTION:How to create an administration menu as shown in the visual tour of dokuwiki ?

### ISSUE THREAD

**Issue by help53** [LotarProject/dokuwiki-template-bootstrap3#195]
Hello, 

i would like to create an administration menu (usermanager, access control list, extension manager...) as it is shown in the picture in dokuwiki, how to proceed ?

Currently i ve to go administration page and then select in the page which is quite tiring, i liked your idea of creating an admin menu with all the Tools available directly, saves a lot of time !

Awaiting for your reply 
thanks !

**Comment by polyzen** [comment]
You seem to be talking about the tpl»bootstrap3»showAdminMenu configuration option.

**Comment by help53** [comment]
Oh thank you its working very well !!!
