### ISSUE TITLE
QUESTION : what is the meaning of the option "verify" in the parameters disableActions ?

### ISSUE THREAD

**Issue by help53** [LotarProject/dokuwiki-template-bootstrap3#197]
Hello !

I have some questions regarding the parameter "disableactions" in the config manager, actually in the options of this parameter there is "verify", could you explain its meaning, please.

![verify_config](https://cloud.githubusercontent.com/assets/18329131/14666144/0fc15b8a-06d8-11e6-8b8d-424130945e4f.PNG)

I also have one more question as you are a pro in dokuwiki, do you know if there is a way to add a contact form in the navbar ? Actually i would like to give the ability to any visiter of the wiki, to send an email to the author of the article they are reading (in order to send some remarks), do you ve any idea on how do i proceed ? 

Thanks ,
Awaiting for your reply :)
Help53

**Comment by LotarProject** [comment]
Hi! Verify action (a.k.a. ``?do=check``) display useful informations of your DokuWiki installation (DW and PHP version, permission, etc) and namespace/page ACL.

This template have only a button to send the DokuWiki link via email to a friend. I have discovered "Authorlist" plugin (https://www.dokuwiki.org/plugin:authorlist) can you add author name (or home-page or email) on every page or by adding ``~~AUTHORS~~`` syntax.

**Comment by help53** [comment]
Hello, 

thank you for your response.

**Comment by polyzen** [comment]
@help53, could you close this since it's resolved?

**Comment by help53** [comment]
hello , 

Actually i am new to github could you tell me how to close an issue ? 

Thanks

**Comment by LotarProject** [comment]
Can you close an issue using "Close issue" button below the comment textarea.
