### ISSUE TITLE
Multiple Table Headers, display question

### ISSUE THREAD

**Issue by aliasedv2** [LotarProject/dokuwiki-template-bootstrap3#199]
From 
http://futanari.org/wiki/%E3%83%95%E3%82%BF%E3%83%8Alist/westerncomics.2016.digital

If you scroll down you can see a list of tables... is it possible to define each header as <thead> instead of just the first of a series?

The code on the page follows format as such:

`^  ^ ^`
`|  |  |`
`|  ||`
`^  ^ ^`
`| | |`
`|  ||`

**Comment by LotarProject** [comment]
Hi! I'm not sure I understand ;) ... With Bootstrap theme, can you have one fixed header per table. I think this is the solution:

```
^ ^ ^
| | |
| ||

^ ^ ^
| | |
| ||
```

At your disposal,
Joseph
