### ISSUE TITLE
Upload media dont work with this theme

### ISSUE THREAD

**Issue by fenshu666** [LotarProject/dokuwiki-template-bootstrap3#20]
Hello,
When i select a file to upload anbd press upload button, there is no loading % with this theme...
it work with dokuwiki theme...
and there is no upload...
![ecran257](https://cloud.githubusercontent.com/assets/12064618/7270448/82eaaf8c-e8dc-11e4-838c-331b1f06cb8e.png)

**Comment by jreso** [comment]
I have the same problem. 
And when I clic on the name of a category (left menu), even it is the same, the appearance change, and I can upload.

There is no problem to upload with "?do=media".
![media-not-ok](https://cloud.githubusercontent.com/assets/6763556/7333241/138aadc0-eb68-11e4-9db1-d48eb32cc1ba.png)
![media-ok](https://cloud.githubusercontent.com/assets/6763556/7333242/138b235e-eb68-11e4-95b8-bc6de1e1726d.png)

**Comment by neuralyzer** [comment]
Same here. Upload not working from within the editor. However, upload does work using the `lib/exe/mediamanager.php` mediamanager.

**Comment by LotarProject** [comment]
Hi. I have fixed this issue in commit c69d071.

**Comment by neuralyzer** [comment]
Seems to work for me. Thanks.

**Comment by fenshu666** [comment]
it works too ! Thank you !

*  * RESO-NANCE numérique    LFO FABLAB         ////>
*41 rue Jobin 13003 MARSEILLE | N° Siret: 523 736 650 00020 Code APE:
9499Z www.reso-nance.org  |  http://lfofablab.org



2015-05-07 8:33 GMT+02:00 neuralyzer <notifications@github.com>:
