### ISSUE TITLE
Admin Menu Collapses too fast

### ISSUE THREAD

**Issue by issmirnov** [LotarProject/dokuwiki-template-bootstrap3#200]
Hey,

First of all, thank you for a superb theme - it's recharged my flow and made my wiki a true pleasure to use.

I noticed there's a bug in the latest release that causes the mobile admin menu to collapse the moment I scroll past the bottom boundary. A similar problem was present with the mobile sidebar which was recently fixed, so hopefully it's a simple tweak again.

Demo:
![menu collapse](https://cloud.githubusercontent.com/assets/5771615/14764435/27cba9a6-096c-11e6-8179-dad640cf1e8c.gif)

Desired outcome:

- Make the buffer below the menu bigger so I can select items from it without the menu collapsing. Whatever you did with the sidebar worked.

**Comment by issmirnov** [comment]
Hi maintainers,

Can I get this tagged as a bug, or some sort of update?

Thanks,
- Ivan

**Comment by LotarProject** [comment]
Hi Ivan, thanks for reporting this issue.
What browser and version are you using ?

At your disposal,
Joseph

**Comment by issmirnov** [comment]
Hi,

I'm running the latest release of both dokuwiki and this theme. There are no major customizations in `userstyle.css` or `userscript.js` (I changed a font and removed some toolbar icons). I have reproduced this issue on the following browsers:

- Firefox on OSX 10.10
- Chrome on OSX 10.10
- Chrome on Android M

Can you take a look at this on your end and see? 

Thanks,
-Ivan
