### ISSUE TITLE
Problem with Show Individual Tool

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#201]
Hi,

Testing a bit some features in a local wiki, I noticed in show Individual Tool that Dokuwiki content page stops displaying if you uncheck "page" or "site" (enable by default).  Only sidebar or pageheader content is displaying. 
Need  to add manually : `$conf['tpl']['bootstrap3']['showIndividualTool'] = 'site,page';`
in  /conf/local.php to work around the bug. 
user unchecked is ok.

**Comment by polyzen** [comment]
@Digitalin, did you get a chance to try the fix?

**Comment by Digitalin** [comment]
Hi polizen,

No, till you asked :-)

Yes, it works !
* Without all {user,site,page} (mean unchecked) you get nothing in the tool menu, so you need to use 
the `?do=admin ` in adress bar. In this case, it is relevant to put "never" in the line "Display tool in the menu.." because tool icone is still there for nothing
* Without {user,page} you get recent changes, media manager and sitemap in the tool menu and still need to use `?do=admin`
* Without {user} this adds tools of page (modify, old revision, plugin tools as pdf, rename...) and still need to use `?do=admin`
* Finally {user} also checked gives you Profil update, logout and Admin manager if user is a superuser

It could different according to options wanted to display in tools menu in Bootstrap config and also according plugins installed. 

Bug is fixed. Tanks Joseph :-)

**Comment by polyzen** [comment]
The fix works for me as well. :+1: @Digitalin, if you closed this, it would be appreciated.

Any ideas how those situations that leave you without a link to the admin page/s can be handled? Perhaps there should be an issue opened for it.

**Comment by Digitalin** [comment]
Hi Polyzen,

It is why I always do things like test, update, upgrade and plugins install on a local wiki and most of the time one by one to check all is okay before doing on a prod wiki. It is a bit longer but uptime is nice and not having bad surprise:-)
I close the issue.
