### ISSUE TITLE
About the sidebar , how judge the current active item ?

### ISSUE THREAD

**Issue by ZHANGYANKUN** [LotarProject/dokuwiki-template-bootstrap3#203]
I see the author's wiki homepage ,when I click the sidebar itme then the background-color is on the current item , How to make author's effect ?

**Comment by LotarProject** [comment]
Hi! If i understand the question, can activate/highlight the item of current page in sidebar by adding ``~~NOCACHE~~`` macro in sidebar page (see https://www.dokuwiki.org/faq:sidebar#how_can_i_have_an_automatic_navigation_in_my_sidebar).

At your disposal,
Joseph!

**Comment by ZHANGYANKUN** [comment]
Very thanks ，follow your method I have solve this question .

**Comment by polyzen** [comment]
@ZHANGYANKUN, could you close this now that it's resolved? :)
