### ISSUE TITLE
How to insert background picture to one or all pages?

### ISSUE THREAD

**Issue by Raketenphysik** [LotarProject/dokuwiki-template-bootstrap3#204]
What would be the most appropiate way to insert a background picture to all or just some selected pages?

Thanx, Mark

P.S.: Best template for DW. Apprechiate your effort. Great job.

**Comment by GitHub-Mike** [comment]
https://www.dokuwiki.org/template:bootstrap3#customize_the_theme

Mike

**Comment by Raketenphysik** [comment]
Thanks Mike. That was a no-brainer. Sorry.
