### ISSUE TITLE
navbar dropdown menu don't toggle (expand)

### ISSUE THREAD

**Issue by GitHub-Mike** [LotarProject/dokuwiki-template-bootstrap3#205]
My navbar dropdown menu don't toggle (expand). I see no js error. Perhaps a css problem?

Is this the default layout?  No changes - but Is not my layout!

![template-navbar-page](http://lotar.altervista.org/dokuwiki/_media/wiki/template/bootstrap3-template-navbar-page.png)?

Here my generated html source code:

`<ul class="nav  navbar-nav">
<li class="level1 node dropdown"><a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"></a><a title="start" class="wikilink1" href="/dokuwiki/doku.php?id=start"><i title="" style="font-size:16px" class="fa fa-home"></i> Start</a> <span class="caret"></span>
<ul role="menu" class="dropdown-menu">
<li class="level2"> <a rel="nofollow" title="playground:start" class="wikilink2" href="/dokuwiki/doku.php?id=playground:start">playground</a></li>
<li class="level2 active"> <a title="playground:navbar" class="wikilink1" href="/dokuwiki/doku.php?id=playground:navbar">navbar</a></li>
<li class="level2"> <a title="playground:sidebar" class="wikilink1" href="/dokuwiki/doku.php?id=playground:sidebar">sidebar</a></li>
</ul></li></ul>`

Mike

**Comment by LotarProject** [comment]
Hi! I have discovered an error in your HTML snippet. Can you send the DokuWiki source of ``:navbar`` hook ?

At your disposal,
Joseph

**Comment by GitHub-Mike** [comment]
Do you mean the code from :navbar node?

`  * {{fa>home}} [[:start|Start]]
    * [[:playground:start]]
    * [[:playground:navbar]]
    * [[:playground:sidebar]]
~~NOCACHE~~`

Sorry, the code area strips the line-breaks.

Mike

**Comment by LotarProject** [comment]
Hi! Thanks for your snippet.
The problem is the link in first item. The parent item of dropdown-list must be a text.

```
  * {{fa>home}} Start
    * [[:playground:start]]
    * [[:playground:navbar]]
    * [[:playground:sidebar]]
~~NOCACHE~~
```

At your disposal,
Joseph

**Comment by GitHub-Mike** [comment]
Hi Joseph,

thanks, it works now!

Mike
