### ISSUE TITLE
Table alignement incorrect

### ISSUE THREAD

**Issue by davidrolli** [LotarProject/dokuwiki-template-bootstrap3#206]
Tables are not formatted the same way although the code is not different. In example code Column 2 of table 2 and table 3 are each indented, but should not.

***** Example Code Start ****

===== Teilzonenplan =====
=== np_tzp_Datenchck_ITF_to_shp_LV95 ===
np_tzp_Datenchck_ITF_to_shp_LV95.fmw

^ DVS ready  ^ Ja  |
^ Datenmodell   | BL_TEILZONENPLAN_LV95  |
^ Input  | ITF  |
^ Output  | SHP  |
^ Beschreibung  | Kontrolle der Verknüpfungen und der Geometrie; {{:gi:np_tzp_Datenchck_ITF_to_shp_LV95.pdf|}}  |

=== np_tzp_Datenchck_ITF_to_shp_LV03 ===
np_tzp_Datenchck_ITF_to_shp_LV03.fmw

^ DVS ready  ^ Ja  |
^ Datenmodell   | BL_TEILZONENPLAN  |
^ Input  | ITF  |
^ Output  | SHP  |
^ Beschreibung  | {{:gi:np_tzp_Datenchck_ITF_to_shp_LV03.pdf|}}  |

=== DUP_ERROR_bereinigen ===
DUP_ERROR_bereinigen_Teilzonenplan_1_1_arc_LV95.fmw

^ DVS ready  ^ Ja  |
^ Datenmodell   | BL_TEILZONENPLAN_LV95  |
^ Input  | ITF  |
^ Output  | ITF, SHP  |
^ Beschreibung  | {{:gi:dup_error_bereinigen.pdf|}}  |

***** Example Code Start ****

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. I have replicated your issue in my dev environment and i think the problem is ``tableFullWidth`` option to ``off``.
Can you send me a screenshot of your page ?

At your disposal,
Joseph
