### ISSUE TITLE
Sidebar disappears

### ISSUE THREAD

**Issue by Laurent3170** [LotarProject/dokuwiki-template-bootstrap3#207]
The sidebar on https://wikidurable.org appears and then disappears with no possibilities to open it.
Is it due to `<div class="dw-sidebar-title toogle hidden-lg hidden-md hidden-sm" data-toggle="collapse" data-target="#dokuwiki__aside .dw-sidebar-body">` where to**o**gle should be to**g**gle ?

**Comment by LotarProject** [comment]
Hi! This (toogle) class is a typo error and is no longer used in my template. I have removed this class from dev branch.
I have investigated on your website and i have discovered the problem. In your ``style.css`` file don't have some "responsive" Bootstrap's classes. In particular your template lacks ``visibile-*-block`` (and ``visible-*-inline``) classes used in Bootstrap3 template to adapt the template for different devices.

At your disposal,
Joseph

**Comment by Laurent3170** [comment]
Hi! Thanks for your investigation! As the styles.css is automatically created from bootstrap magic, I will have to add those classes manually I think. As it was working before the update, I think it is due to the removal of the classes from the dev branch. I will look at the mentioned classes.
Thanks!

**Comment by Laurent3170** [comment]
So... I have just copied/pasted from the original bootstrap file and it works!
Really thanks!

**Comment by Laurent3170** [comment]
Maybe a "good" thing will be to load both, bootstrap.css and styles.css (which is the value in bootstraps3 > customTheme), like this there will be no other missing classes ?
