### ISSUE TITLE
Why my editor area becomes so small ?

### ISSUE THREAD

**Issue by ZHANGYANKUN** [LotarProject/dokuwiki-template-bootstrap3#209]
Why my editor area becomes so small ? But , I use the default theme is normal size .

How to make it to be fullwidth ?

![2016-05-04-00001](https://cloud.githubusercontent.com/assets/3318669/15004123/aeb1ff52-11e5-11e6-8363-9a306da38203.png)

**Comment by Soeldner** [comment]
Normally should be 100%. You can test and write in your userall.css.

```.dokuwiki textarea.edit {
     min-width: 100%;
}```

or force

```.dokuwiki textarea.edit {
     min-width: 100% !important;
}```

**Comment by ZHANGYANKUN** [comment]
I have know the reason  , because I  was deleted the  default theme !

Thx!
