### ISSUE TITLE
todo-plugin

### ISSUE THREAD

**Issue by berot3** [LotarProject/dokuwiki-template-bootstrap3#21]
When using dokuwiki.org/plugin:todo the checkbox is misplaced. it looks like it puts a huge space between checkbox and the text and therefore breaks line so that the checkbox is at the end of the first line and the text itself is in the second line. Makes todo almost unusable with bootstrap3.

when switching back to dokuwiki it looks as usual.

**Comment by LotarProject** [comment]
Hi, thanks for reporting this issue.
I have fixed this issue in my last commit.

Best regards,
Joseph

**Comment by berot3** [comment]
Great! Thank you! 
So when will this commit land in the regular theme I can get from dokuwiki.org?

**Comment by LotarProject** [comment]
The last commit is available for downloading from dokuwiki.org
