### ISSUE TITLE
Cannot switch to BootSwatch Theme - PHP Warning

### ISSUE THREAD

**Issue by briangig** [LotarProject/dokuwiki-template-bootstrap3#210]
Hi, I was using a version of Boostrap3 from the end of last year, and updated to the latest version just now.  Now when I attempt to switch to a different BootSwatch theme, I get the following error:

PHP Warning:  Cannot modify header information - headers already sent by (output started at E:\dokuwiki\inc\template.php:1814) in E:\dokuwiki\inc\common.php on line 1911

Sometimes it is on line 444 of template.php.  I have tried removing the template and reinstalling, but the same error returns.

Thank you!

**Comment by LotarProject** [comment]
Hi! i think this is a cookie problem. Can you delete the DokuWiki cookie (or use private browser) and retry to change the themplate from ThemeSwitcher?

At your disposal,
Joseph

**Comment by briangig** [comment]
Hi, I am a horrible person but I forgot about this.  I ended up downgrading the plug, but just now was upgrading my plugins and ran into this again, same error. I have tried on multiple browsers and computers.  I will be attempting to update to Elenor this weekend, but wanted to let you know it was not a cookie issue that I can see.

**Comment by briangig** [comment]
Hi, I bit the bullet and updated, but it did not resolve the issue.  I removed and re-installed the plugin, which also did not resolve the issue.

I attempted to update from PHP 5.x to 7.x, but reverted back to 5.x due to time contraints, and I am now able to change themes via the switcher!
