### ISSUE TITLE
footer and rightsidebar DokuWiki hook by namespace

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#211]
Hi, 

As navbar, sidebar and pageheader Dokuwiki hook works perfectly well by namespace from my side, I am testing the footer in same conditions. But if it works at the root for the whole wiki :footer, I can't have it working for :bar:footer.  Nothing is displaying. As I did'nt test yet all hooks, I have investigated further and : 

- pageheader is ok
- pagefooter is ok
- sidebar is ok
- rightsidebar :

as I have the sidebar on and in left position in Bootstrap config, I add : rightsidebar string to the config to get it as explained.   rightsidebar's content is displaying only where there is a sibebar but following bellow in my case the left sidebar. I am not sure if it is possible in this case to have only rightsidebar by namespace but anyway, something goes wrong. Surely, with the brilliant [advanded config plugin](https://www.dokuwiki.org/plugin:advanced), it  is probably easy to work around with html hook but I appreciate the simplicity of DokuWiki hook. 

Last Bootstrap release is running (Wed, 20 Apr 2016 12:07:01 +0200) and all is up to date. 

A little thing : there is some strings not translated  in french and [transifex](https://www.transifex.com/lotar-project/dokuwiki-template-bootstrap3/language/fr/) says 100 % done.  I can translate it.

Thanks for attention.

**Comment by LotarProject** [comment]
Hi! The Footer Hook have the same function (``tpl_include_page()``) and behavior of others DokuWiki hooks.
Yes, the right sidebar have this behavior/limitation, since the first release of template. I'm to work to remove this limitation.

Thanks for your contribution on Transifex!

At your disposal,
Joseph

**Comment by LotarProject** [comment]
@Digitalin I have pushed in dev branch a patch to solve the right sidebar issue.

**Comment by Digitalin** [comment]
Hi, 
After template reinstallation (same release : 2016-04-13) on local wiki, all strings are now in French in Config manager and footer works well by namespace. A little thing went wrong with the first install.

Thanks for your patch that I am going to test soon.
