### ISSUE TITLE
Problem with snippets plugin popup-window

### ISSUE THREAD

**Issue by moz0817** [LotarProject/dokuwiki-template-bootstrap3#213]
I use your wonderful template. Unfortunately it don't work with snippets plugin.

This ist the popup **without** your template:
![snippets ok](https://cloud.githubusercontent.com/assets/2591552/15397520/cbc1b342-1de0-11e6-9a6a-bde7ba6935ae.png)

... and this **with** bootstrap template active:
![snippets fail](https://cloud.githubusercontent.com/assets/2591552/15397750/94f9b232-1de1-11e6-9b72-7ab401a1fbe2.png)

It's not only the wrong view, the functionality (preview, import) also don't work.

**Comment by bradszabo** [comment]
This is not an enhancement, this is a bug. The theme only recently stopped working with the snippets plugin.

**Comment by LotarProject** [comment]
@bradszabo Can you specify latest version of Bootstrap3 template work ?

**Comment by Lethert** [comment]
no, did not work with the actual version of the theme.

**Comment by bradszabo** [comment]
Thanks, Giuseppe! I apologize, I had not seen a notification about your request on 7/26. I just saw notification about the closing of this. I updated to the current master branch HEAD (commit f8f82f4) and confirmed that the snippets plugin is working properly again. Thanks again.
