### ISSUE TITLE
Support correct styling of sitemap in the sidebar (simplenavi ? )

### ISSUE THREAD

**Issue by Braintelligence** [LotarProject/dokuwiki-template-bootstrap3#214]
Using the indexeverywhere plugin (https://www.dokuwiki.org/plugin:indexeverywhere) I display the sitemap in the sidebar, but it doesn't look like the sitemap site itself.

![image](https://cloud.githubusercontent.com/assets/6761196/15455473/8c6c5a72-2055-11e6-944d-c4830777e969.png)

versus

![image](https://cloud.githubusercontent.com/assets/6761196/15455475/966394d2-2055-11e6-9480-eaa9808f7fdd.png)

The best way would be for you to support the simplenavi plugin: https://www.dokuwiki.org/plugin:simplenavi

That would be awesome!

**Comment by Valiantiam** [comment]
Have to agree here - I am desperately looking for a way to integrate the sitemap design into the sidebar, basically.

Indexmenu does some of this but the indenting it does is sometimes confusing for those not used to tree's like that. (my users often complain about it looking like a page is in a folder when it is in the folder they have opened and just ordered below other "folders")

**Comment by polyzen** [comment]
:+1:

Couldn't manage to get the fix to apply to pages open prior to updating, but a sidebar sitemap isn't for me, anyhow. :p
