### ISSUE TITLE
showThemeSwitcher doesn't put anything in navbar

### ISSUE THREAD

**Issue by drilus** [LotarProject/dokuwiki-template-bootstrap3#216]
Toggling **showThemeSwitcher** doesn't seem to produce any results in the navbar.

**Comment by drilus** [comment]
Nevermind, it appears you need to set "**bootstrapTheme**" from _default_ to _Bootswatch.com theme_.

**Comment by LotarProject** [comment]
Yes, the theme selector is available only for Bootswatch themes.
