### ISSUE TITLE
Suggestion: Integrate support for Linkbacks plugin

### ISSUE THREAD

**Issue by downhamdave** [LotarProject/dokuwiki-template-bootstrap3#217]
Some plugins such as Linkbacks utilise various CSS (please see https://github.com/dokufreaks/plugin-linkback/issues/11 ) and am advised: 
"It looks like the .less code is e.g. changing the background-color to inherit.

So it really seems to be a template issue. I suggest to open a new issue in the bootstrap3 issues section."

As I say some plugins use CSS from the style.ini files?
e.g. ` background-color: __background_alt__;`

All of these plugins can therefore look odd in bootstrap3 colour schemes, as the style.ini colours don't reflect the theme.

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. Some plugins use ``style.ini`` placeholders but don't respect Bootstrap color schema.
I have created a custom CSS classes to integrate LinkBack plugin with Bootstrap3 template.

At your disposal,
Joseph
