### ISSUE TITLE
footer overlaps main area and wrong width (IE and OPERA)

### ISSUE THREAD

**Issue by Soeldner** [LotarProject/dokuwiki-template-bootstrap3#218]
Hi,

in OPERA and IE overlaps footer the main area (see pdf file) [opera_ie_bug.pdf](https://github.com/LotarProject/dokuwiki-template-bootstrap3/files/314837/opera_ie_bug.pdf). 

In firefox and chromium its ok.

/footer code

```
~~NOCACHE~~
<grid>
<col sm="4">
<panel type="default" title="Kontakt" icon="fa fa-paper-plane-o">
Reichardt Informationstechnik

...
</panel>
</col>
<col sm="4">
<panel type="default" title="Sitemap" icon="fa fa-sitemap">
  * [[:firma|Reichardt Informationstechnik]]
  * ...
</panel>
</col>
<col sm="4">
<panel type="default" title="Informationen" icon="fa fa-info">
  * [[:informationen|Informationen]]
  * ...
</panel>
</col>
</grid>

[[:firma:kontakt|{{:template:contact_banner_35.png|}}]]
```
The change of the "position" attribute was not successful. Any Idee?

Next, in opera and ie the footer class `<div class = "navbar-text">` is not 100% of the footer container class. 

Change
```
#dw__footer .navbar-text { 
margin-left: 0px;
margin-right: 0px;
}
```
in
```
#dw__footer .navbar-text { 
margin-left: 0px;
margin-right: 0px;
width: 100%;
}
```
works for me.

**Comment by Soeldner** [comment]
In Opera and IE the "footer" has the following entries:

```
.navbar-fixed-bottom {
border-bottom-width: 0px;
border-left-width: 0px;
border-right-width: 0px;
border-top-width: 1px;
bottom: 0px;
margin-bottom: 0px;
}
```

Removal `bottom: 0px;` ends the overlap. The whole is on the bootstrap.min.css.

**Comment by LotarProject** [comment]
Thanks for your screenshot :+1: 

Fixed in dev branch!
