### ISSUE TITLE
Best way to use a plugin shortcode in pageheader.html

### ISSUE THREAD

**Issue by lucker999** [LotarProject/dokuwiki-template-bootstrap3#22]
Thank you for awesome template! I really enjoy responsive design and hooks (I'm big fun of Genesis template for wordpress also)! 

I try to use nspages plugin in order to display the list of namespaces (building kind of dictionary). Alas, placing `<nspages>` doesn't work. Seems like dokuwiki treats this as an html tag and adds the closing tag `</nspages>` at the end of the page. 

I understand that I could use an php function, but my skills in php below the newbi - I'm able to copypaste some code only with minor adjustments.

Could you please advise the best way to utilize a plugin shortcode in the template hooks?

**Comment by LotarProject** [comment]
Hi! Thanks for using my template :)

I prefer this method to extend DokuWiki template:

  * Create (or using an existent) DokuWiki page with the plugin code
  * Open the ````pageheader.html```` hook and place this code:
````php
<?php tpl_include_page('namespace:page'); ?>
````
  * Enjoy

Best regards,
Joseph
