### ISSUE TITLE
Footnote error and change css like mediawiki

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#220]
Thank's to insert 'overlay' function in this template!

I have another problem with 'footnote'.
In latest version template,
If I touch footnote, each footnote hide in navbar.
Would you mind modify this function?

And.
I think, look like better that footnote change like mediawiki in mobile.
If I touch footnote number, It show in mobile's bottom area.
How about think this opinion?

Thank's read my opinion.

**Comment by LotarProject** [comment]
Thanks for your UX ideas!
