### ISSUE TITLE
Disable TOC in mobile view

### ISSUE THREAD

**Issue by sanctus17** [LotarProject/dokuwiki-template-bootstrap3#222]
Hi,

I noticed, that after upgrading to the newest bootstrap, the TOC will always show in mobile view (p.e. on iPhone).

If I am correct, the TOC was disabled in mobile view in the previous release - which made sense to me as its appearance would shift the whole page down and interfere with reading.

Is there any way to change it back to the old behavior?

Thank you for your excellent work!

Cheers,
T

**Comment by polyzen** [comment]
Looks alright to me, but perhaps instead the TOC button could be made to fit in the margin while in mobile view?

**Comment by LotarProject** [comment]
Hi @sanctus17,
can you specify your template version ?

At your disposal,
Joseph

**Comment by sanctus17** [comment]
Hi Joseph,
I am using Bootstrap3 Template [v2016-04-13] on Dokuwiki Release 2014-09-29d "Hrun".

Thank you,
T

**Comment by zicklag** [comment]
I would like to have to TOC always minimized by default on the mobile view. I could set the config so that the TOC is always minimized, but I like it to be maximized by default on the desktop views.
