### ISSUE TITLE
new DokuWiki release "Elenor of Tsort" 

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#223]
Hi, 
I am testing the new DokuWiki release in a local copy. All seems to work with Bootstrap3 (and with installed plugins included all Lotar plugins). I have just to give to navbar a "read " permission in ACL, what was not needed (surprisingly) in detritus, (not an issue). 
For me, it works well :-)

**Comment by LotarProject** [comment]
Thanks for your feedback.

In this week i have the plan to release a new template version!

**Comment by Digitalin** [comment]
Two new releases in the same week. :smile: 
Curious to see what's up with Bootstap3's template :yum:

**Comment by Soeldner** [comment]
I have updated 2 pages. Works great with Bootstrap. Thanks for your work!

**Comment by LotarProject** [comment]
In this new release of DokuWiki ("Elenor of Tsort") is introduced a check of ACL in this functions used for include the sidebar and hooks:

  * ``tpl_include_page``
  * ``page_findnearest``

This ACL check break compatibility of most template (and plugins?). For Bootstrap3 template i have introduced a new config (disabled by default for compatibility) to control the ACL check for sidebars and DokuWiki hooks.
