### ISSUE TITLE
ToC missing styling when expanded

### ISSUE THREAD

**Issue by HanFox** [LotarProject/dokuwiki-template-bootstrap3#227]
Is it intended with the v2016-07-05 release that the ToC when expanded has no borders/background styling any more or have I missed something? It seems to be missing some inner divs that it used to have.

This is what it looks like now:
![screenshot_2016-07-07_14-14-39](https://cloud.githubusercontent.com/assets/1781312/16654355/48a23e3a-444d-11e6-84da-465b6632e559.png)

**Comment by LotarProject** [comment]
Hi! The v2016-07-05 version introduce the new immersive layout inspired from Bootstrap documentation (see http://getbootstrap.com/getting-started/).
I'm investigating to reduce the excessive space of TOC on right of your screenshot

**Comment by HanFox** [comment]
The lack of theming breaks usability and makes it visually confusing. I'm glad I tested it first. 

The white space, though wasteful, isn't that bad.

Is your intention to leave it unstyled?

**Comment by HanFox** [comment]
Nevermind I think I'll work on a custom template that doesn't use bootstrap.
