### ISSUE TITLE
[Solved] Time to load so long as logged user on intranet without Internet

### ISSUE THREAD

**Issue by rafamerino** [LotarProject/dokuwiki-template-bootstrap3#228]
Hi! All in my work love your theme instead of previous (sidebar theme), we use Dokuwiki for guides and handbooks for hundreds of workers.

The problem is, when I'm logged, time to load pages takes too much time, making annoying to edit anything.

Here you can see, as guest, time to load is barely 1,5 secs:
![session_guest](https://cloud.githubusercontent.com/assets/371826/16704165/54f3896e-4574-11e6-8e88-bbb0e3c22f46.png)

But as logged user, time to load any page increases at least to 15 seconds!
![session_admin](https://cloud.githubusercontent.com/assets/371826/16704171/66960890-4574-11e6-9d4d-1281118380ce.png)

This intranet doesn't have Internet connection, so I've checked for external resources (such google fonts) to avoid any timeouts, but except some lines removed in font-awesome(.min).css, I'm not capable to locate what's causing this issue.
 
FYI, I have the full TimelineData from Chrome in both scenarios, but I don't know if are really useful to you (as logged user, log size is 29Mb and as guest user, log is 7,5Mb). I can upload the files if you wish.

Thank you!

**Comment by LotarProject** [comment]
Thank you for your analysis. My next step is include all WebFonts of all Bootswatch themes in asset directory.
Stay tuned :)

**Comment by LotarProject** [comment]
Hi! I have created a new branch  (**feature/google-fonts**) to test this new feature.

**Comment by rafamerino** [comment]
I'll try asap to give you feedback. Thank you!

**Comment by rafamerino** [comment]
Hi Giuseppe.

Now as a logged user, time to load has improved hugely. Barely takes 4,5 secs.

Problem now is, as guest user, time to load is nearly the same, while with previous version, it was about 1,5 secs. I need to investigate more this issue (I've changed nothing more) to give you full detailded feeback, but for now, the guest time load degradation is not worth it (we're talking about thousands of pageviews/day).

Regards!

**Comment by LotarProject** [comment]
Hi! Thanks for your feedback.

  * The guest users (generally) which browser and version have ?
  * You have "useGravatar" option set to on ?
  * Can you send me (in private) the network tab screenshot of Developer Tools ?

Have a nice day.
Joseph

**Comment by rafamerino** [comment]
So sorry, I forgot to add more feedback :(
After some DW reinstall, with your suggested new theme, loading time is perfect.

Thank you so much for your work. Kudos!

**Comment by LotarProject** [comment]
Thanks for your feedback!
