### ISSUE TITLE
Sidebar width

### ISSUE THREAD

**Issue by taizoli** [LotarProject/dokuwiki-template-bootstrap3#229]
Hello,

first of all thank you for the new bootstrap3 release. I wanted to ask, why is the config option "left(right)SidebarGrid" misssing in this new release?

For me it is necessary to use this option to change the sidebar width, so please if it is possible put it back.

Thank you

best regards
Zoltan

**Comment by LotarProject** [comment]
Hi @taizoli , i have reverted this feature in develop and master branch.
Can you reinstall the template.

Sorry :P

At your disposal,
Joseph
