### ISSUE TITLE
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher

### ISSUE THREAD

**Issue by iheinrich** [LotarProject/dokuwiki-template-bootstrap3#23]
Installed Bootstrap 3 template via download in DokuWiki extension manager. Activated template=bootstrap3 in configuration manager.
Result: I can not edit pages. "Tools" menu can not be opened.
Re-installed Bootstrap 3 via direct download and unzip in tpl folder.
Same result.

DokuWiki VERSION file says: 2014-09-29d "Hrun"
Firefox developer console: Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher
Installed on Debian unstable (sid), package dokuwiki_0.0.20140929.d-1_all.deb.

What can I do? (I figure I need jQuery 1.9.1+... But: is there a way to add jQuery 1.9.1+ to DokuWiki?)

**Comment by LotarProject** [comment]
Hi. This version of Dokuwiki (2014-09-29d "Hrun") uses jQuery 1.11.1.

To show the current version of jQuery from Firebug console:
```javascript
  jQuery.fn.jquery
```

Best regards,
Joseph
