### ISSUE TITLE
Bootstrap3 templates switcher by namespace

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#230]
Hello,

It could be great to choose by namespace among all templates provided by Bootstrap3. I am testing the Loadskin plugin. Except I have an token error "Possible CSRF attack", it seems that  I have to choose between Dokuwiki and Bootstrap3. It is probably possible to copy Boostrap3 and give to it an other name but ....   Perhaps, some experience is over here with this topic ?
As Boostrap3 has already a theme switcher in settings admin, I wonder if it will be possible to give this option to choose by namespace as well, really useful and fun to give some specific skin to namespace :sunglasses: (just to go as far as possible with all hooks available that provides nice possibilities, I mean before becoming a wiki farmer).

**Comment by LotarProject** [comment]
Very interesting feature!

**Comment by Digitalin** [comment]
Hi,
Great to hear that you add it as a feature :+1: 

I am testing Bootstrap3 template in a wiki farm. Choosing a theme works well, having a navbar by namespace too. Seems nice at this time.  But, it is an other purpose.

**Comment by LotarProject** [comment]
Hi! I have added initial support in **feature/template-by-namespace** branch.

To enable this feature create ``bootstrap3.themes.conf`` in ``DOKU_CONF``:

````
:wiki  default
:playground  bootswatch/yeti
````

See live action in my website:
  * https://lotar.altervista.org/dokuwiki and other pages (Bootswatch Yeti theme)
  * https://lotar.altervista.org/dokuwiki/wiki (default Bootstrap theme -- is useful to display Bootstrap Wrapper samples with original Bootstrap theme)

My next steps:
  * Create a configuration to enable/disable this feature
  * Fix regex
  * Testing

At your disposal,
Joseph

**Comment by Digitalin** [comment]
Hi Joseph, 

After different tries, it seems that is better to just put in the bootstrap3.themes.conf
`:foo bootswatch/whateverTheme`
where :foo wants to have another theme. It works better for me without saying where default theme is used as :
`ns:page: default`

Just brilliant :-)
Thanks.

**Comment by LotarProject** [comment]
Integration with Advanced Plugin Config (LotarProject/dokuwiki-plugin-advanced#6)

**Comment by KyleWayneLaCroix** [comment]
I can't seem to get this to work. The advanced plugin config doesn't seem to recognize the  conf file either. I'm putting the conf. file in the conf folder. Is there something obvious I could be missing?
