### ISSUE TITLE
Option to start with TOC collasped

### ISSUE THREAD

**Issue by tysoncecka** [LotarProject/dokuwiki-template-bootstrap3#231]
Hello,

I still have some spacing issues when the TOC is opened on the Lumen theme (it moves all content over to the left while it exists in it's own column inside the body of the page).

This isn't ideal behavior (would like it outside of the body content to the far right). But would be fine if we could get an option that have the TOC start collapsed. 

http://wiki.parkourvisions.org/teach/pkv-certification-syllabus

Thanks for considering!

**Comment by aterratos** [comment]
Hi, I use the same theme and have the same problem.
Also, when I use the inlinetoc plugin, both tocs appear. Is this intended. Can I disable the normal toc without disabling the inlinetoc?

Thanks!

**Comment by LotarProject** [comment]
@aterratos the inlinetoc issue is fixed in dev branch with this commit d2af927
