### ISSUE TITLE
Sidebar not shows up

### ISSUE THREAD

**Issue by AlekSet** [LotarProject/dokuwiki-template-bootstrap3#232]
Hi.
After upgrade DokuWiki and Bootstrap template sidebar at right side not shows up.
Setting: sidebarPosition: right
New setting useACL: on/off - no matter, not works
At left side sidebar is ok.

![kody magazynek org_game-wallpapers_start-6_-_20160715-121520](https://cloud.githubusercontent.com/assets/16212999/16871278/5215bd4a-4a86-11e6-9717-65e10a5d7e6f.png)

![kody magazynek org_game-wallpapers_start-6_purge true_-_20160715-122351](https://cloud.githubusercontent.com/assets/16212999/16871413/0d77f0ee-4a87-11e6-99f7-cac72336080a.png)

Please help

**Comment by LotarProject** [comment]
Hi @AlekSet, i have fixed this issue in develop and master branch!

At your disposal,
Joseph

**Comment by AlekSet** [comment]
TY. Now works good.
