### ISSUE TITLE
topbar

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#234]
Hi,

Following a part of the thread #91, I open a new one about topbar. 
Since this topic, a lot have changed and [procedure](https://www.dokuwiki.org/tips:topbar) could have changed too. I try adding a topbar. 

What I have done : 
- create a data/pages/topbar.txt with some links as bulleted list (like navbar, sidebar...) with ACL read to ALL
- create a /lib/tpl/bootstrap3/footer.html with 
  `<div class="topbar">
  <?php tpl_include_page('topbar') /* includes the wiki page "topbar" */ ?>
  </div>`
- then add a /conf/userall.css with css text as explained (in dokuwiki/conf not in bootstrap3/conf )

Nothing is displaying. Only, the usually hidden breadcrumb  comes off.  I tested on two local wiki, because one use the footer DokuWiki hook  for some namespaces, so in case, I tried on the other. But same result. 
Have you an idea ? 

Thanks.

**Comment by LotarProject** [comment]
Hi,
if you set ``fixedTopNavbar``option to on, the topbar is below the Bootstrap navbar. I have added in ``.topbar`` class this line:

```.css
.topbar {
  z-index: 9999;
}
```

... but the topbar is above the Bootstrap navbar (because the navbar have the fixed position).

If you set ``fixedTopNavbar`` to off, display the topbar.

At your disposal,
Joseph

**Comment by lrdt** [comment]
Hy

The topbar is planed to be integrated to the features of bootstrap3? I'm scared about managing code by my own...
Thank you

**Comment by Digitalin** [comment]
Hi Joseph, 

It was this :-) 
I am not sure to use it but works fine. 
Thanks.

**Comment by LotarProject** [comment]
:)

I think its possible to create a new hook caller ``:topbar`` using DokuWiki list syntax (like ``:navbar``) and/or ``navbar.html`` to edit directly in HTML.

**Comment by Digitalin** [comment]
For sure. Dokuwiki hooks in Bootstrap3 template are awesome and navbar.html is almost deprecated :smile: 

In fact, it works but changes the width of all page included navbar and let a big space between navbar and topbar. I am not good enough with CSS to fix it for now but as I don't need, I am not in a hurry... more on Linux, networking, wiki farms and db with struct and Sqlite problems at present time. 

I wonder what you plan to make easier to change template. lrdt is asking on this issue,  [issue 238](#238) talks about integration with styling plugin for managing colors. I know you are really reactive and listening to wishes and issues and I imagine there is different possible paths. A good step forward was made with [advanced plugin](https://www.dokuwiki.org/plugin:advanced), it is already "easier" to change config files from DokuWiki with some CSS skills.  Perhaps, the plugin could push CSS used file config to serve as skeleton ( as it does for some others config files ) and not just displays made changes, if I am not wrong. Having the three files (default, complete and only diff as made changes) would be great . 

With Template [switcher by namespace](#230), perhaps in a next release :sunglasses: , it is going to become more complex. I remember you were on integration with LESS.
It is just to have  your feeling and some prospective ways you imagine to deal with this topic.

**Comment by LotarProject** [comment]
Created ``:topheader`` hook in upcoming template version.
