### ISSUE TITLE
conflicts with Navigation Plugin (Andreas Gohr)

### ISSUE THREAD

**Issue by NikolausMB** [LotarProject/dokuwiki-template-bootstrap3#235]
The navi-plugin allows you to create a nested navigation menu. Lower navigation levels are shown or hidden dependent on the current page.
Using bootstrap3-template, an entry with hidden sub-entries has incorrect font-attributes.

Example: Entry "Tipps" has two sub-entries and is "closed"
![nav](https://cloud.githubusercontent.com/assets/1101285/17184788/5d21a58a-542e-11e6-83ed-d2cd17a1ca2a.GIF)

-> incompatible definition of style ".close"

**Comment by colorprint** [comment]
I have the same issue

**Comment by NikolausMB** [comment]
a workaround:
in many cases, you can use  instead the "nav"-component of the "bootstrap wrapper"-Plug-in.
 ```
 ~~NOCACHE~~
  <nav type="pills" stacked="true"> ... </nav>
```
Mayby Lotar is too modest to mention it  ;-)
