### ISSUE TITLE
Acronyms are printed with braces

### ISSUE THREAD

**Issue by mihula** [LotarProject/dokuwiki-template-bootstrap3#236]
When page text contains acronym, eg. GUI, template adds braces in print preview of such page.

Example:
`Acronyms -- like GUI -- are printed with braces. :-(`

Wiki view:
![acronyms_wiki_view](https://cloud.githubusercontent.com/assets/1676074/17243498/77caa51c-557d-11e6-9624-e9a1dfb1a186.png)

Print view:
![acronyms_print_view](https://cloud.githubusercontent.com/assets/1676074/17243497/77c35c8a-557d-11e6-99d3-fde2dd0af9e2.png)

Standard template
![acronyms_print_view_standard_template](https://cloud.githubusercontent.com/assets/1676074/17243600/f01f2cf4-557d-11e6-812b-f48817b6a001.png)

Using
dokuwiki 2016-06-26a "Elenor of Tsort"
bootstrap3 template [v2016-07-05]

**Comment by LotarProject** [comment]
Thanks for reporting this issue. I have restored the default Bootstrap theme behavior.

Best regards,
Joseph
