### ISSUE TITLE
Fatal error during compilation of CSS file

### ISSUE THREAD

**Issue by ysalmon** [LotarProject/dokuwiki-template-bootstrap3#237]
### Description

Today, I upgraded my bootstrap3 Dokuwiki (Detritus) plugin using Dokuwiki's standard plugin upgrade interface and the compilation of ```lib/tpl/bootstrap3/css/plugins/overlay.less``` fails.
After inspecting the file, it appears that
```less
@media print {
  #overlay: display: none;
}
```
is not valid. I replaced it with
```less
@media print {
  #overlay: {display: none;}
}
```
which is now accepted by http://less2css.org/.

But how can I run the compilation again ? If I try to reinstall the plugin, my corrected file is replaced by the faulty one.

**Comment by ysalmon** [comment]
Hum, switch to Dokuwiki default theme then back to bootstrap3 seems to cause a recompilation ; I do not see error messages now.

Leaving this open to know if the initial problem is really a bug in the plugin or on my side.

**Comment by LotarProject** [comment]
Hi, Sorry, it's my mistake!
Fixed in develop and master branch.

At your disposal,
Joseph
