### ISSUE TITLE
Feature request: Support for Table Width Plugin

### ISSUE THREAD

**Issue by Lethert** [LotarProject/dokuwiki-template-bootstrap3#239]
when i use this Plugin, Tables not format correct.

**Comment by lukderp** [comment]
I had some trouble getting it to work aswell, but I managed to figure out a solution.

* Create your table and save it.

* Go back into the editor and add the | <100% 25% 25% 25% 25%> |  above the table.

* Does it work now?

**Comment by Lethert** [comment]
The width did work.
What not work correct is the style of the table.
When I add a line like | <100% 25% 25% 25% 25%> |  above the table, then it changes the style of the display. 
Without it displays with lines and border.
With this line above the table displays without lines and borders.

**Comment by lukderp** [comment]
Could you provide a screenshot so I can understand your problem a bit better?

Just use dummy Tables so you dont have to black out stuff.

**Comment by Lethert** [comment]
look here: [Testsite](http://85.214.37.232/LCS/DOKUWIKI/doku.php/test)

This site you can edit.

**Comment by lukderp** [comment]
Probably another plugin is causing this. It works fine for me.

**Comment by Lethert** [comment]
i dactivate all other plugins, but the second table on the test side did not display correct.
There are no horizonal vertical border lines in this table!

**Comment by Lethert** [comment]
i attempt to anylyse the generated html:

1. Table: <table class="inline table table-striped table-bordered table-hover table-condensed">
2. Table: <table class="inline" style="width: 100%;">

with the dokuwiki original-template all works fine, 
I have the problem only with the bootstrap template.

**Comment by lukderp** [comment]
I just realized that the border lines are not displayed for me as well.

I guess the problem lies within bootstrap3, but I don't know where the problem is coming from exactly.

**Comment by LotarProject** [comment]
Hi! I have tested in your test site and in my dev enviroment and works fine but the borders is not visible .... but have discovered the problem in plugin code.

The problem is a new attribute pushed in ``<table>`` tag. I can prepare a patch to solve this issue.

Best regards,
Joseph

**Comment by Lethert** [comment]
Tested with many tables.
Works fine!

Thanks for this quick solution.

**Comment by lukderp** [comment]
Thanks @LotarProject for the quick fix!
