### ISSUE TITLE
Stretched images in main pages

### ISSUE THREAD

**Issue by comclusive** [LotarProject/dokuwiki-template-bootstrap3#24]
With Bootstrap3 theme enabled, images/tables created using pluguns "diagram" or "rack elevation" get stretched to the full width of the page. You can see it draw the correct width and then redraw full-width.

**Comment by LotarProject** [comment]
Hi. With Bootstrap the tables is on full width of the page. I have fixed the problem in my last commit.

Best regards,
Joseph

**Comment by comclusive** [comment]
Thanks for the quick fix, everything displays perfectly now.
