### ISSUE TITLE
Can't find the file which adds 70px padding-top as seen in picture

### ISSUE THREAD

**Issue by lukderp** [LotarProject/dokuwiki-template-bootstrap3#240]
### Description

Can someone tell me where I can change the 70px to something less ? I can't for my life find the correct file to change the padding-top...

### Screenshots or Logs

![padding70](https://cloud.githubusercontent.com/assets/18195444/17517903/d998ac50-5e45-11e6-9ae1-987840473396.png)

The green area glows when using google inspect element.

**Comment by lukderp** [comment]
Alright I found it, it's in tpl_functions.php :)

**Comment by LotarProject** [comment]
Hi, is into ``tpl_function.php`` because every theme have different values for navbar height.
