### ISSUE TITLE
Navbar dropdown menu not working

### ISSUE THREAD

**Issue by s0n-** [LotarProject/dokuwiki-template-bootstrap3#241]
### Description

Navbar dropdown menu not working, no menu objects
### Steps to Reproduce

Clean Install, any Theme with any combination of configurations in bootstrap.

**Expected behavior:** [What you expected to happen]
Dropdown menu options

**Actual behavior:** [What actually happened]
Nothing - clicking will refresh the page
### Versions

7-5-2016
2014-05-05a "Ponder Stibbons"
Chrome && Safari
### Screenshots or Logs

Chrome Errors

bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
home?do=admin&page=config:29 Uncaught TypeError: jQuery(...).scrollspy is not a function

**Comment by LotarProject** [comment]
Hi, i have replicated your issue in my develop enviroment with the same DokuWiki and Template version but i don't have the same result.

Can you purge js cache (via ``http://<dokuwiki>/lib/exe/js.php?purge=true`` url) and clean your Browser cache ?

At your disposal,
Joseph

**Comment by s0n-** [comment]
Purged Cache but only came back with a bunch of json(?). Cleaned browser cache and still the same effect.

**Comment by s0n-** [comment]
in a last ditch effort I took a different bootstrap.min.js and replaced the version included and everything is working.

**Comment by LotarProject** [comment]
What is the version of new ``bootstrap.min.js`` file ?

**Comment by leveled** [comment]
@s0n- How exactly did you this? I'm running into the same problem and replacing the js file did not fix the problem for me.

**Comment by s0n-** [comment]
Its been two weeks so I beleive i pulled the min.js from another plugin but taking a quick look this is what version it says. 

Bootstrap v3.0.2 by @fat and @mob

**Comment by leveled** [comment]
I can confirm that this fix worked for me as well.

**Comment by paulnus** [comment]
![image](https://cloud.githubusercontent.com/assets/239261/18889036/b9631be0-84c0-11e6-8730-32c0ea464a10.png)

Is it normal for the jQuery items to be pulling from maxcdn.bootstrapcdn.com ? 

I tried going back to v3.0.2 of bootstrap.min.js to no avail.

**Comment by LotarProject** [comment]
Is unsafe change the asset files in ``tpl/bootstrap3/asset`` directory because this files change when a new release of Bootstrap3 is issued.

**Comment by kmlucy** [comment]
I am also having this issue. Is there any fix?

**Comment by colorprint** [comment]
I have the same issue with fresh installation

**Comment by brodywJoesSporting** [comment]
I'm having the same issue, tried some of the config and cache purging options offered on this and similar bugs and still does nothing.

**Comment by slymedia** [comment]
I just did an update and now this happened to me as well on a clients site. This same thing happened a while back.. so for a week or so I had to run one of the default theme's. Then I think you fixed this and an update came out. When I applied that update it started working again. Is there a way to fix this? Thanks!

**Comment by Coenny** [comment]
I am having a similar issue. 
I have cleared my caches and tried reinstalling the template. 

I get the following errors:
- Uncaught ReferenceError: Invalid left-hand side expression in postfix operation 
- Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
- Uncaught ReferenceError: jQuery is not defined
    at doku.php:36

Any ideas?

**Comment by waldauf** [comment]
### Description

I tried to use drop-down menu in navbar. But when I tried to use simple tree structure navbar was broken.

### Steps to Reproduce

1. Edit navbar and save:
```
  * [[projekty|Projekty]]
    * [[hr|HR]]
  * [[hr|HR]]
```
2. navbar is broken and work just first level links. Drop-down menu doesn't react on mouse.

![image](https://user-images.githubusercontent.com/24603883/31298610-3d76acb6-aaeb-11e7-9ecd-ecb8ab1d7039.png)


### Versions

  * [Bootstrap3 Template] - Last updated on 2016-12-12
  * [DokuWiki] - Release 2017-02-19e "Frusterick Manners"
  * [Browser] - Chromium Version 61.0.3163.91
  * [JQuery] - 
```
# cat /var/www/lib/scripts/jquery/versions
# this is loaded from the update.sh script and our PHP code
JQ_VERSION=3.1.1
JQUI_VERSION=1.12.1
JQM_VERSION=3.0.0
```
I tried to download new JQuery packages but without success.

**Comment by waldauf** [comment]
Hello,
can I aks you if there is some way how to work drop-down menu?

Thx for answer in advance. :]

**Comment by vidschofelix** [comment]
I think was able to solve this by touching the bootstrap.min.css in every style folder

**Comment by LotarProject** [comment]
See #291
