### ISSUE TITLE
Not compatible with dir or pagelist plugins

### ISSUE THREAD

**Issue by huksley** [LotarProject/dokuwiki-template-bootstrap3#242]
### Description

There is issues in displaying `~~DIR~~` or pagelist command.
It caused by `~~DIR~~` rendering first row in table with `class="row"` which is obviously used by Bootstrap CSS itself.

### Versions

  * Theme - Latest Release from update manager
  * DokuWiki - Release 2016-06-26a "Elenor of Tsort"

**Comment by huksley** [comment]
Fixed by following CSS
```
table.pagelist tbody tr.row::before {
    display: none;
}
```

**Comment by LotarProject** [comment]
Thank you for the patch! Added in dev branch.

Joseph
