### ISSUE TITLE
Want toc position in overlay(plugin).

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#244]
### Description

Original toc is located in write side of screen.
But I want to move toc position, write side to overlay(plugin).
### Steps to Reproduce
1. Using 'inlinetoc' plugin, toc will locate in sidebar.
2. So, I want to move toc position in overlay(plugin).
3. But, Using 'inlinetoc' plugin, when I click overlay plugin button, the sidepage shown empty page.

My homepage URL is http://www.animint.net/
Please, click 'overlay' button in icon package of right side.
### Versions
- [Bootstrap3 Template] - latest version
- [DokuWiki] - latest version
- [Plugin] - overlay, inlinetoc
- [Browser] - chrome latest version
### Screenshots or Logs

![overlay-inline](https://cloud.githubusercontent.com/assets/7350716/17835342/feb946d6-67a3-11e6-9791-55b40a9c9bfb.jpg)
### Sample Page

http://www.animint.net/

**Comment by LotarProject** [comment]
Hi! I think Overlay and InlineTOC not have this feature, but with little bit of JS ....

Cloning DokuWiki TOC into Overlay:
```.js
var toc = jQuery('#dokuwiki__toc').clone();
toc.appendTo('#overlay');
```

or  move InlineTOC into Overlay:
```.js
 jQuery('.inlinetoc2').appendTo('#overlay');
```

At your disposal,
Joseph

**Comment by lattekun** [comment]
Thanks to your advice, but it isn't work I tried.
I tried that insert code one of each method  insert in 'overlay.js'.
Would you mind explain to me how to insert that method step-by-step?

**Comment by lattekun** [comment]
My result, in start page, toc was shown 'config page''s toc in overlay page.

**Comment by lattekun** [comment]
I tested
   jQuery('div.inlinetoc2');
to
  jQuery('.inlinetoc2').appendTo('#overlay');
But, it isn`t work, and result is like this...
![method 2](https://cloud.githubusercontent.com/assets/7350716/17893723/b4c8dc8c-6981-11e6-8983-8dad33501554.jpg)

**Comment by lattekun** [comment]
I hope...
toc move to overlay, and toc display none in content area.
In mobile or tablet, I think, using 'sectiontoggle' plugin to useful.

**Comment by SergTT** [comment]
@lattekun, @LotarProject, could you please write step-by-step algorithm of including {{inlinetoc}} into the template?
I was able to place TOC in one page, but I can't include the TOC into whole template. Is it possible?

**Comment by lattekun** [comment]
@SergTT 
Before to write, my English is very bad.
In my experience, Write {{inlinetoc}} in sidebar page, and delete all cache file.
That 's all.

@LotarProject 
Please, read my question and help me! ^^;;
  I hope...
  toc move to overlay, and toc display none in content area.
  In mobile or tablet, I think, using 'sectiontoggle' plugin to useful.
