### ISSUE TITLE
Table scrollbar unreponsive

### ISSUE THREAD

**Issue by luthiens** [LotarProject/dokuwiki-template-bootstrap3#245]
### Description

Hello, I changed the template of my wiki page to Bootstrap3 and I noticed that the horizontal scrollbar below the table (see: screenshots) is not working properly. In fact it only works when I click and hold the mouse button on the bottom edge of the scrollbar. 

**Expected behavior:** 

I expect the scroll bar to work after clicking and holding at the whole area of the scroll bar.
### Versions
- [Bootstrap3 Template] latest version
- [DokuWiki] latest version
- [Browser] Google Chrome
### Screenshots or Logs

![bez tytulu](https://cloud.githubusercontent.com/assets/17991522/17962200/05b47136-6ab0-11e6-9b09-7fa48b9f2842.png)

To scroll the table,  You have to "catch" for example the place shown by the red pointer otherwise it is not working.

**Comment by LotarProject** [comment]
Hi,
can you send a snippet of your table in DokuWiki format?

Thanks,
Joseph
