### ISSUE TITLE
403 Forbidden error ?

### ISSUE THREAD

**Issue by WinEcos** [LotarProject/dokuwiki-template-bootstrap3#247]
### Description

open home page and get  more 403 forbidden error  via http://docs.winecos.com 
### Steps to Reproduce

open website and F12 developer tools analysis

http://docs.winecos.com/bugs/sp160831_171819.png 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
### Versions
- [Bootstrap3 Template]

**Comment by LotarProject** [comment]
Hi @WinEcos ,
generally the HTTP ``403 Forbidden`` is returned for every inaccessible pages or media.

At your disposal,
Joseph
