### ISSUE TITLE
Display TOC outside of content

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#249]
### Description

Expanding/Collapsing the TOC causes the contents to shift (unless collapsed by tocCollapseOnScroll). Before 56fd239 this only occurred at the top of the page (which was also a peeve of mine :p). Would it be possible to relocate the TOC outside of the content again?

**Requested behavior:** TOC appears outside content. Position is kept when expanded.

**Actual behavior:** TOC inside content. Page contents adjust to fit expanded TOC.
### Versions
- [Bootstrap3 Template] develop
- [DokuWiki] 2016-06-26a
- [Browser] Firefox 48.0.2
### Screenshots
- Before https://ptpb.pw/5frx.png
- Current https://ptpb.pw/VLIy.png

**Comment by polyzen** [comment]
Thank you for tackling this :). It couldn't be done with the Bootstrap-style TOC, huh? That's a shame.

I don't know how you feel about this, but if it's possible to have the TOC "hover" even at the top, it can keep something like [this](https://ptpb.pw/K78U.png) from happening.

**Comment by LotarProject** [comment]
Hi! Yes is a shame :(
The Bootstrap style not have a border around the TOC and during the scroll the TOC is above the text content like ...

![spectacle qq9827](https://cloud.githubusercontent.com/assets/1824717/19433865/ccefc210-9462-11e6-9ce2-78a89a9ebb15.png)

**Comment by polyzen** [comment]
Ah, I see.. Asked in their IRC channel if it's possible to add a border, but no response yet.
