### ISSUE TITLE
Integration of the translation plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#25]
Hi,

excellent template with a good design and a lot of customizing possibilities.

But one thing I want to describe: When turning on the option "showTranslation", the content area of the page is highly reduced because subsequently a whole line of the window is reserved only for these translation buttons (class clearfix). In my opinion it would be better if these buttons were integrated into the navbar, perhaps on the right side or into the class "pageId text-right"

Regards
Jürgen

**Comment by LotarProject** [comment]
Hi. Thanks for using my template.

Your suggestion is a good idea!
I have created a simple code with Translation Plugin API and this is the result:

![bootstrap3-template-plugin-translation](https://cloud.githubusercontent.com/assets/1824717/7591560/de62a26e-f8ce-11e4-9b8a-5930b0480359.png)

Best regards,
Joseph

**Comment by LotarProject** [comment]
I have pushed the code in the last commit (35be820aaf)
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much.

I've tested it, and it looks very good. Precondition is that in the customizing of the translation plugin the option "dropdown" is deactivated. Another thing is that one cannot recognize if a page in a special language is existing. When using the original dokuwiki template these language codes are grayed out in the drop down list.

Regards Juergen

**Comment by LotarProject** [comment]
Hi :)
At this moment, the non-existent translated page is displayed with dashed border around the language (see my picture above) but is not easy to understand (specially for the white themes).

The my solution is to remove the dashed border and add the opacity:

![image](https://cloud.githubusercontent.com/assets/1824717/7608364/1022ddba-f969-11e4-859f-efcac1d81578.png)

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you, that is the solution.

Best regards 
Juergen
