### ISSUE TITLE
Error: "Warning: Cannot modify header information - headers already sent..."

### ISSUE THREAD

**Issue by bobdeh** [LotarProject/dokuwiki-template-bootstrap3#250]
### Description

Error
`Warning: Cannot modify header information - headers already sent by (output started at C:\xampp5_6\htdocs\dokuwiki\inc\template.php:1821) in C:\xampp5_6\htdocs\dokuwiki\inc\common.php on line 1992` 
triggered by setcookie after changing theme. My research says this is caused because php creates output before the header is modified. Because of this it was also tested on fresh DokuWiki installations with XAMPP and the DokuWikiStick version from dokuwiki.org and without any other plugins.
### Steps to Reproduce
1. enable tpl»bootstrap3»showThemeSwitcher in settings
2. change the theme

**Expected behavior:** Theme should change without error.

**Actual behavior:** Theme changes but i get this error message:

`Warning: Cannot modify header information - headers already sent by (output started at C:\xampp5_6\htdocs\dokuwiki\inc\template.php:1821) in C:\xampp5_6\htdocs\dokuwiki\inc\common.php on line 1992`
This message is from my local test installation without any other plugins and with a fresh installation. It was used because i get the same message on my web server.
### Versions
- [Bootstrap3 Template] 2016-07-05
- [DokuWiki] 2016-06-26a "Elenor of Tsort"
- [Browser] Chrome 51.0.2404.103m (also tested with IE and Firefox)

**Comment by bobdeh** [comment]
Hello, 
I just would like to know if i missed some information in my report or if someone can reproduce it.

Regards, Bob

**Comment by LotarProject** [comment]
Sorry @bobdeh,
i have fixed in my local branch but i don't have pushed on GitHub!

Sorry :P

At your disposal,
Joseph

**Comment by bobdeh** [comment]
Thank you very much. I can confirm that i works now like intended.
Letting the user choose between darkly and flatly seems like a big benefit to me!
Keep up the good work!

Regards, Bob

**Comment by aubreyz** [comment]
I am seeing this error again in the latest Bootstrap3 downloaded today. Cannot change themes at all.
