### ISSUE TITLE
Tablelayout plugin not taken into account

### ISSUE THREAD

**Issue by vincowl** [LotarProject/dokuwiki-template-bootstrap3#254]
### Description

It seems that tablelayout plugin's syntax is not taken into account. Tables remains left aligned, with pre-calculated width columns. 
### Steps to Reproduce
1. Create a page with the following code, using tablelayout plugin
   {{tablelayout?colwidth="20px,30px"&rowsFixed=1&rowsVisible=2&float=right}}
   ^ header 1 ^ header 2 ^
   | cell A1 | cell B1 |
   | cell A2 | cell B2 |
   | cell A3 | cell B3 |

**Expected behavior:** 
The previous example syntax will make the first fixed and show about 1 other row in a scrollable container below. It will make the first column 20px wide and the second 30px. The table itself will be floating to the right.

**Actual behavior:** 
The table is still left aligned. Columns still have a bootstrap3 pre-calculated width
### Versions
- Bootstrap3 Template : 2016-07-05
- DokuWiki : 2016-06-26 "Elenor Of Tsort" 
- Plugin : TableLayout (2016-10-07)
- Browser : Safari Version 10.0 (12602.1.50.0.10)

**Comment by LotarProject** [comment]
Fixed in upcoming release of template.

**Comment by mbromley-voxel** [comment]
I've just installed the update from 2017-12-07 and am having this same issue.  I've copied an pasted the same syntax with no effect on the table produced.

**Comment by vincowl** [comment]
I confirm the @mbromley-voxel's issue : same pb here

**Comment by Chris75forumname** [comment]
https://forum.dokuwiki.org/d/22325-template-bootstrap3-mit-tablelayout-plugin
