### ISSUE TITLE
Wrap plugin not applied to tables alignment

### ISSUE THREAD

**Issue by vincowl** [LotarProject/dokuwiki-template-bootstrap3#255]
### Description

It seems that wrap plugin's syntax is not taken into account. Tables remains left aligned when wrap syntax specifies center alignment.
### Steps to Reproduce
1. Create a page with the following code, using tablelayout plugin
   <WRAP center 80%>

^ header 1 ^ header 2 ^
| cell A1 | cell B1 |
| cell A2 | cell B2 |
| cell A3 | cell B3 |

</WRAP>

**Expected behavior:** 
The previous example syntax will make the table itself to be centered aligned

**Actual behavior:** 
The table is still left aligned. 
### Versions
- Bootstrap3 Template : 2016-07-05
- DokuWiki : 2016-06-26 "Elenor Of Tsort" 
- Plugin : Wrap (2015-07-19)
- Browser : Safari Version 10.0 (12602.1.50.0.10)

**Comment by LotarProject** [comment]
Hi @vincowl,
Wrap plugin work fine with the simple table in your snippet code but not with Table Layout Plugin.

Depend #254

**Comment by vincowl** [comment]
The same problem is back. The simple table in the snippet code is not centered. tablelayout plugin is not installed
Using 
DokuWiki : 2017-02-19b "Frusterick Manners"
Bootstrap3 Template : 2016-12-12
Wrap : 2015-07-19
