### ISSUE TITLE
Button malfunction for admin, profile, logoff

### ISSUE THREAD

**Issue by ahoehe** [LotarProject/dokuwiki-template-bootstrap3#257]
### Description

After activating "Bootstrap3 Template" the buttons on the top right corner do not function correctly as they do in "dokuwiki-template". E.g. "admin" should open "http://servername/dokuwiki/doku.php?id=start&do=admin" but points to current page (meaning: nothing happens).
### Steps to Reproduce
1. normal Dokuwiki running, no template activated but default "dokuwiki-template". Buttons work okay.
2. activating "bootstrap3"-template. Buttons don't work (have to give URL to adminpage manually in order to swich back)
3. switching back to default, buttons work correctly.
### Versions

(all latest versions)
- [Bootstrap3 Template]: 2016-07-05
- [DokuWiki] Elenor Of Tsort (2016-06-26)
- [Plugin] "Bootstrap Wrapper Plugin" (2016-04-14)
- [Browser] Firefox 48.0.2, IE11 ,  WIN10pro
### Screenshots or Logs

![bootstrap3-adminbutton-malfunction](https://cloud.githubusercontent.com/assets/21197602/19561774/3a87529c-96da-11e6-9669-e789d1aa768f.png)

**Comment by LotarProject** [comment]
Hi @ahoehe,
can you send a screenshot of javascript console ?

At your disposal,
Joseph

**Comment by Nata16** [comment]
Hi, I have the same problem. Here are the screenshots that you asked
![2016-12-01_14-09-58](https://cloud.githubusercontent.com/assets/24293275/20791851/0d77399a-b7d0-11e6-9f20-8680e65dc8f4.png)

**Comment by LotarProject** [comment]
Hi @Nata16, thanks for screenshot. Can you type this string in JS Console for display your jQuery version ?

```jQuery.fn.jquery```

**Comment by Nata16** [comment]
We use jQuery from the Debian repository jessie version 1.7.2

**Comment by LotarProject** [comment]
Bootstrap require jQuery 1.9.1. The last release of DokuWiki uses jQuery v2.2.4

**Comment by kmlucy** [comment]
I'm seeing a similar issue. Here is my console upon loading the page:

![image](https://cloud.githubusercontent.com/assets/13952475/20952776/ce5e55aa-bbfc-11e6-86bc-27fd2a10b0e4.png)

**Comment by LotarProject** [comment]
Hi @kmlucy, this is a different error. Can you disable JS & CSS compression via ``compress`` option and send me a screenshot with the error and source code around the error line ?

Thanks!

At your disposal,
Joseph

**Comment by kmlucy** [comment]
Joseph,

I don't have a lot of experience with JS and CSS, so just let me know if this isn't what you needed. Also, those errors pop up as soon as I load the wiki, not just when I try to click the navigation buttons.

![5](https://cloud.githubusercontent.com/assets/13952475/21087730/9568bfa8-bff6-11e6-8c16-90b19e04cd29.JPG)
![1](https://cloud.githubusercontent.com/assets/13952475/21087727/9567f7b2-bff6-11e6-96a1-6086a6b70b52.JPG)
![2](https://cloud.githubusercontent.com/assets/13952475/21087729/95688678-bff6-11e6-866a-ee4ac1ee2772.JPG)
![3](https://cloud.githubusercontent.com/assets/13952475/21087728/9568388a-bff6-11e6-80d2-9f438482daf7.JPG)
![4](https://cloud.githubusercontent.com/assets/13952475/21087731/9568e596-bff6-11e6-8866-99c081ec1714.JPG)


Thanks,
Kyle

**Comment by LotarProject** [comment]
Thanks @kmlucy for your feedback!

Your DokuWiki installation is published on internet ?

Can you purge Browser and DokuWiki cache (via ``http://example.org/dokuwiki/lib/exe/js.php?purge=true`` url) ?

Have a nice day,
Joseph

**Comment by kmlucy** [comment]
I tried purging the cache, and was presented with a page of source code. Afterwards, the buttons still do not function, and I still have the same errors.

Thanks,
Kyle

**Comment by LotarProject** [comment]
Hi @kmlucy, the code on your screenshot seems jQuery-UI. I think you have a corrupted jQuery-UI library.

Joseph

**Comment by kmlucy** [comment]
Like I said, I really don't have any experience with JS. How can I check and repair that?

**Comment by kmlucy** [comment]
I am running DokuWiki inside a Docker container, so it looks like that is the root of the issue.

**Comment by kmlucy** [comment]
This line appears to be the issue: ```<script type="text/javascript" charset="utf-8" src="/dokuwiki/lib/exe/js.php?t=bootstrap3&amp;tseed=e2913edbbac0f3d0f76eb0f57e7d5d3b"></script>```

When I check that source, it ends abruptly:
```
	search: function( value, event ) {
		value = value != null ? value : this._value();

		// always save the actual value, not the one passed as an argument
		this.term = this._value();

		if ( value.length < t
```

It looks like that is causing the other errors.

When I enable or disable other plugins, the end of the file changes, but it is always abrupt, as in cutting off the end of the file.

**Comment by kmlucy** [comment]
Okay, so it looks like it is not a bootstrap3 issue. The strange cut off of js.php is occurring even on the stock DokuWiki template. Thank you for the help in diagnosing it.

**Comment by LotarProject** [comment]
Hi @kmlucy your DokuWiki is published on internet ?

**Comment by kmlucy** [comment]
Yes, it is at https://kmlucy.ddns.net/dokuwiki/

**Comment by trailjeep** [comment]
I had same issue as kmlucy - JQuery wasn't getting loaded.
Uninstalled bootstrap3 - same errors
Downgraded bootstrap3 - same errors.
I think it had to do with Google Chrome & Disconnect extension:
https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo
I had to allow content requests in Disconnect.
Of course also purged CSS & JS.
This doesn't explain why I see the the same errors @ kmlucy's site - so I am baffled.

**Comment by trailjeep** [comment]
Uninstalled disconnect and now tools drop-down works & no js console errors on kmlucy's site.
So its not a server side issue.

**Comment by kmlucy** [comment]
I am seeing the issue persist on every browser and device I have tried it on: 
- Chome on Windows 10
- Microsoft Edge on Windows 10 (no add-ons)
- Internet Explorer 11 on Windows 10 (no add-ons)
- Chrome on Android
- Chromebook

I don't run disconnect on any of my browsers, and I have attempted disabling µBlock Origin in Chrome.

You said you were able to not get the 'Uncaught Syntax Error' and were able to access the dropdowns on my site?

**Comment by LotarProject** [comment]
Hi @kmlucy, i have executed, on your site, several purge via ``lib/exe/js.php` url but the issue persist. I think this is a DokuWiki issue or another plugin cause an exception on ``js.php`` script.

I suggest to inspect your Apache error log to find errors or exceptions for ``js.php`` script.

At your disposal,
Joseph

**Comment by kmlucy** [comment]
Yes, I believe it is a DokuWiki issue. I have opened an issue there: splitbrain/dokuwiki#1779

**Comment by LotarProject** [comment]
Thanks 😉

**Comment by trailjeep** [comment]
![kmlucysite1](https://cloud.githubusercontent.com/assets/175368/21271245/338cb7ae-c388-11e6-9ccd-c62d1c10a10f.png)

![kmlucysite2](https://cloud.githubusercontent.com/assets/175368/21271252/3c6fae3a-c388-11e6-9b9b-79d60c689815.png)

**Comment by kmlucy** [comment]
I am not able to replicate that at all, on any browser, on any device. @trailjeep, do you mind posting in the DokuWiki Issue linked above to see if they can do anything with that over there?

**Comment by trailjeep** [comment]
Hmmm...I can't get it to work at all w/firefox - shows syntax and jquery errors in console.
I don't know much, but I **_think_** the fact that I can view your site fine in chrome (Version 55.0.2883.87 (64-bit)) proves this not to be bootstrap3 tpl or dokuwiki related.
My site had the same errors as you and now works fine in chrome & ff.
I would start here https://observatory.mozilla.org/analyze.html?host=kmlucy.ddns.net and get your server configs up to snuff.

**Comment by polyzen** [comment]
Doesn't work for me with `chromium --disable-extensions` of the same version. o.O

**Comment by trailjeep** [comment]
I think that adds to the evidence that it is a server / header config issue on kmlucy's site, but I don't know enough to specifically say what.
Someone more knowledgable than I could probably check https://observatory.mozilla.org/analyze.html?host=kmlucy.ddns.net and spell it out for us.

**Comment by LotarProject** [comment]
@trailjeep @kmlucy

What is your environment stack?

  * Web server (eg. apache, nginx) and version
  * PHP version

At your disposal,
Joseph

**Comment by kmlucy** [comment]
This is through the https://github.com/istepanov/docker-dokuwiki container. It uses php7 and nginx running on Alpine. 
```
# nginx -v
nginx version: nginx/1.10.1
# php7 -v
PHP 7.0.13 (cli) (built: Nov 16 2016 17:49:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
# cat /etc/*-release
3.4.4
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.4
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by kmlucy** [comment]
@trailjeep, as per your recommendations, I got my security passing in Observatory, but haven't seen any change with this issue.

**Comment by trailjeep** [comment]
> @trailjeep, as per your recommendations, I got my security passing in Observatory, but haven't seen any change with this issue.
Sorry, that's all I got.  This is above my head.
Oddly, now I see the errors on your site again and cannot get it to work with chrome?!?!
Oh well, at least your server is better configured now!

**Comment by kmlucy** [comment]
Thanks for the help regardless!

**Comment by kmlucy** [comment]
I solved it. It turns out it was a permissions error on the ```/var/lib/nginx/``` directory, which was resulting in permission being denied to the fastcgi directory. I changed the directory owner and it looks like it is fixed now.

 I believe the issue stemmed somehow from a combination of my work in setting it up, and the Docker image I use: [istepanov/docker-dokuwiki](https://github.com/istepanov/docker-dokuwiki). I have not had the problem resurface even after rebuilding the container, so I'm not sure how it happened. Regardless, it was not an issue with either DokuWiki or Bootstrap3, as I had initially suspected. 

Thank you all for the help troubleshooting,
Kyle

**Comment by LotarProject** [comment]
Thank you!

**Comment by Nata16** [comment]
Hello,

**Comment by sslashi** [comment]
Have the same problem on Debian8 + Apache with button malfunction for admin, profile, logoff.

And in my situation there is no /var/lib/nginx/ directory. Tried to change ownership of /var/lib/apache2 with www-data user, but the same problem.

**Comment by trailjeep** [comment]
Had this issue pop up again after setting up a new server.
I had installed Pihole network wide adblocker.
Pihole uses dnsmasq and I turned on DNSSEC.
My debian distro only had dnsmasq v2.72 and v2.73 introduced a fix (Fix broken DNSSEC validation of ECDSA signatures.)
This was causing issues with various CDN providers.
Ref: https://serverfault.com/a/740529

**Comment by LotarProject** [comment]
Same problem of #291
