### ISSUE TITLE
Error: Can't change missing link and link color

### ISSUE THREAD

**Issue by Django-BOfH** [LotarProject/dokuwiki-template-bootstrap3#258]
### Description
With dokuwiki's original template I can change the colors for missing links and links. With bootstrap3 template I can't do it anymore.

### Steps to Reproduce
If I change the color with "Template Style Settings" both colors for "missing links" = __missing__ and "links" = __existing__ the old red ond blue values still be used. :/

### Versions

  * [Bootstrap3 Template] latest version from 216-10-26
  * [DokuWiki] 2016-06-26a "Elenor of Tsort"
  * [Browser] IE and Firefox

**Comment by LotarProject** [comment]
Hi @Django-BOfH,
Bootstrap3 template is not integrated with "styling plugin" and i have plan to add this feature in the future release.

At your disposal,
Joseph

**Comment by LotarProject** [comment]
It's possible change the link color using a custom CSS (``<dokuwikidir>/conf/userstyle.css``).

```.css
/* inexistent DokuWiki page  */
.wikilink2 { color: red; }
/* existent DokuWiki page */
.wikilink1 { color: blue; }
```

Joseph

**Comment by Django-BOfH** [comment]
O.K., I'll try your suggestion ...

**Comment by Django-BOfH** [comment]
wunderful, it works! Thank you for your help! ;)
