### ISSUE TITLE
FRE: dark variant of the bootstrap3 theme

### ISSUE THREAD

**Issue by MarcinOrlowski** [LotarProject/dokuwiki-template-bootstrap3#259]
First, thanks for the your contribution - bootstrap3 template is the best one I managed to find. The only thing I am currently missing is dark variant of the template. Is there any chance you could have such version too? Thanks

**Comment by LotarProject** [comment]
Hi! Thanks for using my template :)

By default Bootstrap vanilla theme have only one variant (optional), but Bootswatch themes have many black variants (eg. Darkly, Slate).

Can you change the template via Configuration Manager using this config:
  * ``bootstrapTheme``:  Bootstrap vanilla or optional theme, Bootswatch.com Theme or a custom theme
  * ``bootswatchTheme``: Bootswatch.com theme (samples at http://bootswatch.com)
  * ``showThemeSwitcher``: Show Bootswatch.com theme switcher in navbar

At your disposal,
Joseph

**Comment by MarcinOrlowski** [comment]
Thanks for the hint. Not sure how I manged to overlook this in settings - now it works perfect :)
