### ISSUE TITLE
Image Alignment

### ISSUE THREAD

**Issue by duenni** [LotarProject/dokuwiki-template-bootstrap3#26]
Hi,

thanks for this superb template!
If I do something like this in default template
```
{{wiki:dokuwiki-1.png}}
{{wiki:dokuwiki-2.png}}
{{wiki:dokuwiki-3.png}}
```
the images in the resulting page are displayed in a row, horizontally. In your template the images are diplayed on top of each other or vertically. Is this done intentionally? I can't seem to change this behaviour which is okay for mobile devices but seems strange when viewed with a higher resolution display. With the default theme you would place spaces in between to put the image on top of each other.
```
{{wiki:dokuwiki-1.png}}

{{wiki:dokuwiki-2.png}}

{{wiki:dokuwiki-3.png}}
```
Thanks for looking into this.

**Comment by LotarProject** [comment]
Hi. Thanks for using my template and report this issue ;)
This is Bootstrap default behavior for all images with ".img-responsive" class.

I have replicated the default DokuWiki behavior in last commit 4479d1d

Best regards,
Joseph

**Comment by duenni** [comment]
That was a fast fix. :open_mouth: Thanks!

**Comment by duenni** [comment]
This bug is back with the newest version. :confused:

**Comment by LotarProject** [comment]
Hi. I have tested in a fresh DokuWiki installation and work. I have created a test page with this code:

```
{{ wiki:dokuwiki-128.png}}
{{wiki:dokuwiki-128.png }}
{{ wiki:dokuwiki-128.png }}
```

And this:

```
{{ wiki:dokuwiki-128.png}} Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\\
\\

{{wiki:dokuwiki-128.png }} Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\\
\\

{{ wiki:dokuwiki-128.png }} Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Can you purge the DokuWiki and browser cache ?

At your disposal,
Joseph

**Comment by duenni** [comment]
Mhh, I don't know what's going on. When I put spaces for alinement into the command the images are not rendered at all. With no spaces they are on top of eacht other. Purged the cache with `&purge=true`, tried from different clients with IE11 and FF 38.1.0

**Comment by duenni** [comment]
So, I played around with some options. Changed `tpl»bootstrap3»bootstrapTheme` to "optional" and "vanilla". Activated `tpl»bootstrap3»fluidContainer`, `tpl»bootstrap3»pageOnPanel`, `tpl»bootstrap3»useAnchorJS`, `tpl»bootstrap3»tableFullWidth` to no avail. Tried different browsers like FF, IE, Opera, purged the cache of some sites, changed theme to DokuWiki default (images are in a row then) and back to Bootstrap 3 (images are on top of each other). Also got feedback from users asking why the images are not in a row anymore...
Would be nice if you could look into this again.
Thanks in advance!
