### ISSUE TITLE
full width use.

### ISSUE THREAD

**Issue by Hakker** [LotarProject/dokuwiki-template-bootstrap3#260]
How can I make the width be the entire width of the screen. now it seems like it's fixed towards a certain width and not based on screen width.

**Comment by LotarProject** [comment]
Hi @Hakker, can you change this behavior by changing this config:
  * ``fluidContainer`` (default: 0) enable/disable the fluid container
  * ``fluidContainerBtn`` (default: 0) display a button in navbar for enable/disable the fluid container

At your disposal,
Joseph

**Comment by Hakker** [comment]
That works with the menu fine but for some reason the actual articles just stay at the old size.

**Comment by LotarProject** [comment]
Hi @Hakker,
what is the version of Bootstrap3 template ? This issue was fixed in v2016-07-05

Joseph

**Comment by Hakker** [comment]
Installed version:
    2016-07-05
Your last update:
    Thu, 22 Sep 2016 16:04:06 +0200 
which is around the time I actually installed it.

**Comment by Hakker** [comment]
I tried re-installing it. Also removing it and all files of the server and install it again from the dokuwiki site but it stays the same.

**Comment by bobdeh** [comment]
There is a administration page in the admin section doku.php?id=start&do=admin&page=styling with the option "__site_width__" You should make sure it is set to 100%.

**Comment by Hakker** [comment]
there is no such option there.

**Comment by LotarProject** [comment]
Hi @Hakker, you have your DokuWiki installation on internet?

**Comment by LotarProject** [comment]
Hi @bobdeh @Hakker , Bootstrap3 template don't have Styling Plugin support.

**Comment by Hakker** [comment]
sent an email to you unless that has changed with details.

**Comment by LotarProject** [comment]
Hi @Hakker, thanks for your mail and your test server. After testing, i have created a new patch for master and develop branch and now work!

Thanks!

**Comment by Hakker** [comment]
can confirm that it works here as well.
