### ISSUE TITLE
Bad TOC behaviour

### ISSUE THREAD

**Issue by bobdeh** [LotarProject/dokuwiki-template-bootstrap3#267]
### Description
Closing TOC moves the TOC button to the top ob the browser window.
See: http://i.imgur.com/8J0URcV.png
When you try to open it again it immediately closes itself. You have to scroll down the page to make the TOC work correctly again.

### Steps to Reproduce
1. Open article
2. Close TOC and don't scroll
3. Try to open TOC

### Possible Solution 
With the current developer branch it works. Yet the developer version has the bug that using tpl»bootstrap3»tocCollapsed=1 makes it impossible to open TOC without scrolling down.

### Versions
- [Bootstrap3 Template] v2016-07-05 (installed newest master at 2016-11-11)
- [DokuWiki] 2016-06-26a "Elenor of Tsort"
- [Browser] Chrome 51.0.2404.103m (also tested with IE and Firefox)

**Comment by polyzen** [comment]
Thank you for the fix. :)
