### ISSUE TITLE
Click in TOC doesn't update url in browser

### ISSUE THREAD

**Issue by tmo26** [LotarProject/dokuwiki-template-bootstrap3#268]
### Description

Bug: When clicking on a section in a TOC, the page moves to that section, but the url in the browser doesn't change.

### Steps to Reproduce

1. Goto https://wiki.lede-project.org/faq
2. In the TOC, click e.g. "Where is the Forum?"

**Expected behavior:** After clicking "Where is the Forum?", url in browser get's updated to https://wiki.lede-project.org/faq#where_is_the_forum

**Actual behavior:** After clicking "Where is the Forum?", url in browser stays at https://wiki.lede-project.org/faq

-> Expected and actual behavior are not in line.

3. In the main page, when you hover over the section title, a link appears to the right of the section title. Click on it.

**Expected behavior:** After clicking the link, url in browser get's updated to https://wiki.lede-project.org/faq#where_is_the_forum

**Actual behavior:** After clicking the link, url in browser get's updated to https://wiki.lede-project.org/faq#where_is_the_forum

-> Expected and actual behavior are perfectly in line for these links.

### Versions

  * [Bootstrap3 Template] Installed version: 2016-07-05
  * [DokuWiki] 2016-06-26a "Elenor of Tsort"
  * [Browser] FF 50.0 + chrome 54.0.2840.99 m

**Comment by bobdeh** [comment]
When you disable java script the TOC acts as you expect it. Only the "scroll down animation" will be gone.
So i guess that it results from this animation: the browser does not handle the link like a URL but instead executes the java scripts and scrolls down. Either the animation would have to be removed or in the java script the browser url has to be updated.

**Comment by tmo26** [comment]
Both solutions would be OK for me.

**Comment by polyzen** [comment]
:+1:
