### ISSUE TITLE
Re-open h2~h6 section toggle when xs size -> sm, md or lg size

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#269]
### Description
I checked 'h2-h6 section toggle' in dokuwiki admin page.
It is ok that h2-h6 headline toggled when window is little(sm, md, lg).
But, when I was re-size window to big, headline was closed yet.

How can I change re-open h2~h6 section toggle when xs size -> sm, md or lg size?

### Steps to Reproduce
1. Checked 'section toggle' function in admin page.
2. I can see collapsed headline when window is small.
3. But, when I resized window to big, headline doesn't open yet.

### Versions
  * [Bootstrap3 Template] latest
  * [DokuWiki] latest
  * [Plugin]
  * [Browser]

### Screenshots or Logs
1. Before - small screen
![before](https://cloud.githubusercontent.com/assets/7350716/20455125/552f055c-ae97-11e6-8785-c63657790cc2.jpg)

2. After - full or big screen
![after](https://cloud.githubusercontent.com/assets/7350716/20455128/6bd8b87a-ae97-11e6-8052-d8a9fb3f35e1.jpg)

### Sample Page
http://www.animint.net/note/

P.S 1 - How can I change to use section toggle when screen that access with tablet in width mode (not height mode)?
Next screen is width mode when I access using tablet phone.
![width](https://cloud.githubusercontent.com/assets/7350716/20455156/465cb744-ae98-11e6-898b-a7595e158e3e.jpg)

P.S 2 - I using korean, but toc list doesn't line break when screen is small. How can I change?
For example, 'ㄱㄴㄷㄹ ㅁㅂㅅ' is looked
'ㄱㄴㄷㄹ ㅁ
ㅂㅅ'
in small window(screen).
![toc](https://cloud.githubusercontent.com/assets/7350716/20455130/86eaf100-ae97-11e6-996e-acb8953e427d.jpg)

I'm sorry to my bad english ; (

**Comment by lattekun** [comment]
Or,
Would you ming using 'sectiontoggle' plugin to this template?
It is useful to mobile, but it is difficult to config.
I think, it is problem of cache or template version...

**Comment by lattekun** [comment]
http://www.dokuwiki.org/plugin:sectiontoggle

**Comment by lattekun** [comment]
Plus Question
P.S 3 - When I configured toc admin to do collapse toc box
(if scroll to bottom, change to small size box of toc),
if I click headline 1~6 in toc box,
headline (in content) is hide in navbar. How can I change to solve?

**Comment by lattekun** [comment]
Please, help me!

**Comment by lattekun** [comment]
@LotarProject
Thank you to your help, but it is not work...

**Comment by LotarProject** [comment]
Hi, can you flush the Dokuwiki and browser cache ?

**Comment by lattekun** [comment]
@LotarProject 
Yes. I deleted cache using 2 method(delete cache plugin, delete in ftp) and browser,
but it isn`t work...uu

**Comment by LotarProject** [comment]
Hi! I have fixed this issue in develop branch.

**Comment by lattekun** [comment]
@LotarProject 
Sorry, It doesn`t work yet... would you mind check my template(modify version)?
https://github.com/lattekun/animint

**Comment by LotarProject** [comment]
Hi @lattekun i have backported the patch in master branch.

**Comment by lattekun** [comment]
It is work well in other install link(not my homepage url),
but my homepage doesn`t work.
also I delete cache... What should I do?

**Comment by lattekun** [comment]
Oh, it work! thanks.
But it is not work when inserted list syntax in own section...
I think, it is bug;;
