### ISSUE TITLE
Image detail page does not render correct

### ISSUE THREAD

**Issue by duenni** [LotarProject/dokuwiki-template-bootstrap3#27]
Hi,

when clicking an image in DokuWiki you'll get redirected to a "detail page" containing a larger version of the image and some EXIF data etc..
This detail page `mywiki.com/wiki/lib/exe/detail.php?` won't render in "bootstrap style". See screenshot below:
![screenshot](https://cloud.githubusercontent.com/assets/4258185/7615506/5c20904c-f99e-11e4-9d7f-a2b38d932dbc.png)

**Comment by LotarProject** [comment]
Hi! I have forgot the detail page to styling.
Added in last commit 104d082

Thanks for reporting this issue :wink: 

Best regards,
Joseph

**Comment by duenni** [comment]
You are blazing fast in fixing stuff!  :thumbsup:
And this template is by far the best looking bootstrap template for DokuWiki. So, thanks again for fixing.

**Comment by duenni** [comment]
Hi there,

in the latest release it seems like this issue is back again.

Regards
duenni

**Comment by LotarProject** [comment]
Hi, this issue was re-fixed in 45122ea commit (see #145).
Sorry.

Regards,
Joseph
