### ISSUE TITLE
minimized TOC hides horizontal lines <hr>

### ISSUE THREAD

**Issue by bobdeh** [LotarProject/dokuwiki-template-bootstrap3#270]
### Steps to Reproduce
1. minimize/hide TOC
2. TOC is minimized/hidden but so are horizontal lines hr, too.

**Expected behavior:**
<hr> should not be affected

### Versions
current developer version

### Solution
Remove the line 66 (hr,) from toc.less

```
.dw-toc-closed {
  hr,
  .toc-title span,
  .toc-body         { display: none; }
}
```

**Comment by LotarProject** [comment]
Hi @bobdeh,
i have removed this old CSS rule from develop branch.

Thanks!
Joseph

**Comment by bobdeh** [comment]
Thanks for the fix.
Works now as expected.
