### ISSUE TITLE
Discussion, tag plugin not working properly after template update

### ISSUE THREAD

**Issue by kiritype** [LotarProject/dokuwiki-template-bootstrap3#274]
### Description

Hello.
I'm sorry I'm not accustomed to English

after template update(v2016-12-12)
- no part of the output discussion plugin in some page and threads not shown
- tag plugin output at the bottom of page

### Screenshots or Logs

![1](https://cloud.githubusercontent.com/assets/5303410/21123051/a02f7638-c119-11e6-8800-d81816caf111.PNG)

discussion plugin not working
tag plugin working at the bottom

![2](https://cloud.githubusercontent.com/assets/5303410/21123059/a54445b8-c119-11e6-8280-666d6930f105.PNG)

discussion plugin working in some page

![3](https://cloud.githubusercontent.com/assets/5303410/21123238/e1137e5a-c11a-11e6-815e-11c15dcae572.PNG)

discussion threads not shown

### Sample Page
http://wsg.mobage.wiki

**Comment by LotarProject** [comment]
Hi @kiritype, thanks for reporting this issue. I have fixed this issue in master and develop branch. Please reinstall again the template.

At your disposal,
Joseph

**Comment by kiritype** [comment]
thank you for your prompt action
The issue with the tag plugin has been resolved.

but I reinstall again the template, discussion plugin still not working page with comments.
(example: http://wsg.mobage.wiki/%ED%95%A8%EC%84%A0/%EC%95%84%ED%82%A4%EC%A6%88%ED%82%A4 )
I confirmed that it works if I delete comment file.
is this discussion plugin's problem?
