### ISSUE TITLE
Plugin 'inlinetoc' doesn't work

### ISSUE THREAD

**Issue by lattekun** [LotarProject/dokuwiki-template-bootstrap3#275]
### Description
I`m using 'inlinetoc' plugin in aside(sidebar) to instead of original toc.
However, it is not work. Details, one wiki`s main(start) page`s toc list showing,
But, if I click other page, toc list doesn`t change. (showing main page`s toc list)

### Steps to Reproduce
1. Install bootstrap 3 template and inlinetoc plugin
2. You can see that original toc is hide.
3. But, if you click other page, instead toc list not shown that page`s toc list.
4. If you see that page`s toc list, you have to delete cache file.

### Versions
  * [Bootstrap3 Template] latest
  * [DokuWiki] latest
  * [Plugin] inlinetoc plugin latest
  * [Browser] IE and Chrome

### Sample Page
![inlinetoc](https://cloud.githubusercontent.com/assets/7350716/21181666/574ad0fa-c242-11e6-97bb-87d45a847fb3.jpg)

**Comment by LotarProject** [comment]
Fixed in upcoming release of template.
