### ISSUE TITLE
TOC over Content after update from 2016-12-12

### ISSUE THREAD

**Issue by ded5b13328** [LotarProject/dokuwiki-template-bootstrap3#277]
### Description

After the update to the version from v2016-07-05 to v2016-12-12 the TOC is shown over the Content. Also the content is always 100 % width (different issue)

### Steps to Reproduce

1. Update from v2016-07-05 to Version v2016-12-12
2. Open Configuration and scroll

**Expected behavior:**
I expected that the toc is on the right hand next to the content like it was befor the update (see screenshots)

**Actual behavior:** 
The TOC is over the Content and hides it

### Versions

  * [Bootstrap3 Template] Version from 2016-12-12
  * [DokuWiki] latest
  * [Plugin] it happens on two different wikis. One isn't updated yet to the newest Bootstrap 3 Theme and works fine. Common plugins of all three are
   * ACL Manager
   * authpdo plugin
   * Plain Auth Plugin 
   * CAPTCHA Plugin
   * Configuration Manager 
   * Extension Manager 
   * Gallery Plugin
   * Info Plugin
   * Popularity Feedback Plugin
   * DokuWiki Upgrade Plugin 
   * User Manager 
   * Video Sharing Site Plugin
   * Wrap Plugin 
  * [Browser] Chrome (latest), Firefox (latest)

### Screenshots or Logs

Expected:
![wiki_exp 1](https://cloud.githubusercontent.com/assets/3877180/21310219/a5f08f9a-c5e1-11e6-8ff1-3bd476f22622.png)

Actual:
![wiki_act 1](https://cloud.githubusercontent.com/assets/3877180/21310236/bc3a4926-c5e1-11e6-9abb-1b7d98dd202d.png)

### Note

I reinstalled version v2016-07-05 and everything works as expected

**Comment by polyzen** [comment]
Intended behavior: https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/249

Release notes here: https://github.com/LotarProject/dokuwiki-template-bootstrap3/releases/tag/v2016-12-12

**Comment by bobdeh** [comment]
The TOC should normally be next to the content after loading the site.
When you enable to close TOC at scrolling and open it manually after scrolling down it opens over the content (what i prefer).
When TOC is configured to stay opened while scrolling down, i agree that it should stay next to the content.

**Comment by LotarProject** [comment]
Hi @bobdeh @polyzen,
i'm working to add a new option for choice the preferred TOC style:
  * Bootstrap-style TOC (like http://getbootstrap.com/) used in the previous release (beside the contents)
  * Default and "historic" TOC (hover the contents)

I plan to issue this release at the end of month.

Best regards and ... happy new year!
Joseph

**Comment by polyzen** [comment]
> Best regards and ... happy new year!

Happy New Year :)

If we can get a [border](https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/249#issuecomment-254167743) or something for the bootstrap-style TOC, perhaps both won't be needed.

Trying to look into it. :)

**Comment by polyzen** [comment]
For "next to content": How about TOC on the outside of sidebars [like so](https://ptpb.pw/5frx.png)? Disregard the PageTools, just an old shot. :p
