### ISSUE TITLE
navbar item only icon

### ISSUE THREAD

**Issue by senolv** [LotarProject/dokuwiki-template-bootstrap3#279]
Hi,

And this is an alternative without a label:

```
  * [[:start|{{fa>home}}]]
~~NOCACHE~~

```

Three bugs I recognized.

1. If you use "showHomePageLink"

and do not have home-button in :navbar

the font-sizes differ, items from tpl_navbar.php are smaller

OK, but I would agree it´s the better way to disable "showHomePageLink" because it´s more clearly if you have all items in one place (:navbar), but here ist a second bug, if you do not label the item (just icon) and if the item is selected in menu, it is not presented as selected (with special background).

And the third bug is: (this is not depending on bug 2)

If you choose another item in sidebar, the selected state of navebar item gets lost, allthough the new choosen item in sidebar is in the same navbar-menu.

Last but not least: this is a great work! Thanks

**Comment by LotarProject** [comment]
Hi, the second bug is a DokuWiki + Icon Plugin issue and in these month, don't have found a valid solution.

Sorry :(
