### ISSUE TITLE
multi popups in search result

### ISSUE THREAD

**Issue by LotarProject** [LotarProject/dokuwiki-template-bootstrap3#282]
_From @Juergen-aus-Koeln on December 20, 2016 9:37_

Hi Lotar,

when you quickly hover over the search result list the popups from the semantic plugin are overlapped.
 
_Example:_
![2016-12-20 10_34_23-suche test-wiki](https://cloud.githubusercontent.com/assets/1800472/21345338/2296a714-c6a0-11e6-8cde-18cf9df641d4.png)

Best regards
Juergen

_Copied from original issue: LotarProject/dokuwiki-plugin-semantic#5_

**Comment by LotarProject** [comment]
Duplicate of #281

**Comment by Juergen-aus-Koeln** [comment]
Hi,

the problem still exists in the actual release of your template:
![grafik](https://user-images.githubusercontent.com/1800472/36777067-5aae4854-1c68-11e8-8715-635e6d260a46.png)

Best regards
Juergen
