### ISSUE TITLE
Problem with Facebook share

### ISSUE THREAD

**Issue by Polarwelt** [LotarProject/dokuwiki-template-bootstrap3#283]
Hy Lotar,
i have an problem with Facebook share.
If i want to share an article via facebook, there will always shown the text "Zeige Quelltext Ältere Versionen Links hierher" before the article.

I think this is caused by the links in the content. Do you see an opportunity to correct this? I could understand the errors on all bootstrap installations with activate Share buttons.

### Steps to Reproduce

1. Share an article on facebook
![bootstrap](https://cloud.githubusercontent.com/assets/20779887/21929990/ef18e0b2-d993-11e6-9b73-a884f057abbc.jpg)

### Versions

  * [Bootstrap3 Template]
  * [DokuWiki] Release 2016-06-26a "Elenor of Tsort"
  * [Browser] Vivaldi, Chrome, Firefox

Best Regards

Robert

**Comment by LotarProject** [comment]
Hi @Polarwelt,
i think Facebook catch the first portion of text in the page.

I have replicated in my development and online DokuWiki installation (http://lotar.altervista.org) but i dont'have the same behavior. This is an example from your website (i think 😛)

![immagine](https://cloud.githubusercontent.com/assets/1824717/22284908/a066dabe-e2e9-11e6-840e-039d27b5b86b.png)

I suggest to use my Semantic Plugin (https://www.dokuwiki.org/plugin:semantic) to add metadata (HTML description, Schema.org,  OpenGraph, DublinCore, etc) for SEO and the social networks.

At your disposal,
Joseph
