### ISSUE TITLE
Table header broken with database2 plugin

### ISSUE THREAD

**Issue by justemu** [LotarProject/dokuwiki-template-bootstrap3#288]
### Description

The table header is broken with database2 plugin. - all the header titles crowded in the first column, leaving the rest columns no header titles.

### Steps to Reproduce

1. Create A new page.
2. Use the` <database>` tag of database2 plugin to open a table.
3. Save the page

**Expected behavior:** [What you expected to happen]
A table populated with the data from the database shows up.
The header of each column displays above corresponding column.

**Actual behavior:** [What actually happened]
The table populated with the data from the database shows up.
However, all the headers of the table crowded in the first column.( PLS check the screenshot)

-
The table displays correctly, as long as I change the template of the site back to dokuwiki template.
And the problem shows again, if I change the template of the site back to bootsrap3. 

### Versions

  * [Bootstrap3 Template] 2016-12-12
  * [DokuWiki] 2016-06-26 "Elenor Of Tsort" 
  * [Plugin] database2 2014-11-25
  * [Browser] Chrome 55.0.2883.87 & Safari 

### Screenshots or Logs
table broken with template bootstrap3
![image](https://cloud.githubusercontent.com/assets/20639347/22728440/e6da4668-ee18-11e6-8169-6f25bd241166.png)

table shows normal with template dokuwiki 
![image](https://cloud.githubusercontent.com/assets/20639347/22729110/43cff518-ee1c-11e6-96c9-94c47d61a363.png)

### Sample Page

[Paste your sample DokuWiki page](https://mba.touyan.net/wiki/database/药品招标/氯吡格雷)

**Comment by justemu** [comment]
here is the html source I obtained with chrome (corresponding to the first screenshot above)... The script of table seems correct, but I render the wrong table head - all the theads crowed in the first column - I don't know why. who can help me out?

`<table width="100%">
    <thead>
     <tr class="row0">
      <th class="counter"></th>
      <th class="label">药品名&nbsp;<input type="image" name="db2dosortDrugName[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">商品名&nbsp;<input type="image" name="db2dosortDrugTradeName[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">剂型&nbsp;<input type="image" name="db2dosortDosageForm[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">规格&nbsp;<input type="image" name="db2dosortSize[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">包装&nbsp;<input type="image" name="db2dosortPack[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">单位&nbsp;<input type="image" name="db2dosortUnit[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">中标价&nbsp;<input type="image" name="db2dosortBidPrice[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">质量层次&nbsp;<input type="image" name="db2dosortQualityLevel[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">生厂商&nbsp;<input type="image" name="db2dosortManufacturer[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">省份&nbsp;<input type="image" name="db2dosortProvince[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>
<th class="label">日期&nbsp;<input type="image" name="db2dosortDate[1]" src="/lib/plugins/database2/icons/none.gif" title="Sort by this column ascendingly"/></th>

      <th class="commands"></th>
     </tr>
    </thead>
    <tbody>
     <tr class="first odd row1"><td class="counter col0 rightalign">1</td>
<td class="text col1">硫酸氢氯吡格雷片(薄膜衣)</td>
<td class="text col2">波立维</td>
<td class="text col3">薄膜衣片</td>
<td class="text col4">75mg</td>
<td class="text col5">7</td>
<td class="text col6">盒</td>
<td class="real col7">132.17</td>
<td class="text col8">专利药品</td>
<td class="text col9">法国赛诺菲Sanofi Winthrop Industries(杭州赛诺菲分装)</td>
<td class="text col10">吉林</td>
<td class="date col11">2008/01/01</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect4798[1]" id="db2docmdinspect4798[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="even row2"><td class="counter col0 rightalign">2</td>
<td class="text col1">硫酸氢氯吡格雷片</td>
<td class="text col2">泰嘉</td>
<td class="text col3">片剂</td>
<td class="text col4">25mg</td>
<td class="text col5">20</td>
<td class="text col6">瓶（盒）</td>
<td class="real col7">79</td>
<td class="text col8"></td>
<td class="text col9">深圳信立泰药业股份有限公司</td>
<td class="text col10">甘肃</td>
<td class="date col11">2009/01/01</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect4894[1]" id="db2docmdinspect4894[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="odd row3"><td class="counter col0 rightalign">3</td>
<td class="text col1">硫酸氢氯吡格雷</td>
<td class="text col2">波立维</td>
<td class="text col3">薄膜衣片</td>
<td class="text col4">75mg×7片</td>
<td class="text col5"></td>
<td class="text col6"></td>
<td class="real col7">128.9</td>
<td class="text col8">专利</td>
<td class="text col9">杭州赛诺菲安万特民生制药有限公司-1</td>
<td class="text col10">新疆</td>
<td class="date col11">2009/05/31</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect13982[1]" id="db2docmdinspect13982[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="even row4"><td class="counter col0 rightalign">4</td>
<td class="text col1">硫酸氢氯吡格雷</td>
<td class="text col2">波立维</td>
<td class="text col3">片剂</td>
<td class="text col4">75mg*7片</td>
<td class="text col5">75mg*7片</td>
<td class="text col6">盒</td>
<td class="real col7">132</td>
<td class="text col8">专利原研</td>
<td class="text col9">法国（杭州赛诺菲安万特民生制药）</td>
<td class="text col10">内蒙古</td>
<td class="date col11">2009/01/01</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect26790[1]" id="db2docmdinspect26790[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="odd row5"><td class="counter col0 rightalign">5</td>
<td class="text col1">硫酸氢氯吡格雷</td>
<td class="text col2">泰嘉</td>
<td class="text col3">素片</td>
<td class="text col4">25mg×10片</td>
<td class="text col5"></td>
<td class="text col6"></td>
<td class="real col7">39</td>
<td class="text col8">普通GMP</td>
<td class="text col9">深圳信立泰药业股份有限公司</td>
<td class="text col10">新疆</td>
<td class="date col11">2009/05/31</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect31832[1]" id="db2docmdinspect31832[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="even row6"><td class="counter col0 rightalign">6</td>
<td class="text col1">硫酸氢氯吡格雷片(薄膜衣)</td>
<td class="text col2">波立维</td>
<td class="text col3">薄膜衣片</td>
<td class="text col4">75mg</td>
<td class="text col5">7</td>
<td class="text col6">盒</td>
<td class="real col7">127.96</td>
<td class="text col8"></td>
<td class="text col9">法国赛诺菲Sanofi Winthrop Industries(杭州赛诺菲分装)</td>
<td class="text col10">江苏</td>
<td class="date col11">2010/02/05</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect41099[1]" id="db2docmdinspect41099[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="odd row7"><td class="counter col0 rightalign">7</td>
<td class="text col1">硫酸氢氯吡格雷片</td>
<td class="text col2">泰嘉</td>
<td class="text col3">素片</td>
<td class="text col4">0.025g</td>
<td class="text col5">20</td>
<td class="text col6">片/瓶</td>
<td class="real col7">83.9</td>
<td class="text col8">GMP药品</td>
<td class="text col9">深圳信立泰药业股份有限公司</td>
<td class="text col10">湖北</td>
<td class="date col11">2008/01/01</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect62749[1]" id="db2docmdinspect62749[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="even row8"><td class="counter col0 rightalign">8</td>
<td class="text col1">硫酸氯吡格雷片</td>
<td class="text col2">波立维</td>
<td class="text col3"></td>
<td class="text col4">75mg*7T</td>
<td class="text col5">75mg*7T</td>
<td class="text col6">盒</td>
<td class="real col7">132.17</td>
<td class="text col8"></td>
<td class="text col9">杭州赛诺菲安万特民生制药有限公司</td>
<td class="text col10">内蒙古</td>
<td class="date col11">2010/01/01</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect77074[1]" id="db2docmdinspect77074[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="odd row9"><td class="counter col0 rightalign">9</td>
<td class="text col1">氯吡格雷</td>
<td class="text col2"></td>
<td class="text col3">片剂</td>
<td class="text col4">75mg</td>
<td class="text col5">7</td>
<td class="text col6">盒</td>
<td class="real col7">128</td>
<td class="text col8">专利</td>
<td class="text col9">杭州赛诺菲安万特民生制药有限公司</td>
<td class="text col10">河南</td>
<td class="date col11">2009/08/11</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect80130[1]" id="db2docmdinspect80130[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>
<tr class="last even row10"><td class="counter col0 rightalign">10</td>
<td class="text col1">硫酸氢氯吡格雷</td>
<td class="text col2">泰嘉</td>
<td class="text col3">素片</td>
<td class="text col4">25mg×20片</td>
<td class="text col5"></td>
<td class="text col6"></td>
<td class="real col7">76.06</td>
<td class="text col8">普通GMP</td>
<td class="text col9">深圳信立泰药业股份有限公司</td>
<td class="text col10">新疆</td>
<td class="date col11">2009/05/31</td>
<td class="commands col12"><input type="image" class="icon-cmd" name="db2docmdinspect90132[1]" id="db2docmdinspect90132[1]" title="View This Record" src="/lib/plugins/database2/icons/view.gif" onclick="" /></td></tr>

    </tbody>
    <caption>
     <input type="submit" name="db2donum10[1]" value="10" class="selected pure-text" />
<input type="submit" name="db2donum20[1]" value="20" class="pure-text" />
<input type="submit" name="db2donum50[1]" value="50" class="pure-text" />
<input type="submit" name="db2donum100[1]" value="100" class="pure-text" /> &mdash; 82 records on 9 pages
    </caption>
   </table>
   </td>
  </tr>
  <tr class="lower-navigation">
   <td colspan="3">
    
   </td>
  </tr>
 </tbody>
</table>`

**Comment by justemu** [comment]
I fixed this issue. The conflict comes from the style class "label", which has an attribute “display: inline” defined in the bootstrap3 template. The database2 plugin has applied class "label" in is  <th>, leading to this problem of crowed table headers.

my solution is to define a "display: table-cell" attribute in the plugin's <th> overiding the attribute defined in the bootstrap3 template. And the table returns normal.

Now this issue is closed.

**Comment by LotarProject** [comment]
Hi @justemu, thanks to reporting this issue and for your investigation.

I think its possible to add your suggested patch in Bootstrap3 template.

At your disposal,
Joseph

**Comment by justemu** [comment]
I am glad that I helped. 
best regards
Benjamin
