### ISSUE TITLE
Feature request: replace default Dokuwiki logo

### ISSUE THREAD

**Issue by rthill** [LotarProject/dokuwiki-template-bootstrap3#290]
I would love to be able to replace the default logo using a setting in the template configuration which remains also intact when updating the template, just like the custom CSS settings.

**Comment by xkpd3** [comment]
Just upload a file called "logo.png". Dokuwiki will automatically use it instead of the default one.

HTH,
Stefan

**Comment by rthill** [comment]
Yes, I know, but it is overwritten by each update.

**Comment by xkpd3** [comment]
Did you upload it via the media manager into the wiki namespace?
The template does not contain a `logo.png`. It should never be overwritten.

**Comment by rthill** [comment]
No I did not upload it using the media manager. Should I replace
the dokuwiki-128.png in the wiki namespace?

**Comment by xkpd3** [comment]
No. Just upload a file called "logo.png" as shown in the screenshot I've added.

**Comment by rthill** [comment]
Perfect, that works, I moved back the original logos and uploaded the logo.png to the wiki namespace.
