### ISSUE TITLE
Not compatible with jQuery 3 in latest Dokuwiki

### ISSUE THREAD

**Issue by webarnes** [LotarProject/dokuwiki-template-bootstrap3#291]
### Description

The latest version of dokuwiki updated jQuery to version 3. From the console: "bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3"

### Steps to Reproduce

Update dokuwiki.

### Versions

  * Bootstrap Template: 2016-12-12
  * Dokuwiki: Frusterick

**Comment by webarnes** [comment]
Bootstrap 3.3.7 supports jQuery 3.

http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/

**Comment by LotarProject** [comment]
Hi @webarnes, the actual version (v2016-12-12) of Bootstrap included in the template is v3.3.7 and have jQuery3 support.
Can you purge your browser cache and test again ?

At your disposal,
Joseph

**Comment by kalos** [comment]
hi @LotarProject, I have same problem.

I tested with firefox and chrome (with cache purged).

This is the chrome console error, in dokuwiki start page:

```

Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
    at bootstrap.min.js:6
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
js.php?t=bootstrap3&tseed=8a5978e…:1 Uncaught TypeError: jQuery(...).popover is not a function
    at js.php?t=bootstrap3&tseed=8a5978e…:1
(anonymous) @ js.php?t=bootstrap3&tseed=8a5978e…:1
jquery.php?tseed=38e996c…:2 Uncaught TypeError: jQuery(...).scrollspy is not a function
    at HTMLDocument.<anonymous> ((index):34)
    at j (jquery.php?tseed=38e996c…:2)
    at k (jquery.php?tseed=38e996c…:2)
(anonymous) @ (index):34
j @ jquery.php?tseed=38e996c…:2
k @ jquery.php?tseed=38e996c…:2
```

Thank you for this beautiful template plugin!

**Comment by webarnes** [comment]
Restarted my browser since yesterday and it works.

**Comment by kalos** [comment]
I've set **tpl»bootstrap3»bootstrapTheme** to Bootswatch.com theme and then to Vanilla, and now it works.

thanks

**Comment by TO-sthaessler** [comment]
Same Problem here, error message is exactly that one posted by @kalos.

How did you resolve the issues? Dont understand the last post.

**Comment by zympolium** [comment]
Same problem (@kalos) here.
Try @kalos solution and modify dokuwiki/conf/local.php without success

**Comment by LotarProject** [comment]
#241

**Comment by LotarProject** [comment]
Hi guys,
I have installed the new version of DokuWiki and Bootstrap3 on fresh machine and don't have this issue. Today i have updated a previous DokuWiki "Detritus" installation and have this issue. From Apache logs i saw the "HTTP 500" error for a new jQuery dispatcher file (``/lib/exe/jquery.php``) introduced in this new DokuWiki version.

To solve this problem i have changed the file permission to ``755`` (``rwxr-xr-x``).

I suggest to see Apache error/access log and repair file permission (https://www.dokuwiki.org/install:permissions).

At your disposal,
Joseph

**Comment by TO-sthaessler** [comment]
@bernhardbrunner 's solution worked for me, thank you!

(manually switch to default theme, reinstall bootstrap3, activate again in cofniguration)

**Comment by webarnes** [comment]
Now that I see @TO-sthaessler 's post, I remember that the other thing I did beside restarting my browser was switch to the default theme for a while so I could get work done. I did not reinstall bootstrap3 though. I just re-activated it.

**Comment by LotarProject** [comment]
Hi,
Generally this problem is caused by DokuWiki caching system. I suggest to "touch" the ``local.php`` file (via cli ``touch <dokuwiki-install-directory>/conf/local.php``) or via **Configuration Manager** (change an option and save). This two action cause a refresh of DokuWiki cache. In addition i suggest to purge CSS and JS DokuWiki cache (via ``http://<your-dokuwiki-server>/lib/exe/js.php?purge`` and ``http://<your-dokuwiki-server>/lib/exe/css.php?purge``) and Browser cache (specially for Chrome).

Joseph

**Comment by NDee303** [comment]
Hi, 
I had the same Problems. I did everything you suggested, but nothing worked. The Apache logs showed no conspicuous Messages. Now im running dokuwiki again with the older release "Elenor of Tsort" and it works fine with bootstrap3. Any other Ideas?

Andy

**Comment by werdlerk** [comment]
I tried all suggestions and kept having the problem. 

I found out that the file https://wiki.morgenwerk.nl/lib/tpl/bootstrap3/assets/bootstrap/js/bootstrap.min.js was reporting version v3.3.6 while the actual file was updated to v3.3.7. If you keep having problems, check this file in your browser and check the displayed version with the actual file on your web server!

I remembered I'm using Cloudflaree for my wiki installation. Purging the cache at Cloudflare solved the problem.

**Comment by MyIgel** [comment]
Another thing: Updating the template is helpful ;)

**Comment by cavazquez** [comment]
Uninstall and install template.

**Comment by MarcinOrlowski** [comment]
This worked for me:
 - manually edit `conf/local.php` file and change `$conf['template']` value from `bootstrap3` to `dokuwiki`.
 - reload to have default theme restored
 - go to `Admin -> Extension Manager`
 - switch to `Installed Templates` tab
 - hit `Update` next to `Bootstrap3 Template`
 - manually edit `conf/local.php` file and restore  `bootstrap3` as `$conf['template']` (or use GUI)
 - reload.

Voila.

**Comment by algorys** [comment]
Same issue for me after updating some plugin. Like @kalos said:

- Go to `YOUR_WIKI_FQDN/doku.php?id=accueil&do=admin&page=config#tpl____bootstrap3____template_settings_name`
- Change `tpl»bootstrap3»bootstrapTheme` to another choice and **Save** !
- Return to admin configuration, back `tpl»bootstrap3»bootstrapTheme` to your initial choice and **Save** again.

Then solved. (Tested on `2016-06-26a Elenor Of Tsort`)

**Comment by algorys** [comment]
@LotarProject after update to last version, problem is come back. Now even I change my template choice, problem persist.

Here is the console errors:

```js
js.php?t=bootstrap3&tseed=bb821b2…:1 Uncaught TypeError: jQuery(...).affix is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=bb821b2…:1)
    at HTMLDocument.dispatch (jquery.php?tseed=23f8886…:3)
    at HTMLDocument.q.handle (jquery.php?tseed=23f8886…:3)
    at Object.trigger (jquery.php?tseed=23f8886…:4)
    at HTMLDocument.<anonymous> (jquery.php?tseed=23f8886…:4)
    at Function.each (jquery.php?tseed=23f8886…:2)
    at a.fn.init.each (jquery.php?tseed=23f8886…:2)
    at a.fn.init.trigger (jquery.php?tseed=23f8886…:4)
    at js.php?t=bootstrap3&tseed=bb821b2…:1
(anonymous) @ js.php?t=bootstrap3&tseed=bb821b2…:1
dispatch @ jquery.php?tseed=23f8886…:3
q.handle @ jquery.php?tseed=23f8886…:3
trigger @ jquery.php?tseed=23f8886…:4
(anonymous) @ jquery.php?tseed=23f8886…:4
each @ jquery.php?tseed=23f8886…:2
each @ jquery.php?tseed=23f8886…:2
trigger @ jquery.php?tseed=23f8886…:4
(anonymous) @ js.php?t=bootstrap3&tseed=bb821b2…:1
js.php?t=bootstrap3&tseed=bb821b2…:1 Uncaught TypeError: jQuery(...).popover is not a function
    at js.php?t=bootstrap3&tseed=bb821b2…:1
(anonymous) @ js.php?t=bootstrap3&tseed=bb821b2…:1
js.php?t=bootstrap3&tseed=bb821b2…:1 Uncaught TypeError: $dw_toc.affix is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=bb821b2…:1)
    at HTMLDocument.dispatch (jquery.php?tseed=23f8886…:3)
    at HTMLDocument.q.handle (jquery.php?tseed=23f8886…:3)
    at Object.trigger (jquery.php?tseed=23f8886…:4)
    at HTMLDocument.<anonymous> (jquery.php?tseed=23f8886…:4)
    at Function.each (jquery.php?tseed=23f8886…:2)
    at a.fn.init.each (jquery.php?tseed=23f8886…:2)
    at a.fn.init.trigger (jquery.php?tseed=23f8886…:4)
    at js.php?t=bootstrap3&tseed=bb821b2…:1
(anonymous) @ js.php?t=bootstrap3&tseed=bb821b2…:1
dispatch @ jquery.php?tseed=23f8886…:3
q.handle @ jquery.php?tseed=23f8886…:3
trigger @ jquery.php?tseed=23f8886…:4
(anonymous) @ jquery.php?tseed=23f8886…:4
each @ jquery.php?tseed=23f8886…:2
each @ jquery.php?tseed=23f8886…:2
trigger @ jquery.php?tseed=23f8886…:4
(anonymous) @ js.php?t=bootstrap3&tseed=bb821b2…:1
jquery.php?tseed=23f8886…:2 Uncaught TypeError: jQuery(...).scrollspy is not a function
    at HTMLDocument.<anonymous> (doku.php?id=accueil:39)
    at j (jquery.php?tseed=23f8886…:2)
    at k (jquery.php?tseed=23f8886…:2)
```
I've tried to empty cache, restart server, uninstall and install template again. Nothing works :cry: 

An idea please ?

Server Debian Wheezy 7.11
Server version: Apache/2.2.22 (Debian)

**Comment by phy25** [comment]
@algorys 

1. Delete files under `data/cache/` (Be careful, or you can backup everything first)
2. Use incognito mode to visit DokuWiki again

**Comment by algorys** [comment]
@phy25 I've tried to do that, but it still the same (I've uninstall plugin, empty cache, etc...). 

It works under private mode but in normal mode not (always the same errors)! Strange behavior...

**Comment by algorys** [comment]
**Last solution:** I've uninstall / install Chrome and now things back to normal :smile: I think it's a Chrome side issue, the cache does not seem to empty as it should.

**Comment by tylermeuse** [comment]
I am experiencing the same issues as others such as @algorys have reported. None of the solutions aforementioned have worked for me, and it appears to be browser-agnostic, as I experience the same issue and console output on different browsers and devices.
