### ISSUE TITLE
Slow performance on main pages when template is enabled

### ISSUE THREAD

**Issue by swordfischer** [LotarProject/dokuwiki-template-bootstrap3#292]
### Description
I'm trying to align some internal websites to bootstrap, one of which is dokuwiki.
However, when I use this template the page rendering time goes from 0.5-1.5 seconds to 7-9 seconds.
I've tried disabling all plugins, and it can at best give me 1 second less of load time.

Accessing the root document (doku.php) is generally the slowest - other pages like admin is normal speed.

### Steps to Reproduce

1. Enable Bootstrap3 template

**Expected behavior:** Performance is somewhat the same as with other templates.

**Actual behavior:** Performance is sub par

### Versions

  * [Bootstrap3 Template] = 2016-12-12 and tried with latest version from git
  * [DokuWiki] = 2017-02-19 and tried with 2016-06-26a
  * [Plugin] = ?
  * [Browser] = Chrome 55, 56 and 57. Firefox 50, Internet Explorer 11 and Edge

### Screenshots or Logs

What kind of logs would be sufficient?

**Comment by LotarProject** [comment]
Hi @swordfischer,
you have particular option enabled ?
Example:
- ``useLocalBootswatch``
- ``useGravatar``
- ``useGoogleAnalytics``
- ``customTheme`` (external custom theme)

At your disposal,
Joseph

**Comment by swordfischer** [comment]
Hi @LotarProject 
Thanks for the quick reply.

useLocalBootswatch is enabled
useGravatar is disabled
useGoogleAnalytics is disabled
customTheme is empty

The load time is high on doku.php and not loading the other resources. However this extra delay is only present while the bootstrap theme is enabled :(

**Comment by LotarProject** [comment]
Hi @swordfischer,
can you specify all plugin installed on your DokuWiki ? (You can see the list in "Popularity Feedback" page).

Thanks!

At your disposal,
Joseph

**Comment by swordfischer** [comment]
@LotarProject, there are some improvement since last. The current load time is roughly 2 seconds with everything disabled and bootstrap theme active.

It seems that if I disable 'Add New Page' plugin https://github.com/samwilson/dokuwiki-plugin-addnewpage roughlty 1.5 seconds are cut from loading the page when bootstrap is enabled

```
anon_id	8b3ac5373d1e4b13d4996bfa821a4f41
version	Release 2017-02-19b "Frusterick Manners"
popversion	2015-07-15
language	en
now	1491213632
popauto	1
conf_useacl	1
conf_authtype	authad
conf_template	bootstrap3
page_count	651
page_size	1194143
page_biggest	38204
page_smallest	3
page_nscount	175
page_nsnest	8
page_avg	1834.3210445469
page_oldest	1235404292
media_count	592
media_size	137935992
media_biggest	15390231
media_smallest	178
media_nscount	106
media_nsnest	8
media_avg	232999.98648649
cache_count	16430
cache_size	207379309
cache_biggest	1082270
cache_smallest	0
cache_avg	12621.990809495
index_count	430
index_size	3715953
index_biggest	998563
index_smallest	1
index_avg	8641.7511627907
meta_count	5066
meta_size	3166988
meta_biggest	13343
meta_smallest	1
meta_avg	625.14567706277
attic_count	7054
attic_size	12761603
attic_biggest	94340
attic_smallest	0
attic_avg	1809.1299971647
attic_oldest	1234717983
user_count	1000
edits_per_day	3.509530253068
plugin	acl
plugin	authad
plugin	authplain
plugin	config
plugin	extension
plugin	popularity
plugin	usermanager
pcre_version	8.38 2015-11-23
pcre_backtrack	20971520
pcre_recursion	100000
os	WINNT
webserver	Microsoft-IIS/8.5
php_version	7.1.1
php_sapi	cgi-fcgi
php_memory	134217728
php_exectime	300
php_extension	Core
php_extension	bcmath
php_extension	calendar
php_extension	ctype
php_extension	date
php_extension	filter
php_extension	hash
php_extension	iconv
php_extension	json
php_extension	mcrypt
php_extension	SPL
php_extension	pcre
php_extension	readline
php_extension	Reflection
php_extension	session
php_extension	standard
php_extension	mysqlnd
php_extension	tokenizer
php_extension	zip
php_extension	zlib
php_extension	libxml
php_extension	dom
php_extension	PDO
php_extension	openssl
php_extension	SimpleXML
php_extension	xml
php_extension	wddx
php_extension	xmlreader
php_extension	xmlwriter
php_extension	cgi-fcgi
php_extension	mysqli
php_extension	mbstring
php_extension	gd
php_extension	gettext
php_extension	curl
php_extension	exif
php_extension	xmlrpc
php_extension	Phar
php_extension	soap
php_extension	pdo_mysql
php_extension	pdo_sqlite
php_extension	imap
php_extension	tidy
php_extension	wincache
php_extension	ldap

```

**Comment by swordfischer** [comment]
Actually, enabling plugin and setting tpl»bootstrap3»showAddNewPage to never, allows the site to load within a reasonable timeframe

**Comment by LotarProject** [comment]
Thanks!!!! You confirm my suspect!
I'm plan to create a lightweight version of **Add new page** component because in my internal tests **Add new Page Plugin** slow page time load.

At your disposal,
Joseph

**Comment by pirrimanson2000** [comment]
Same problem here. Is there the lightweight version available?

**Comment by takuy** [comment]
This is still an issue now. I removed the AddNewPage plugin entirely from my instance. Any ideas why this is so detrimental?

**Comment by giterlizzi** [comment]
> This is still an issue now. I removed the AddNewPage plugin entirely from my instance. Any ideas why this is so detrimental?

This AddNewPage plugin create a tree of all DokuWiki namespace to display via dropdown list. If you have lot of namespaces this slow down the performance if `showAddNewPage` option.
