### ISSUE TITLE
User tools dropdown not working

### ISSUE THREAD

**Issue by bernhardbrunner** [LotarProject/dokuwiki-template-bootstrap3#293]
### Description

Probably since upgrade to Release 2017-02-19a "Frusterick Manners", User Tools dropdown and other menus don't work anymore. 

### Steps to Reproduce

1. Install Release 2017-02-19a "Frusterick Manners"
2. Click on "User Tools" dropdown

**Expected behavior:** menu opens ;)

**Actual behavior:** nothing happens

 ### Fix
  * Changed theme to dokuwiki by editing conf/local.php directly
  * Tried to reinstall plugin => no effect
  * Removed and reinstall Template => fixed!

Because of the reinstall I don't have the old version number of the plugin. But I could recover the complete Template directory from last nights backup if needed.

### Versions

  * Release 2017-02-19a "Frusterick Manners"
  * Template version no longer available
  * Browser: IOS, Firefox 45.7.0 Linux

**Comment by phy25** [comment]
Duplicate of #291?

**Comment by bernhardbrunner** [comment]
Sounds like it. Thanks!
