### ISSUE TITLE
Footnotes in Frusteric Manners

### ISSUE THREAD

**Issue by sanctus17** [LotarProject/dokuwiki-template-bootstrap3#294]
### Description

After upgrading to Frusterick Manners, there now is a line break after every number in the footnotes section at the very end of the page.

### Steps to Reproduce

1. Create a footnote in a DokuWiki page. Syntax: `((footnote))`
2. Look at the bottom at the page.
3. It now displays:

```
1)
footnote
```

instead of:

`1) footnote`

### Versions

latest bootstrap3 template with latest DokuWiki Frusteric Manners, happens in every browser

**Comment by LotarProject** [comment]
Hi @sanctus17,
i have fixed this issue in master and develop branch.

At your disposal,
Joseph

**Comment by sanctus17** [comment]
Great, thank you!
