### ISSUE TITLE
Change color of background in "Template-Design" settings does not apply

### ISSUE THREAD

**Issue by igittigitt** [LotarProject/dokuwiki-template-bootstrap3#297]
### Description

Currently i use bootswatch.com theme "Cerulean". The background and page color is white but i want to have more contrast between them. So i want to have all page background to have an other color (unique grey) than the wikipage itself.

It seems that changes in the Temple-Design admin tool does not apply to bootswatch3 templates.

**Comment by LotarProject** [comment]
Duplicate of #238
