### ISSUE TITLE
Conflict with Bootstrapwrapper (tab pane)

### ISSUE THREAD

**Issue by legend2360** [LotarProject/dokuwiki-template-bootstrap3#299]
### Description
When using Tab Pane (http://www.lotar.altervista.org/dokuwiki/wiki/plugin/bootswrapper/nav) and enabled option showSemanticPopup, information in a popup is looks badly (contains entire page, not a content of pane/pane-id) and covers part (or wholly) of tab button.

### Steps to Reproduce
1. Enable option showSemanticPopup (before: install 'Semantic plugin')
2. Use tag <tabs> and inner <pane-id> on any page that don't include in the setting semantic»excludedPages
3. Check page

**Expected behavior:** Display _content of <tab pane-id...>above tab button_ or disable this feature for tab-panes

**Actual behavior:** (as in description...) content in the popup is looks badly (contains entire page, not a content of pane/pane-id) and covers part (or wholly) of tab button.

### Versions
  * Bootsrap3: v2016-12-12
  * DokuWiki: Release 2017-02-19b "Frusterick Manners"
  * Bootstrap Wrapper: 2016-04-14
  * Semantic: 2016-12-12
  * Vivaldi/Chrome/Ya.Browser

### Screenshots or Logs
![image](https://cloud.githubusercontent.com/assets/13462641/23990830/526d5802-0a48-11e7-947a-43657f62787d.png)
GIF(...): http://i.imgur.com/2UCPfxd.gifv (for some reason here popup can't close)

### Sample Page
—

**Comment by LotarProject** [comment]
Duplicate #281 #282
