### ISSUE TITLE
Enable the fluid container

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#30]
Hi Lotar,

suggestion for the option "Enable the fluid container (full-width of page)":
The idea of the named option is very good. So why is it only available from the admin panel? I don't know how much work this would be, but my proposal is to integrate it as a clickable button into the navbar so everyone can toggle it device-specific.

Best regards 
Juergen

**Comment by Juergen-aus-Koeln** [comment]
Hi Lotar,

thank you very much! Here are the first testing results:
- The new functionality works fine in Firefox, but not in Chrome and IE11
- There is no tool-tip for the new button
- I can't find out, if you have implemented a default value. If not, that would be a good supplement

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi!

  * in my develop env and in my live site (http://lotar.altervista.org/dokuwiki) works. After the installation i have purged all cache (browsers and DokuWiki)
  * the patch for tooltip, is coming in next commit (see my site)
  * i have provided a cookie to save the setting

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Ok, thank you!

The reason for the defective width was a parameter in the userstyle.conf to set the default width to 94%. Beg your pardon. I've deleted this entry, and everything works fine.

Best regards
Juergen

**Comment by LotarProject** [comment]
:+1:
