### ISSUE TITLE
How to get rid of social icons?

### ISSUE THREAD

**Issue by igittigitt** [LotarProject/dokuwiki-template-bootstrap3#300]
### Description

I'd like to remove the social share icons, as loaded in main.php at line 45 using:
`<?php tpl_includeFile('social.html') ?>`

Deleting the file will only help until next update of plugin, so i set it to zero content. But this is a very deep operation and i wish it could be configureable. Simply turn on/off would be sufficient.

**Comment by LotarProject** [comment]
Hi,
this hook is replaced with ``showPageIcons`` options since [v2016-02-29](https://github.com/LotarProject/dokuwiki-template-bootstrap3/releases/tag/v2016-02-29) release. This option include:
  * Share to link:
    * Facebook
    * Google+
    * LinkedIn
    * pinterest
    * WhatsApp
    * Twitter
    * Telegram
  * Feed
  * Send Mail
  * Print
  * Help popup hook

At your disposal,
Joseph

**Comment by igittigitt** [comment]
Strange. I use v2016-12-12 as available via Dokuwiki downloader and when i look into main.php i find at line 45 the above mentioned code:
`      <?php tpl_includeFile('social.html') ?>`
It has no condition.
