### ISSUE TITLE
Anyway to get an additional menu levels using Navbar?

### ISSUE THREAD

**Issue by briangig** [LotarProject/dokuwiki-template-bootstrap3#301]
I tried a few combos, but every time it seems to just break the drop down menu.  Any way to get additional levels?  Something like below?  I can only seems to get one level down working:

```
  *[[Books]]
    *[[Non-Fiction]]
      *[[Short-stories]]<--Doesn't work
      *[[Novels]]<--Doesn't work
    *[[Fiction]]
  *[[Movies]]
```

**Comment by LotarProject** [comment]
Hi, this is a complex request because Bootstrap theme have dropped this feature in 3.x release for preserve the usability in mobile and tablet devices.

Sorry!
