### ISSUE TITLE
User Dropdown Menu

### ISSUE THREAD

**Issue by mguitvlugt** [LotarProject/dokuwiki-template-bootstrap3#302]
### Description

When using a fixed navbar, the user dropdown menu is all the way to the right side of the browser window.

### Steps to Reproduce

1. Log in to my DokuWiki
2. Drop down user window (as if going to logout)

**Expected behavior:** [What you expected to happen]

I expected the drop down to be directly below the user icon like the tools drop down menu is. When the navbar is not fixed, the menu is directly below the icon as expected. See attached images.

**Actual behavior:** [What actually happened]

The drop down menu is justified with the right side of the screen.

### Versions

  * Bootstrap3: v2016-12-12
  * DokuWiki: 2017-02-19b "Frusterick Manners"
  * Browser: Chrome

### Screenshots or Logs

What I expect it to be like:
![notfixed](https://cloud.githubusercontent.com/assets/26818811/24553612/c203877a-15f8-11e7-896c-91803f65e41b.png)

What I see:
![fixednavbar](https://cloud.githubusercontent.com/assets/26818811/24553617/c66637b8-15f8-11e7-91c7-be1391d71f32.png)

**Comment by LotarProject** [comment]
Hi @mguitvlugt, this issue is fixed in my develop branch.

Thanks!
Joseph
