### ISSUE TITLE
Styling problem with Indexmenu plugin and sidebar

### ISSUE THREAD

**Issue by fjdiazt** [LotarProject/dokuwiki-template-bootstrap3#303]
### Description

I'm using release v2016-12-12 with Dokuwiki 2017-02-19b and when printing the [indexmenu ](https://www.dokuwiki.org/plugin:indexmenu )in the sidebar, the styling seem inconsistent (see screenshot)

### Versions

  * [Bootstrap3 Template] 2016-06-26a 
  * [DokuWiki]  2017-02-19b

### Screenshots or Logs
![indexmenu](https://cloud.githubusercontent.com/assets/14144777/24572922/15d81666-164b-11e7-9278-166350b3443b.JPG)

**Comment by LotarProject** [comment]
Hi @fjdiazt , recently the i have added a new tweaks for this plugin.

You can try again?

PS. Remember to add ``~~NOCACHE~~`` macro!

Thanks,
Joseph
