### ISSUE TITLE
How to hide entries in navbar, based on ACL

### ISSUE THREAD

**Issue by igittigitt** [LotarProject/dokuwiki-template-bootstrap3#305]
### Description

I'd like to hide a menugroup or specific menuitems in navbar, based von ACLs of user.

**Comment by molefunk** [comment]
I'm using a wrap around the menu items I want to hide to visitors. Eg. `<wrap hidevisitor>` and a small addition to conf/userstyle.css: `.wrap_hidevisitor {display: none;}`. Simple workaround. :)

**Comment by LotarProject** [comment]
This feature is more complex. In other DokuWiki installations i have used the include plugin.

Joseph
