### ISSUE TITLE
template Bootstrap3 not center anything (img and text)

### ISSUE THREAD

**Issue by eniodefarias** [LotarProject/dokuwiki-template-bootstrap3#307]
### Description

template Bootstrap3 not center anything

not center texts inside tables

and not center images

### Steps to Reproduce

example text:
|  text  |
> always aligment left

example image:
{{  :example:image.png  }}
> always aligment left

**Expected behavior:** [What you expected to happen]
centered text and image

**Actual behavior:** [What actually happened]
always aligment left

### Versions

  * [Bootstrap3 Template]
2016-12-12
Bootstrap3 Template de Giuseppe Di Terlizzi
superhero

  * [DokuWiki]
Release 2017-02-19a "Frusterick Manners"

  * [Plugin]
ACL Manager de Andreas Gohr
authpdo plugin de Andreas Gohr
Plain Auth Plugin de Andreas Gohr
Configuration Manager de Christopher Smith
Extension Manager de Michael Hamann
Info Plugin de Andreas Gohr
Popularity Feedback Plugin de Andreas Gohr
Revert Manager de Andreas Gohr
safefnrecode plugin de Andreas Gohr
styling plugin de Andreas Gohr
DokuWiki Template de Anika Henke
Testing Plugin de Tobias Sarnowski
User Manager de Chris Smith

  * [Browser]
firefox, chrome, ie, etc

### Screenshots or Logs
![image](https://cloud.githubusercontent.com/assets/18029282/25179052/a4d994c4-24de-11e7-97a5-e204ea31253a.png)
http://imgur.com/a/znVFd

### Sample Page
[Paste your sample DokuWiki page]
http://informefontespromotora.com.br/wiki/doku.php?id=playground:playground:teste

**Comment by eniodefarias** [comment]
any sugestions to fix it?

**Comment by LotarProject** [comment]
Hi,
i think you have a problem with your DokuWiki installation because the CSS is incomplete. I have forced the purge of your CSS cache via ``http://informefontespromotora.com.br/wiki/lib/exe/css.php?purge=true`` but this is the result:

```
<br />
<b>Fatal error</b>:  Allowed memory size of 26843546 bytes exhausted (tried to allocate 32 bytes) in <b>/home/informefontespromotora/www/wiki/inc/lessc.inc.php</b> on line <b>387</b><br />
```

I suggest to increase php ``memory_limit``.

At your disposal,
Joseph

**Comment by eniodefarias** [comment]
thank you.
its ok now!
