### ISSUE TITLE
Can't change logo image size with css.

### ISSUE THREAD

**Issue by Losiara** [LotarProject/dokuwiki-template-bootstrap3#308]
Is there "officcial" option to resize logo image?

**Comment by eniodefarias** [comment]
-1 create a file /wiki/estilo.css

-2 add lines  into /wiki/estilo.css
```
   #dw__logo{
   height: 50px !important;
   }
```

-3 edit **/wiki/lib/tpl/bootstrap3/main.php** and add line inside tag <head>
`<link type="text/css" rel="stylesheet" href="/wiki/estilo.css"/>`

example: 
<blockquote class="imgur-embed-pub" lang="en" data-id="a/sPyPW"><a href="//imgur.com/sPyPW"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

[](http://imgur.com/a/sPyPW)


-4 save and reload Ctrl+F5 the index page

**Comment by Losiara** [comment]
Thanks

**Comment by LotarProject** [comment]
Hi! I suggest to use ``userstyle.css`` (or ``userall.css``) in your ``/conf`` directory, because are **upgrade safe**.

It's possible to edit this file via [advanced plugin](https://www.dokuwiki.org/plugin:advanced).

At your disposal,
Joseph

**Comment by graham-macleod** [comment]
I too am keen to achieve a larger logo, however adding this will increase the size of the logo, but not the size of the container, so there is a lot of overlap.
