### ISSUE TITLE
Error displaying differences

### ISSUE THREAD

**Issue by sanctus17** [LotarProject/dokuwiki-template-bootstrap3#309]
### Description

There seems to be a bug when comparing different versions of a page, p.e. current version with an old revision. The edited text doesn't display because text and background have the same color (red or green).

### Steps to Reproduce

1. Open a dokuwiki page
2. click on 'old revisions'
3. select two versions and click 'show differences between selected revisions'

**Expected behavior:** Changes can be compared side to side.

**Actual behavior:** Only green / red blocks appear, the text seems to be hidden inside the same colored boxes. Manual selection if the text will reveal it by temporarily adjusting the background color (see attached screenshots).

### Versions

  * latest Bootstrap3 template
  * Dokuwiki Release 2017-02-19b "Frusterick Manners"
  * Safari but same happens in Chrome and Firefox

### Screenshots or Logs

![scrshot01](https://cloud.githubusercontent.com/assets/20143159/25575508/5d89ff4a-2e58-11e7-9e19-c0b2fd2643ab.jpg)

![scrshot02](https://cloud.githubusercontent.com/assets/20143159/25575512/6247e3bc-2e58-11e7-9a03-a8fa628f81b2.jpg)

Thank you!

**Comment by phy25** [comment]
What Bootswatch varient are you using?

I have found before, that in some Bootswatch version, colors of `.text-**` and `.bg-**` are the same, causing this issue.

**Comment by sanctus17** [comment]
Thank you for your comment.

It is the Lumen theme and Bootswatch.com Design.
Indeed, when switching to Vanilla Bootstrap Design, the issue resolves. That is a total different theme, though.

**Comment by CvH** [comment]
this is fixed with https://github.com/LotarProject/dokuwiki-template-bootstrap3/pull/265

**Comment by LotarProject** [comment]
The PR #265 is merged into code! Thanks!

**Comment by ariasuni** [comment]
It’s still too hard to read black on red or green with Lumen theme, it should use white like on [Cards on Lumen page](https://bootswatch.com/lumen/). I’m not sure how and where to fix this though.
