### ISSUE TITLE
Layout for printing

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#32]
Hi Joseph,

when printing a page the whole sidebar is included in the output. 

Regards
Juergen

**Comment by LotarProject** [comment]
Hi! Fixed the issue in commit 86963dd

Best regards
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you, the layout now looks quite good.

But I've found a detail that doesn't work at the moment. It depends on processing of some plugins. See the following wiki code as example form the data plugin:
```
---- datatable ----
cols    : Anrede, %pageid%, Abteilung_person-abt, Telefon, Mobil
filter  : %pageid%~personal:personalstammdaten:*
----
```
When printing the result is something like that:
![schuemmer-2015-05-20 09_06_51-clipboard](https://cloud.githubusercontent.com/assets/1800472/7720619/bfb732ba-fecf-11e4-94ea-6d3cc8703006.png)
The same happens with the plugins chages and top.

Best regards
Juergen

**Comment by Juergen-aus-Koeln** [comment]
The same happens everywhere, where a link is replaced by its header, when the parameter useheading is turned on.

Rergards
Juergen

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, that's the solution.
Is it planned to update the download package for the template on github / dokuwiki?

**Comment by LotarProject** [comment]
Hi, The package is ready on GitHub, DokuWiki and extension manager.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, now it works perfectly
