### ISSUE TITLE
Pagehead clipped on mobile if header if more than one line

### ISSUE THREAD

**Issue by igittigitt** [LotarProject/dokuwiki-template-bootstrap3#320]
### Description

As long as the header fits into a single line, everything is fine. But i used navheader page to add some buttons. In mobile view the header expands to two lines. This header overlap with page content (youarehere and breadcrumbs are no longer visible). It is not possible to scroll this out, because page flips back as soon as released.

You can see this here http://mk4-wiki.denkdose.de/grundlagen/can_analyzer/start

**Comment by igittigitt** [comment]
Because picture are more than words, here you are:

First, if browser is wide enough (Desktop-PC), everything is ok:
![fixed_navbar_ok](https://user-images.githubusercontent.com/909922/28918081-4619df12-7848-11e7-8158-375703a41928.png)

On a smaller device, like a Tablet, the header suddenly overlap parts of page navigation, because the header breaks into two lines:
![fixed_navbar_overlapped](https://user-images.githubusercontent.com/909922/28918148-84f85be6-7848-11e7-935d-6c018874d30d.png)

If access from a smartphone the header elements are grouped into a single button, and the page navigation is accessible again:
![fixed_navbar_compressed](https://user-images.githubusercontent.com/909922/28918184-a44e014e-7848-11e7-8a8f-9f34fb1ea6b8.png)

Funny. So it's just a matter of width. If the CSS was able to group instead of doing a "line break" in header, everything would work fine.

**Comment by phy25** [comment]
The overflow is because your navbar is too long, and it is actually an upstream issue. You can try reducing the width.
Ref: <http://getbootstrap.com/components/#callout-navbar-overflow>

**Comment by igittigitt** [comment]
Good hint! I think "c) Change the point at which your navbar switches between collapsed and horizontal mode. Customize the @grid-float-breakpoint variable or add your own media query." is what i'm looking for. I found that this breakpoint is set to 768px in width. To make it work, it should not switch to horizontal view if screenwidth is under 1280 pixels.
Unfortunately i cannot find the mentioned parameter "@grid-float-breakpoint" anywhere in the plugin-code.

**Comment by zicklag** [comment]
I'm having this issues as well, when I try to add menu entries using the `:navbar` hook.

**Comment by LotarProject** [comment]
This is a old and famous Bootstrap bug. I suggest to reduce the elements in navbar.
