### ISSUE TITLE
Integration with Faster DokuWiki Plugin?

### ISSUE THREAD

**Issue by lifehome** [LotarProject/dokuwiki-template-bootstrap3#322]
### Description
It seems the "Faster DokuWiki Plugin" provides an inline-replacement for all pageload requests, speeds up page reload and offer more features in performance-wise optimization. Will there be integration of such plugin?

### Plugin Page
https://www.dokuwiki.org/plugin:fastwiki

**Comment by LotarProject** [comment]
This plugin work fine with latest release of template
