### ISSUE TITLE
[Feature Request] Copyright information config

### ISSUE THREAD

**Issue by zicklag** [LotarProject/dokuwiki-template-bootstrap3#323]
### Description

It would be nice if there was a configurable copyright for the material in the wiki. It should probably render next to the license information in the footer.

**Comment by LotarProject** [comment]
Hi, 
you can add this information into `:footer` hook.

**Comment by zicklag** [comment]
@LotarProject, thank you for responding.

What exactly is a `:footer` hook, I'm pretty new to DokuWiki. Are you referring to [include hooks](https://www.dokuwiki.org/include_hooks)? I didn't know they existed until I did a search just now. That looks like it will work, just wondering if I'm missing something.

**Comment by LotarProject** [comment]
Yes, Bootstrap3 template use the default DokuWiki hooks mechanism. The complete list of Bootstrap3 hooks (wiki or html) see https://www.dokuwiki.org/template:bootstrap3#available_hooks

**Comment by zicklag** [comment]
Thank you! Very nice. :smiley: 

I didn't realize that you could just create a `:footer` page in the wiki. just like you could create a `:sidebar` page. ( It took me too long to find out what the `:` was :wink: ).
