### ISSUE TITLE
Edit shortcut (accesskey="e") not usable in default config in Firefox 55

### ISSUE THREAD

**Issue by dedeibel** [LotarProject/dokuwiki-template-bootstrap3#325]
### Description

The edit shortcut (``accesskey="e"``) is not usable using the default config of the bootstrap template in Firefox 55. It is present but is not executed, because it's definition is present multiple times.

### Steps to Reproduce

1. Configure the ``showPageTools`` to be always visible _(default)_
2. Configure ``showTools`` (in navbar) to always _(default)_
3. Make sure ``showIndividualTool`` contains ``page`` _(default)_
3. Visit an editable page using firefox (I am using 55)
4. Try to use the edit shortcut ``Alt+Shift+e`` **not working**
5. Compare using ``Alt+Shift+f`` to enter the search bar. Note that firefox apparently allows to reconfigure meta keys under about:config.

**Expected behavior:**

Just like in the default layout the page edit dialog opens.

The function of the shortcuts should not be tied to the presence or amount of buttons on the page. Maybe they should be added as hidden elements and maybe controlled by their own config setting.

Apparently firefox does not execute the command if multiple ``accesskey`` declarations are present.

**Actual behavior:**

Nothing happens

**Workaround:**

Remove ``page`` from the ``showIndividualTool`` setting.

More general: disable all but one "edit" button on the page. For example just the navbar menu. But there is another problem: if you disable all edit buttons the shortcut will stop to function too.

### Versions

  * bootstrap3-v2016-12-12-32-gfef63cb
  * Release 2017-02-19e "Frusterick Manners"
  * Firefox 55 Linux

**Comment by LotarProject** [comment]
Hi @dedeibel, this issue is fixed. Thanks for your detailed description!

At your disposal,
Joseph

**Comment by dedeibel** [comment]
I have got to thank you :) thx
