### ISSUE TITLE
How to use taggging plugin with bootstrap3?

### ISSUE THREAD

**Issue by nelbs** [LotarProject/dokuwiki-template-bootstrap3#326]
I have installed the plugin tagging but how do I use it with the bootstrap3 template? I don't see an element like a pull down menu where i can add some tags? 

thanks in advance!

**Comment by LotarProject** [comment]
Hi, tagging plugin is supported by Bootstrap3 template. You can add the plugin in the page (or sidebar) using this syntax:

```
{{tagging::input}}
```
I suggests to add `~~NOCACHE~~` syntax to prevent page cache.

At your disposal,
Joseph

**Comment by nelbs** [comment]
Thanks for your answer!
I add the code in a certain page but nothing happended when I add a tag. See the screens below


![image](https://user-images.githubusercontent.com/6464671/30738843-ada87f98-9f8b-11e7-87a4-e3f34166dd76.png)

![image](https://user-images.githubusercontent.com/6464671/30738861-ba052d40-9f8b-11e7-88be-ef5055912db0.png)

![image](https://user-images.githubusercontent.com/6464671/30738883-caae1792-9f8b-11e7-8148-35bacdea82c3.png)

**Comment by LotarProject** [comment]
This issue is fixed in upcoming release of template.
