### ISSUE TITLE
Profile and Tools drop-down menu do not appear

### ISSUE THREAD

**Issue by LouisOuellet** [LotarProject/dokuwiki-template-bootstrap3#327]
### Description

After a new installation of the dokuwiki turnkey container on debian, I have installed the bootstrap3 template and all the supported plugins. After applying the template, the tools and profile drop down in the top navigation menu do not seem to open.

### Steps to Reproduce

1. Fresh install of turnkey dokuwiki container on debian
2. Install the bootstrap3 template
3. install all the supported plugins (tested without this step, and the same issue was still there)
4. Apply the bootstrap3 template

**Expected behavior:**
The drop down menus to open

**Actual behavior:** 
No drop down menu.

### Versions

  * [Bootstrap3 Template] vanilla theme
  * [DokuWiki] on internal network
  * [Plugin] all supported ones from the bootstrap template page
  * [Browser] : Firefox and chrome

**Comment by LouisOuellet** [comment]
Maybe I need to install some missing packages. Do you have a list of requirements ?

**Comment by phy25** [comment]
Actually no. You can check the console in the Web Developer in the browser (press F12), to see whether there are errors.

**Comment by LouisOuellet** [comment]
I have this in my console


          SyntaxError: invalid increment/decrement operand  js.php:26:274463
Error: Bootstrap's JavaScript requires jQuery  bootstrap.min.js:6:37
	<anonymous> http://wiki.laswitchtech.com/lib/tpl/bootstrap3/assets/bootstrap/js/bootstrap.min.js:6:37
ReferenceError: jQuery is not defined[Learn More]  start:33:14
	<anonymous> http://wiki.laswitchtech.com/start:33:14

**Comment by phy25** [comment]
Seems that jQuery is not properly loaded (should be bundled in DokuWiki). Please check whether `/lib/scripts/jquery/jquery.min.js?ver=3.1.1` is available.

**Comment by LouisOuellet** [comment]
It seems to be missing. I will redownload dokuwiki copy the file and let you know the result

**Comment by LouisOuellet** [comment]
Alright this fixed the issue for me:
logged in as root on my turnkey linux container then
wget https://download.dokuwiki.org/out/dokuwiki-c5525093cf2c4f47e2e5d2439fe13964.tgz
tar -xvzf dokuwiki-c5525093cf2c4f47e2e5d2439fe13964.tgz
cp -vR dokuwiki/ /usr/share/
shutdown -r 0

Probleme solved. Thanks for the help phy25

**Comment by LouisOuellet** [comment]
Never mind, after my copy command, some pages were overwritten and I lost the content of pages such as the admin page.

After a fresh installed again, I sent basically the same commands in the server
wget https://download.dokuwiki.org/out/dokuwiki-c5525093cf2c4f47e2e5d2439fe13964.tgz
tar -xvzf dokuwiki-c5525093cf2c4f47e2e5d2439fe13964.tgz
cp -n -vR dokuwiki/ /usr/share/
shutdown -r 0

but I added -n to the cp command. but now i am getting this as an error:
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4  bootstrap.min.js:6:216

**Comment by LouisOuellet** [comment]
Also the result of http://wiki.laswitchtech.com/lib/scripts/jquery/jquery.min.js?ver=3.1.1 after the freshinstall does output
/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */

**Comment by LouisOuellet** [comment]
lastest info I dug:

root@wiki ~# cat /usr/share/dokuwiki/lib/scripts/jquery/versions
# this is loaded from the update.sh script and our PHP code
JQ_VERSION=3.1.1
JQUI_VERSION=1.12.1
JQM_VERSION=3.0.0
root@wiki ~# sh /usr/share/dokuwiki/lib/scripts/jquery/update.sh
/usr/share/dokuwiki/lib/scripts/jquery/update.sh: 12: /usr/share/dokuwiki/lib/scripts/jquery/update.sh: source: not found
https://code.jquery.com/jquery-.min.js:
2017-09-22 00:55:01 ERROR 404: Not Found.
https://code.jquery.com/ui//jquery-ui.min.js:
2017-09-22 00:55:01 ERROR 404: Not Found.
https://code.jquery.com/jquery-migrate-.min.js:
2017-09-22 00:55:02 ERROR 404: Not Found.
/usr/share/dokuwiki/lib/scripts/jquery/update.sh: 1: /usr/share/dokuwiki/lib/scripts/jquery/update.sh: gawk: not found
../../../inc/lang/*/jquery.ui.datepicker.js: No such file or directory
../../../inc/lang/de-informal/jquery.ui.datepicker.js: No such file or directory
../../../inc/lang/pt-br/jquery.ui.datepicker.js: No such file or directory
../../../inc/lang/zh/jquery.ui.datepicker.js: No such file or directory
../../../inc/lang/zh-tw/jquery.ui.datepicker.js: No such file or directory
../../../inc/lang/cy/jquery.ui.datepicker.js: No such file or directory

**Comment by LotarProject** [comment]
Hi, @LouisOuellet,
i suggest to execute the script `update.sh` into the directory:

```
cd /usr/share/dokuwiki/lib/scripts/jquery
sh update.sh
```
After jQuery update, clear your browser cache and `touch` your `conf/local.php` file.

At your disposal,
Joseph

**Comment by LouisOuellet** [comment]
@LotarProject 
I reran the update.sh file from within the jquery directory but got does results : 

update.sh: 12: update.sh: source: not found
https://code.jquery.com/jquery-.min.js:
2017-09-22 19:36:07 ERROR 404: Not Found.
https://code.jquery.com/ui//jquery-ui.min.js:
2017-09-22 19:36:07 ERROR 404: Not Found.
https://code.jquery.com/jquery-migrate-.min.js:
2017-09-22 19:36:08 ERROR 404: Not Found.
update.sh: 1: update.sh: gawk: not found
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-af.js:
2017-09-22 19:36:08 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ar.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-az.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-bg.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-bn.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ca.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ca-valencia.js:
2017-09-22 19:36:09 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-cs.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-cy.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-da.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-de.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-de-informal.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-el.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-en.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-eo.js:
2017-09-22 19:36:10 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-es.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-et.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-eu.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-fa.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-fi.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-fo.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-fr.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-gl.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-he.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-hi.js:
2017-09-22 19:36:11 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-hr.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-hu.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-hu-formal.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ia.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-id.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-id-ni.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-is.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-it.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ja.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ka.js:
2017-09-22 19:36:12 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-kk.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-km.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ko.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ku.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-la.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-lb.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-lt.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-lv.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-mg.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-mk.js:
2017-09-22 19:36:13 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ml.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-mr.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ms.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ne.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-nl.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-no.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-pl.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-pt.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-pt-br.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ro.js:
2017-09-22 19:36:14 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ru.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-sk.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-sl.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-sq.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-sr.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-sv.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-ta.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-th.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-tr.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-uk.js:
2017-09-22 19:36:15 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-vi.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-zh.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-zh-tw.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-de.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-pt-BR.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-zh-CN.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-zh-TW.js:
2017-09-22 19:36:16 ERROR 404: Not Found.
https://raw.githubusercontent.com/jquery/jquery-ui//ui/i18n/datepicker-cy-GB.js:
2017-09-22 19:36:16 ERROR 404: Not Found.

it seems I am missing some files even though I imported all the missing files from the original dokuwiki download.

I still went and cleared my browser cache again and also purge js and css for good mesure. finally I also ran touch on my conf/local.php file.

yet I get the same results. this is getting exausting. I am not sure whats wrong with my setup. as mentioned before, I am running a turnkey linux container for this running on debian. and the host hypervisor is kvm running with proxmox. Not sure if that helps.

The only time I managed to prevent these error was by overwritting all the files in the dokuwiki directory. Thus I am thinking that it might be a problem with the file that actually runs the jquery library. Do you have any pointer as to which file it would be. I would overwrite this file only. I do not want to overwrite the entire directories because the last time I lost access to some crucial pages such as the admin page.

**Comment by LouisOuellet** [comment]
Alright so the only solution that worked for me was to remove the TurnKey Linux DokuWiki Stack and to install a TurnKey Linux LAMP Stack and configure a freshly downloaded dokuwiki. I have put the site online if anyone wants to see the complete details of my process.

Site : https://wiki.laswitchtech.com/doku.php?id=how-to:how-to-setup-dokuwiki-on-turnkey-linux
