### ISSUE TITLE
Tables are bad displayed in Boodstrap3

### ISSUE THREAD

**Issue by waldauf** [LotarProject/dokuwiki-template-bootstrap3#328]
### Description

I installed Bootstrap3 template which has problem with table displaying. 

### Steps to Reproduce

1. Install last version of DW
2. Install Bootstrap3 template and switch to
3. Create some table

**Expected behavior:** 
This is how I see table in dokuwiki template:
![dokuwiki_dokuwiki](https://user-images.githubusercontent.com/24603883/30927749-c58b9c4e-a3b9-11e7-971d-e885be0a0d13.png)

**Actual behavior:**
This is how I see table in bootstrap3 template:
![dokuwiki_bootstrap3](https://user-images.githubusercontent.com/24603883/30927743-c1a00c8c-a3b9-11e7-9abd-eefab19e0d9a.png)

### Versions

  * [Bootstrap3 Template] - Last updated on 2016-12-12
  * [DokuWiki] - Release 2017-02-19e "Frusterick Manners"
  * [Plugin] - 
  * [Browser] - Chromium Version 61.0.3163.91

**Comment by LotarProject** [comment]
Hi @waldauf, this is the default behavior of Bootstrap but exist an option to set 100% full width for all tables (`tableFullWidth`). You can set this option in Configuration Manager.

Joseph

**Comment by waldauf** [comment]
I can set ''tableFullWidth'', but there are missing lines between columns. If you have table with more columns and in columns are words splitted by space, it is confused to recognize where is one column is ending and next is beginning:

- Bootstrap3 template
![screenshot_20171001_104719](https://user-images.githubusercontent.com/24603883/31053092-ce27b908-a695-11e7-9273-fedb7047bb32.png)

- DokuWiki template
![screenshot_20171001_104506](https://user-images.githubusercontent.com/24603883/31053081-9b513bc6-a695-11e7-9c7a-eb4ad32a3e9a.png)

That is my point what I want to show you. :]

**Comment by phy25** [comment]
@waldauf In `tableStyle` of the configuration, you can turn on `bordered`. The table without border is the default in Bootstrap: https://getbootstrap.com/docs/3.3/css/#tables

**Comment by waldauf** [comment]
Aha... that I didn't know. Thanks for that. ;]

**Comment by waldauf** [comment]
Can I ask you for help how to set this table borders by default in DW? 

I tried to set HTMLlok, and it works when I put it into HTML tags. But this is not clear way.

**Comment by waldauf** [comment]
I overlooked tableStyle setting in configuration. Now it works like charm.
