### ISSUE TITLE
Adding regular links to other site in :navbar

### ISSUE THREAD

**Issue by LouisOuellet** [LotarProject/dokuwiki-template-bootstrap3#329]
### Description

I looked around, and I could not find any documentation on adding links to external sites in the navbar as a button. I would like to add additional buttons on my dokuwiki navbar that would point to external sites.

https://wiki.laswitchtech.com

**Comment by LouisOuellet** [comment]
Yeah well never mind. I actually found my anwser on https://www.dokuwiki.org/link. I feel bad for asking now ..

**Comment by LotarProject** [comment]
Hi,
add external website in navbar is easy because the ``:navbar`` hook use the same DokuWiki syntax.

:)
