### ISSUE TITLE
Plugin publish

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#33]
Hi Joseph,

another little flaw is the concurrence with the publish plugin. If it is activated for a page the message box (draft or approved) is displayed below the toc. In other templates it is placed at top of the page.

Regards
Juergen

**Comment by LotarProject** [comment]
Hi! I have added the initial support for Publish Plugin.

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you, it looks quite good. 

One thing could be optimized: When I load a page initially the message box is generated below the toc, and then it is replaced by the new message box. When the system has a good performance its no problem, but this is not always guaranteed.

Best regards,
Juergen

**Comment by LotarProject** [comment]
Hi. The template move on-the-fly the box from below to above of toc. I'm to work to find an elegant solution.

Best regards,
Joseph
