### ISSUE TITLE
Extended Table Syntax 3 Plugin broken

### ISSUE THREAD

**Issue by albeus** [LotarProject/dokuwiki-template-bootstrap3#330]
### Description

Tables elements seems not taken into account. For example bulletted lists.

### Steps to Reproduce

1. install [Extended Table Syntax 3 Plugin](https://www.dokuwiki.org/plugin:exttab3)
2. create a table containing a cell with a bulletted list (see sample code below)

**Expected behavior:** the cell should contain formatted dotted list

**Actual behavior:** the dotted list appears as normal unformatted text

### Versions

  * Bootstrap3 Template: v2016-12-12
  * DokuWiki: 2017-02-19e "Frusterick Manners"
  * Plugin: [Extended Table Syntax 3 Plugin](https://www.dokuwiki.org/plugin:exttab3) 2016-06-19
  * Browser: Firefox 55.0.2 (64-bit)

### Screenshots or Logs

See "Sample Page" in next paragaph for source code related to following rendered table.

![screenshot_2017-10-14_14-46-08](https://user-images.githubusercontent.com/2544953/31575783-7ec5c70c-b0ee-11e7-9f7b-e60f758ff7b2.png)

### Sample Page

```
{|
 !style="vertical-align:middle"| Row1
 | 

  * item1
  * item2
  * item3

 |-
 !style="vertical-align:middle"| Row2
 |

  * item1
    * subitem1
  * item2

|}
```

**Comment by LotarProject** [comment]
This plugin seems work with template.

Thanks,
Joseph
