### ISSUE TITLE
How to add a new theme

### ISSUE THREAD

**Issue by Antsypc** [LotarProject/dokuwiki-template-bootstrap3#334]
I wanted to add materia theme from bootswatch.com, so I downloaded materia them css file to my site content, while it was not working well.

What is the right operation for a new theme added from bootswatch.com. 

THANKS.

**Comment by LotarProject** [comment]
Hi,
Materia seems a new version of Paper theme, and is tuned for Bootstrap v4 (actually in beta) and my template is tuned for Bootstrap v3.

The template support loading of external/customized themes (via Configuration Manager) but Bootstrap v4 have more incompatibility issues with Bootstrap v3 (http://getbootstrap.com/docs/4.0/migration/#by-component).

At your disposal,

**Comment by Antsypc** [comment]
Thanks, I got your point.
