### ISSUE TITLE
Feature Request : add function to add new templates downloaded from https://bootswatch.com/

### ISSUE THREAD

**Issue by veenone** [LotarProject/dokuwiki-template-bootstrap3#335]
### Description

Please add a function to add new theme from https://bootswatch.com/ which is not yet installed in DokuWiki (i.e: pulse). so more themes can be chosen from the config

**Comment by phy25** [comment]
There's a `tpl:bootstrap3:customTheme` config. Are there other usages that this config cannot fulfill?

**Comment by veenone** [comment]
the problem is when the wiki site is localized and no connection to the internet as in my case, providing url is not possible,
so ability to import pre downloaded theme would be nice

**Comment by phy25** [comment]
You can just install the theme yourself under `lib\tpl\bootstrap3\assets\bootstrap\` and use that URL in `tpl:bootstrap3:customTheme` . I don't think this feature should be that accessible at the front-end.

**Comment by LotarProject** [comment]
I suggest placing the theme in other location outside ``lib/tpl/bootstrap3`` directory because is not upgrade safe.
