### ISSUE TITLE
inline TOC throwing errors in my logs

### ISSUE THREAD

**Issue by striderr** [LotarProject/dokuwiki-template-bootstrap3#339]
### Description
php 7.0, php-fpm
latest dokuwiki and bootstrap 3 theme

http error.logs throwing this stuff every few seconds.

2017/11/30 08:17:44 [error] 2431#0: *44236 FastCGI sent in stderr: "PHP message: PHP Warning:  Declaration of action_plugin_inlinetoc::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller)

Turns out the inline TOC is no longer supported and probably doesn't have support for php7.0.

TOC is working but I'm getting a ton of errors.  Is there any plans to replace the inlineTOC with something that is currently supported?

Is there a workaround that utilizes php7+ ?

**Comment by LotarProject** [comment]
Hi, seems a method signature mismatch problem of InlineTOC Plugin. Since PHP 7.0 this problem is notified with `E_WARNING` error level.

I think you can change this line in InlineTOC `action.php` file from:

```.php
function register(&$controller) {
        $controller->register_hook('RENDERER_CONTENT_POSTPROCESS', 'AFTER', $this, 'handle_renderer_content_postprocess', array());
        $controller->register_hook('TPL_METAHEADER_OUTPUT', 'BEFORE', $this, 'handle_tpl_metaheader_output', array());
    }
```

to

```.php
public function register(Doku_Event_Handler $controller) {
        $controller->register_hook('RENDERER_CONTENT_POSTPROCESS', 'AFTER', $this, 'handle_renderer_content_postprocess', array());
        $controller->register_hook('TPL_METAHEADER_OUTPUT', 'BEFORE', $this, 'handle_tpl_metaheader_output', array());
    }
```
This solution works with my other DokuWiki plugins!

At your disposal,
Joseph

**Comment by striderr** [comment]
I made the change but it broke the site, just a white page, I did restarted the web server and php-fpm service

error.log filled up with a bunch of repeating stuff but the good stuff.

 thrown in /path.../www/inc/events.php on line 211" while reading response header from upstream, client: x.x.x.x, server: www.domain.com<http://www.domain.com>, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "www.domain.com<http://www.domain.com>"
2017/12/02 18:45:44 [error] 5629#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method action_plugin_inlinetoc::handle_tpl_metaheader_output() in /www/inc/events.php:211
Stack trace:

events.php file at line 211 shows this.

    function process_event($event,$advise='') {

        $evt_name = $event->name . ($advise ? '_'.$advise : '_BEFORE');

        if (!empty($this->_hooks[$evt_name])) {
            foreach ($this->_hooks[$evt_name] as $sequenced_hooks) {
                foreach ($sequenced_hooks as $hook) {
                    list($obj, $method, $param) = $hook;

                    if (is_null($obj)) {
                        $method($event, $param);
                    } else {
211                        $obj->$method($event, $param);


On Dec 2, 2017, at 10:24 AM, Giuseppe Di Terlizzi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, seems a method signature mismatch problem of InlineTOC Plugin. Since PHP 7.0 this problem is notified with E_WARNING error level.

I think you can change this line in InlineTOC action.php file from:

function register(&$controller) {
        $controller->register_hook('RENDERER_CONTENT_POSTPROCESS', 'AFTER', $this, 'handle_renderer_content_postprocess', array());
        $controller->register_hook('TPL_METAHEADER_OUTPUT', 'BEFORE', $this, 'handle_tpl_metaheader_output', array());
    }

to

public function register(Doku_Event_Handler $controller) {
        $controller->register_hook('RENDERER_CONTENT_POSTPROCESS', 'AFTER', $this, 'handle_renderer_content_postprocess', array());
        $controller->register_hook('TPL_METAHEADER_OUTPUT', 'BEFORE', $this, 'handle_tpl_metaheader_output', array());
    }

This solution works with my other DokuWiki plugins!

At your disposal,
Joseph

**Comment by LotarProject** [comment]
I think seems this is a inlinetoc issue
