### ISSUE TITLE
Impossible to use the comparison between versions of a page

### ISSUE THREAD

**Issue by diegoscl** [LotarProject/dokuwiki-template-bootstrap3#340]
### Description

When you viewed a comparison between versions of the same page, the text has the same background color as the container, so it can not be read. Only 2 red and green boxes appear.

### Steps to Reproduce

1. Install the theme.
2. See a comparison of versions of a specific page.

**Expected behavior:** The text should be white to make it readable.

### Versions

  * Bootstrap3 2016-12-12
  * DokuWiki 2017-02-19e "Frusterick Manners"
  * Firefox, Safari, Chrome.

### Screenshots or Logs

![Screenshot](https://screenshots.firefoxusercontent.com/images/49cc667e-16af-464b-b81e-549c8f08404f.png)

**Comment by LotarProject** [comment]
Hi, this bug was fixed with this PR #265. 
You can reinstall again the template ?

At your disposal,
Joseph
