### ISSUE TITLE
Navbar links not working with Purplenumbers (render) plugin

### ISSUE THREAD

**Issue by molefunk** [LotarProject/dokuwiki-template-bootstrap3#342]
I think I said most of it in the title. My links in the navbar goes all strange when I'm using the renderer of Purplenumbers plugin. This functionality is crucial to me, as I'm using it as a way to index and jump to paragraphs across pages, but I have turned it off for now. Please let me know if more info needed!

**Comment by LotarProject** [comment]
Hi, thanks for reporting this issue.

Can you send a snippet of navbar to replicate this issue in my dev environment?

At your disposal,
Joseph

**Comment by molefunk** [comment]
Thanks for looking into this. Here is my navbar for good measure:

```
~~NOCACHE~~

  * {{icon>university}} <wrap hide-sm>Library</wrap>
    * (nbsp) <wrap lo>His Divine Grace</wrap>
    * {{icon>book}} [[books|Books by]]
    * {{icon>microphone?padding=1px}} [[spoken|Spoken by]]
    * {{icon>envelope}} [[letters|Letters from]]
    * {{icon>archive}} [[essays|Earlier essays]]
    * {{icon>newspaper-o}} [[btg|BTG magazine]]
    * {{icon>legal}} [[legal|Legal documents]]

  * {{icon>search}} <wrap hide-sm>Lookup</wrap>
    * {{icon>sort-alpha-asc}} [[Glossary|Glossary]]
    * {{icon>list-alt}} [[synonyms|Synonyms]]
    * {{icon>globe}} [[wiki|Wiki Articles]]
    * {{icon>paperclip?padding=1px}} [[index|General Index]]

  * {{icon>image}} <wrap hide-sm>Media</wrap>
    * {{icon>image}} [[gallery|Photo Gallery]]
    * {{icon>film}} [[video|Video Footage]]
```

**Comment by LotarProject** [comment]
Hi @molefunk, i have fixed this issue in develop (the next release of template) and in master (current release of template) branch.

At your disposal,
Joseph
