### ISSUE TITLE
fluid container and navbar-right behaviour

### ISSUE THREAD

**Issue by ggieling** [LotarProject/dokuwiki-template-bootstrap3#343]
### Description

Navbar-right DIV does not return to its original position when container is returned to smaller size after having been expanded to full width by pressing the fluid container button.

### Steps to Reproduce

1. Press fluid container button to expand to full screen view
2. Press fluid container button again to return to standard view
3. Reloading the page returns the navbar-right div to its original position 

**Expected behavior:** I expected the navbar-right div to remain in the same position relative to the navbar

**Actual behavior:** the navbar-right div sticks partly out of the navbar

### Versions

  * Bootstrap3 Template: 2016-12-12
  * DokuWiki: 2017-02-19 "Frusterick Manners"
  * Currently installed plugins (I have not yet had time to test this in a bare minimum install):
    * [https://www.dokuwiki.org/plugin:advanced]
    * [https://www.dokuwiki.org/plugin:bootswrapper]
    * [https://www.dokuwiki.org/plugin:include]
    * [https://www.dokuwiki.org/plugin:move]
    * [https://www.dokuwiki.org/plugin:passpolicy]
    * [http://www.dokuwiki.org/plugin:phpwikify]
    * [https://www.dokuwiki.org/plugin:securelogin]
    * [https://www.dokuwiki.org/plugin:simplenavi]
    * [https://www.dokuwiki.org/plugin:tablelayout]
    * [https://www.dokuwiki.org/plugin:tplmod]
    * [https://www.dokuwiki.org/plugin:translation]
    * [https://www.dokuwiki.org/plugin:wrap]
  * Tested in the following browsers:
    * Firefox 58.0.1 (32-bit) (windows 7)
    * Google Chrome 63.0.3239.132 (Official Build) (32-bit) (windows 7)
    * Firefox 57.0.4 (64-bit) (Arch Linux)
    * Firefox 58.0.1-1 (64-bit) (Arch Linux)
    * Chromium 63.0.3239.132 (Developer Build) (64 bit) (Arch Linux)
    * Chromium 64.0.3282.119-1 (Developer Build) (64 bit) (Arch Linux)

### Screenshots or Logs
Original condensed situation and expanded situation
![fluid1](https://user-images.githubusercontent.com/35794614/35614085-2fdfdfbc-066e-11e8-910e-b7c42851e983.png)
situation after returning to condensed (standard) situation
![fluid2](https://user-images.githubusercontent.com/35794614/35614087-32bc9130-066e-11e8-9a58-59832a93431b.png)

### Sample Page

This is a temporary test location
[http://www.won-nl.org/wontest/public/nl/start]

**Comment by ggieling** [comment]
Giuseppe,
With solving issue #344 this problem returned again.  Probably you removed this correction together with the purplenumbers #342 correction that caused issue #344 

Gerben

**Comment by LotarProject** [comment]
Hi,
seems a cache problem, because i have tested again in my dev environment and works fine.

Can you purge DokuWiki cache and browser cache again ?

Thanks.

Best regards,
Joseph

**Comment by ggieling** [comment]
I reinstalled the template, cleared the cache and tried in two browsers but the problem truly returned.
Exactly as depicted above.
Please note that purging the cache also reloads the page.  As described above, reloading the page solves the issue until the next expand and condense.  Thus after purging the cache, the situation is normal, until you expand and condense once more.
