### ISSUE TITLE
menu in Bootstrap3 template without bootswrapper plugin

### ISSUE THREAD

**Issue by ggieling** [LotarProject/dokuwiki-template-bootstrap3#344]
Giuseppe,

First of all, thank you for sharing this template.  I like the presence of a menu bar option, the detailed configuration options and the use of hooks that can be defined using standard wiki pages.

I am testing a dokuwiki environment with bootstrap3 plugin as base template and ran into an issue when I create a menu.  The menu is defined as a standard unordered list and all but one items have second level subitems.  A part of the menulist, including the entry without subitems, is included below.
```
  * Members section
    * [[members:alv_presentaties|Presentations AGM]]
    * [[members:notulen_alv|Minutes / Reports]]
    * [[members:seminar_presentaties|Presentations seminar]]
    * [[members:notulen_sacepo|Minutes SACEPO - PDI]]
    * [[members:ledenlijst|WON representatives]]
  * [[public:en:vacatures|Vacancies]]
  * Links
    * [[public:en:ug|User groups]]
    * [[public:en:patinf|Public sources]]
    * [[http://sites.google.com/site/wonwiki/|WSI information]]
    * [[http://www.won-nl.org/ipc-nl/ipc.htm|IPC-NL]]
```
The issue is with the entry `  * [[public:en:vacatures|Vacancies]]`.
If the bootswrapper plugin is installed together with the bootstrap3 template everything functions as expected, but without this bootswrapper plugin the 'vacancies' entry is displayed below the line of the other entries.

The code created for this menu section is displayed below:
```
<li class="level1 node dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members section <span class="caret"></span></a>
--
  | <ul class="dropdown-menu" role="menu">
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/alv_presentaties" class="wikilink1" title="members:alv_presentaties">Presentations AGM</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/notulen_alv" class="wikilink2" title="members:notulen_alv" rel="nofollow">Minutes / Reports</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/seminar_presentaties" class="wikilink2" title="members:seminar_presentaties" rel="nofollow">Presentations seminar</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/notulen_sacepo" class="wikilink2" title="members:notulen_sacepo" rel="nofollow">Minutes SACEPO - PDI</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/members/ledenlijst" class="wikilink2" title="members:ledenlijst" rel="nofollow">WON representatives</a>
  | </li>
  | </ul>
  | </li>
  | <li class="level1 dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a> <span class="caret"></span></a>
  | </li>
  | <li class="level1 node dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Links <span class="caret"></span></a>
  | <ul class="dropdown-menu" role="menu">
  | <li class="level2"> <a href="/dokuwiki/doku.php/public/en/ug" class="wikilink1" title="public:en:ug">User groups</a>
  | </li>
  | <li class="level2"> <a href="/dokuwiki/doku.php/public/en/patinf" class="wikilink2" title="public:en:patinf" rel="nofollow">Public sources</a>
  | </li>
  | <li class="level2"> <a href="http://sites.google.com/site/wonwiki/" class="" target="ext" title="http://sites.google.com/site/wonwiki/" rel="nofollow noopener">WSI information</a>
  | </li>
  | <li class="level2"> <a href="http://www.won-nl.org/ipc-nl/ipc.htm" class="" target="ext" title="http://www.won-nl.org/ipc-nl/ipc.htm" rel="nofollow noopener">IPC-NL</a>
  | </li>
  | </ul>
  | </li>
```
The critical section is the section for the "vacancies" link which, without the bootswrapper plugin, is generated as:
```
<li class="level1 dropdown"><a href="/dokuwiki/doku.php/public/en/navbar" class="dropdown-toggle" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a> <span class="caret"></span></a>
</li>
```
and with the bootswrapper plugin as:
```
<li class="level1"> <a href="/dokuwiki/doku.php/public/en/vacatures" class="wikilink1" title="public:en:vacatures">Vacancies</a>
</li>
```
Since the "a" element inside a "li" element of a navbar class is defined as a block element with padding, the code generated without the bootswrapper plugin installed produces two "a" blocks inside the "li" element with the second block positioned below the first block and the "span" element positioned below the two "li" elements.  As a consequence, the entire menu without the bootswrapper plugin occupies three times the height it occupies with the bootswrapper plugin installed.

The issue apparently is that without the bootswrapper plugin an entry without subitems generates the dropdown "a" element the actual link "a" element and the "span", whereas the same entry with bootswrapper plugin generates only the actual link "a" element.

Also the classes for the parent "li" elements differ.  Without the bootswrapper plugin the "li" element has the classes "level1 node dropdown" regardless of the presence of submenu items.  With the bootswrapper plugin an item without subitems generates an "li" element with only the "level1" class.

It seems as if a critical piece of code is present in the bootswrapper plugin, but missing in the bootstrap3 template.

I have tried to mimic the same behaviour in the test environment that has the bootswrapper plugin installed by deactivating the bootswrapper plugin.  But with the bootswrapper installed but disabled, the menu is generated as expected.

Since I do not yet know if I am actually going to use any of the bootswrapper functions, I would like to see the menu in the bootstrap plugin behave as expected with and without the bootswrapper plugin installed to allow me to choose to leave out the bootswrapper plugin if I do not need any of its functions.  It seems that right now I need to install it only to make the menu of the bootstrap3 template function as expected.

To prevent possible incompatibility issues with other plugins, I prefer to install only plugins I really use.

Tested in:
Chromium Version 64.0.3282.119 (Developer Build) (64-bit) (Arch Linux) and
Firefox 58.0 (64-bit) (Arch Linux)### Description

**Comment by LotarProject** [comment]
Hi, thanks for reporting this issue.

Can you specify the version of Bootstrap3 template and Bootstrap Wrapper plugin ?
Thanks.

At your disposal,
Joseph

**Comment by ggieling** [comment]
It is dokuwiki version: 2017-02-19 "Frusterick Manners" 
bootstrap3 version: 2016-12-12
bootswrapper plugin version: 2017-04-07 (but as indicated above, not installed in the environment that shows the problem.  Installing this plugin solves the problem, even when disabled in the extension manager).

**Comment by ggieling** [comment]
P.S. I noticed that you have quite some changes that have not yet made it into the "master" version of this project.  If you want me to try these updates, I'm willing to do so, but I am new to this github environment, can you tell me how I can install this not yet released code, or point me to a page that tells me how to do so?

**Comment by LotarProject** [comment]
Hi, i have found the bug and have fixed this issue in master and development (next release) branch.

Can you reinstall the template via Extension Manager ?

Thanks.

At your disposal,
Joseph

**Comment by ggieling** [comment]
A reinstall of the template fixed the issue.
I had just found the origin as well by comparing a testsite of one week ago with the new site created last saturday. the difference was in lines 568 and 569 of `lib/tpl/bootstrap3//tpl_functions.php`
   "# FIX for Purplenumbers renderer plugin."

Thanks for the quick solution.

**Comment by LotarProject** [comment]
Thanks!!
