### ISSUE TITLE
Uncaught TypeError: jQuery(...).typeahead is not a function

### ISSUE THREAD

**Issue by issmirnov** [LotarProject/dokuwiki-template-bootstrap3#345]
### Description

After upgrade, console shows error with typeahead:
```
jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2 Uncaught TypeError: jQuery(...).typeahead is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=50070dd22f4970c210498db77eb6757e:1)
    at j (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
    at k (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
```

This seems to be coming from [this line](https://github.com/LotarProject/dokuwiki-template-bootstrap3/blob/master/script.js#L37).

### Steps to reproduce

1. Install latest template
2. Load start page.

**Expected behavior:** 

No console errors.

**Actual behavior:**
Stack trace for readahead.

### Versions

* [Bootstrap3 Template] v2018-02-16
* [DokuWiki] 2017-02-19e "Frusterick Manners"
* [Plugins] Nothing out of the ordinary.
* [Browser] 64.0.3282.167

### Screenshots or Logs

```
jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2 Uncaught TypeError: jQuery(...).typeahead is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=50070dd22f4970c210498db77eb6757e:1)
    at j (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
    at k (jquery.php?tseed=23f888679b4f1dc26eef34902aca964f:2)
```

### Sample page or snippet

```
# Welcome

Welcome to my wiki.
```

**Comment by Digitalin** [comment]
Hello, 
Just in case, have you fasterwiki plugin installed ?

**Comment by LotarProject** [comment]
Hi,
thanks for reporting this issue. Seems not all template files is not installed properly. You can reinstall again the template ?

**Comment by issmirnov** [comment]
Thanks - reinstalled template, rebooted server and problem was solved. 

Appreciate the new release :D
