### ISSUE TITLE
Tabbox plugin no longer supported in new version?

### ISSUE THREAD

**Issue by martk70** [LotarProject/dokuwiki-template-bootstrap3#347]
### Description

Feature: old version did tolerate the invaluable tabbox plugin, new version doesn't (turns it into a list).

### Steps to reproduce

1. Update this template
2. Horizontal tabs are gone, vertical unordered list appears. Luckily links are still functional and a grey area below the link list fills according to the select link.

**Expected behavior:** Nothing to expect since you do not include the tabbox plugin in your list of integrated plugins. But a little disappointed :-) since I use the tabbox plugin extensively, and your equivalent in the wrapper plugin (or the wrap tabs plugin) seem to have not the same functionality.

**Actual behavior:** 

** Remarkable:** In edit - preview mode the tabbox plugin output looks as usual!

### Versions

* bootstrap 3 plugin: newest
* dokuwiki: newest
* plugin: tabbox
* chrome

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by LotarProject** [comment]
Hi @martk70, thanks for reporting this issue. I have re-added the event "bootstrap3:tabs" events for all plugin that use DokuWiki tabs.

You can reinstall the template again and purge all cache (DokuWiki and browser cache) ?

At your disposal,
Joseph

**Comment by martk70** [comment]
Dear mr Terlizi,

Thank you for your efforts in making this template even better and for the quick solution! Things work fine again.

Martin
