### ISSUE TITLE
Using Bootswrapper <panel> in sidebar creates unexpected underline

### ISSUE THREAD

**Issue by per-hed** [LotarProject/dokuwiki-template-bootstrap3#348]
### Description

When using a Bootswrapper panel in a sidebar with the latest (2018-02-16) Bootstrap3-theme, there is an underline beneath the panel title, which didn't appear in previous versions. This underline is not visible when a panel is used within article data.

### Versions

* Bootstrap3 Template: 2018-02-16
* DokuWiki: Elenor of Tsort
* Bootswrapper: 2017-04-07
* Browser: Google Chrome 63.0.3239.132

### Screenshots or Logs
![image](https://user-images.githubusercontent.com/15871261/36472332-d44a5a8a-16f1-11e8-902c-54c2cd386f76.png)

### Sample page or snippet

```
<panel type="info" title="Cision News" icon="fa fa-newspaper-o fa-lg fa-pull-left fa-fw">
panel content
</panel>
```

**Comment by LotarProject** [comment]
Hi @per-hed, 
thanks for reporting this issue. I have fixed this problem in develop and master branch.
Can you reinstall the template again ?

At your disposal,
Joseph

**Comment by per-hed** [comment]
That fixed it! Thanks for quick help. :+1:
