### ISSUE TITLE
plugin:tagalerts used to be affixed to navbar?

### ISSUE THREAD

**Issue by per-hed** [LotarProject/dokuwiki-template-bootstrap3#349]
### Description
Feature request or bug report?

I seem to remember that when using [plugin:tagalerts](https://www.dokuwiki.org/plugin:tagalerts/) the resulting tag would be affixed to the bottom right-hand corner of the navbar when scrolling.

I don't think that this feature has been available for several versions, and it is possible that it disappeared with fb51bfdacec5550313f967dfe2836a3502a6ca0d, but I would like it if it could be reintroduced. :)

Thanks in advance!

### Versions
* Bootstrap3 Template: 2018-02-16
* DokuWiki: Elenor of Tsort
* Bootswrapper: 2017-04-07
* Browser: Google Chrome 63.0.3239.132

**Comment by LotarProject** [comment]
Hi, this is a very interesting plugin!
I have added ad initial and official integration of this plugin in **develop** branch.

**Comment by per-hed** [comment]
Thanks, looking forward to it! :+1:

**Comment by LotarProject** [comment]
This feature will be added in next release of template.
