### ISSUE TITLE
Problem with TODO-Plugin (<todo>)

### ISSUE THREAD

**Issue by ParoTheParrot** [LotarProject/dokuwiki-template-bootstrap3#35]
A page witch uses the https://www.dokuwiki.org/plugin%3Atodo Plugin shows no content. Editing and preview is possible :-/

**Comment by LotarProject** [comment]
Hi. The Todo Plugin is introduced with issue #21.
I have tested in different DokuWiki installation and see the content.

I suggest to donwload latest release the template, flush the cache of DokuWiki (CSS via "dokuwiki/lib/exe/css.php?purge=true" and JS "dokuwiki/lib/exe/js.php?purge=true") and flush the browser cache.

Best regards,
Joseph
