### ISSUE TITLE
Problem with Bootswatch.com themes

### ISSUE THREAD

**Issue by DrakMrak** [LotarProject/dokuwiki-template-bootstrap3#350]
### Description
When I choose Vanila Bootstrap theme all is OK
When I choose Bootswatch.com I have problem with warnings for all optional themes (Flatly,Yetti, .....)
---
Warning: file_exists(): open_basedir restriction in effect. File(/lib/tpl/bootstrap3/assets/fonts/flatly.fonts.css) is not within the allowed path(s): (/data/web/virtuals/52324/virtual) in /data/web/virtuals/52324/virtual/www/lib/tpl/bootstrap3/tpl_functions.php on line 1706
----
 
### Steps to reproduce
in Description

### Versions

* [Bootstrap3 Template] - last
* [DokuWiki] - last 2017-02-19e "Frusterick Manners"
* [Plugins] a lot of :) 
Abbreviation Tooltip od Satoshi Sahara
ACL Manager od Andreas Gohr
Plain Auth Plugin od Andreas Gohr
autogallery plugin beta1 od Tim Siebentaler
Blockquote Plugin od Anika Henke (previous author: Gina Haeussge)
bootnote od Algorys
Bootstrap Wrapper Plugin od Giuseppe Di Terlizzi
Changes Plugin od Andreas Gohr
cleanup plugin od Andreas Gohr
Cloud Plugin od Michael Hamann, Michael Klier, Gina Haeussge
CodeMirror plugin od Albert Gasset
Configuration Manager od Christopher Smith
csstimeline plugin od Andreas Boehler
edittable plugin od Andreas Gohr
Extension Manager od Michael Hamann
Gallery Plugin od Andreas Gohr
hidden Plugin od Guillaume Turri
HTML Comment Plugin od Christopher Arndt
Icons Plugin od Giuseppe Di Terlizzi
include plugin od Michael Hamann, Gina Häussge, Christopher Smith, Michael Klier, Esther Brunner
Info Plugin od Andreas Gohr
news od Myron Turner
nspages plugin od Guillaume Turri
Pagelist Plugin od Matthias Schulte, Michael Hamann, Michael Klier, Gina Haeussge
PageQuery Plugin od Symon Bent
PhotoGallery Plugin od Marco Nolletti
Popularity Feedback Plugin od Andreas Gohr
QuickStats Plugin od Myron Turner
recaptcha2 od Martin Gross
Revert Manager od Andreas Gohr
safefnrecode plugin od Andreas Gohr
Searchindex Manager od Andreas Gohr
Securelogin Plugin od Mikhail I. Izmestev, Matt Bagley
slider plugin od Andreas Gohr
Socialite plugin od Fernando Ribeiro
styling plugin od Andreas Gohr
Tag Plugin od Michael Hamann, Gina Häussge, Christopher Smith, Michael Klier, Esther Brunner
ToDo od Leo Eibler, Christian Marg, Markus Gschwendt
DokuWiki Upgrade Plugin od Andreas Gohr
User Manager od Chris Smith
Video Sharing Site Plugin od Andreas Gohr
Wrap Plugin od Anika Henke
* [Browser]
FireFox - last version
EDGE

### Screenshots or Logs

in Description

**Comment by LotarProject** [comment]
Hi @DrakMrak ,
seems a server or hosting problem. Check the value of `open_basedir` PHP directive:

- https://secure.php.net/manual/en/ini.core.php#ini.open-basedir
- https://www.templatemonster.com/help/open_basedir-restriction-in-effect-filex-is-not-within-the-allowed-paths-y.html

At your disposal,
Joseph

**Comment by DrakMrak** [comment]
Hi 
OK
the previous version of bootstrap3 did not do this problem....
so ok I try set open-basedir

thanks for Informatin
DrakMrak

**Comment by LotarProject** [comment]
Hi, This 8b809ea commit don't solve the issue but suppress the waning.
