### ISSUE TITLE
Current version does not center h1 headers correctly with NOTOC pages

### ISSUE THREAD

**Issue by dralli72** [LotarProject/dokuwiki-template-bootstrap3#351]
### Description

Hi, after upgrading the template to the current version, h1 headers are not centered correctly when they are displayed on a wiki page with the ~ ~ NOTOC ~ ~ macro. This was not the case with the previous version.

### Steps to reproduce

1. I've edited the "userstyle.css" file with additional CSS for h1 headers:

```
h1 {
  font-family: "Kaushan Script","Raleway","Helvetica Neue",Helvetica,Arial,sans-serif !important;
  text-shadow: 2px 2px 0 rgba(0,0,0,33%);
  text-align: center;
}
```

2. Purge DokuWiki's CSS cache, delete browser's cache and reload the page

**Expected behavior:** On a page with a visible TOC, the h1 header is centered between the left border of the page and the left border of the TOC. When you minimize the TOC, the h1 header is centered between the left and the right borders of the page. When there is no TOC, the h1 header should also be centered between the left and right borders of the page.

**Actual behavior:** When there is no TOC, the h1 header is centered between the left border of the page and an invisible border of the area where the TOC normally displays.

### Versions

* Current version (updated 2 days ago)
* 2017-02-19e "Frusterick Manners"
* Chrome Version 64.0.3282.167 (Official Build) (64-Bit)

### Screenshots or Logs

Page with visible TOC:
![image](https://user-images.githubusercontent.com/36745210/36563300-f8055c12-1819-11e8-9842-b5e56adacc68.png)

Page with minmized TOC:
![image](https://user-images.githubusercontent.com/36745210/36563332-12346718-181a-11e8-9040-7be963f86e65.png)

Page with ~ ~ NOTOC ~ ~ macro (it's the same when there are not enough headers to generate a TOC):
![image](https://user-images.githubusercontent.com/36745210/36563361-29e7173e-181a-11e8-8bcd-8e794f50c6da.png)

Page source with div for TOC
![image](https://user-images.githubusercontent.com/36745210/36563472-75bf3d26-181a-11e8-9039-9f3265610465.png)

**Comment by trailjeep** [comment]
Adding `.dw-toc { width: auto }` to userstyle.css fixed this for me.

**Comment by LotarProject** [comment]
Hi, i have fixed this issue in master and develop branch.

Can you reinstall the template again ?

Thanks.

At your disposal,
Joseph

**Comment by trailjeep** [comment]
Updated & working fine here.

**Comment by dralli72** [comment]
Re-installed the template and everything looks good now. Thank you, Joseph!
