### ISSUE TITLE
Editor dropdowns covered by footer license.

### ISSUE THREAD

**Issue by trailjeep** [LotarProject/dokuwiki-template-bootstrap3#353]
### Description

When editing and click, for example, Special Chars., footer license div covers selection.

### Steps to reproduce

1. edit a page
2. click special chars. (omega symbol) -or- others

**Expected behavior:** expect to be able to select any symbol

**Actual behavior:** some symbols are covered by footer

### Versions

* [Bootstrap3 Template] latest
* [DokuWiki] latest
* [Plugins] too many to list
* [Browser] chrome latest

### Screenshots or Logs

![screenshot_20180226_105342](https://user-images.githubusercontent.com/175368/36680333-7b53af6c-1ae3-11e8-8f02-ac4da1d99304.png)

### Sample page or snippet

N/A

**Comment by LotarProject** [comment]
Hi @trailjeep thanks for reporting this issue.

What is the theme used ?

Joseph

**Comment by trailjeep** [comment]
bootswatch -> slate & solar also.

**Comment by LotarProject** [comment]
Fixed in next release of template.
