### ISSUE TITLE
Conflict with plugin:ToDo

### ISSUE THREAD

**Issue by nurzu** [LotarProject/dokuwiki-template-bootstrap3#354]
### Description

Since I upgraded Bootstrap3 to its new version, the Plugin ToDo doesn't show the checkbox as checked anymore, but left unchecked as seen on the screenshot. Maybe the class is overwritten. It was working fine in v2016-12-12. 

### Steps to reproduce

1. Creating a task/checkbox in the editor
2. Marking it as „done“ by adding a # to the tag
3. Saving the article

or

2. Marking it as „done“ by clicking it > marked as done
3. Reloading page > marked as undone
 
**Expected "visual" behavior:** Checkbox is marked as checked (blue)

**Actual "visual" behavior:** Checkbox remains empty, unchecked (blank)

### Versions

* [Bootstrap3 Template] v2018-02-16 
* [DokuWiki] Release 2017-02-19e “Frusterick Manners”
* [Plugins] [ToDo](https://www.dokuwiki.org/plugin:todo) Last updated on 2017-01-06
* [Browser] All modern browsers

### Screenshots or Logs

![todo](https://user-images.githubusercontent.com/36882769/36722878-09779076-1baf-11e8-9414-c6d5e94ed039.jpg)

### Thanks

Bootstrap3 Template is just great. Thank you so much for creating it!

**Comment by LotarProject** [comment]
Hi @nurzu,
thanks for reporting this issue,

I have applied workaround in master and develop branch and have opened a PR (merged just few minutes ago) with the fix on Todo Plugin repository.

You can reinstall the template again ?

At your disposal,
Joseph

**Comment by nurzu** [comment]
I reinstalled the template and tested it afterwards on all modern browsers. All works quite well!
Just brilliant. Thanks!
