### ISSUE TITLE
keyboard access for new searchbar

### ISSUE THREAD

**Issue by nurzu** [LotarProject/dokuwiki-template-bootstrap3#356]
### Description

To make the "new fresh layout for search bar" in v2018-02-16 extra smooth and even more user-friendly, it would be great if I could access the results of my search, keeping my hands on the keyboard. But there is a small barrier … 

### Steps to reproduce

1. Clicking the searchform
2. Typing a term on the keyboard
3. Accessing the result with the arrow keys 

**Expected behavior:** Access each result in the dropdown with **one** hit on keyboard's arrow keys (down or up), followed by Enter

**Actual behavior:** First result takes two hits on the arrow key, any further result even three

**Solution:** The reason might be that the keyboard fetches the line and the path showing above each result. Not sure if it's possible to skip this behavior. 

### Versions

[Bootstrap3 Template] v2018-02-16
[DokuWiki] Release 2017-02-19e “Frusterick Manners”
[Browser] All modern browsers

**Comment by LotarProject** [comment]
Fixed this issue in next release of template.

Thanks Joseph
