### ISSUE TITLE
[Question] How could i change width of sidebar and/or textarea?

### ISSUE THREAD

**Issue by poulpoulsen** [LotarProject/dokuwiki-template-bootstrap3#36]
hello,
yesterday i installed your wonderful template and it works quit good out of the box.
Unfortunately two things are not satisfying for me:-(
1. I want to change the width of the sidebar, because i use a tagcloud and this one is currently displayed row by row. If template loads, it seems to be ok, but after loading, the tags are rearranged row by row. So i think, sidebar is too small.
2. How could i change the width of the textarea right from the sidebar? (where contents/ wikipage and so on is displayed).

Regards
Poul

**Comment by LotarProject** [comment]
Hi! I have added a new option in my last commit 1bb66b7 to adjust the sidebar size using the Bootstrap's grid classes.

For the second question: do you intend for the right textarea ? The search bar in navbar ?

Best regards,
Joseph

**Comment by poulpoulsen** [comment]
Hi,
thank you for your updat.
I dl it and install, but unfortunately i see no difference.
How could i adjust the width of the left area.
It is the same as before: Wikipage loads and during this time, the width of the area is large enough to view my tagcloud.
But after load the page is adjusted a little and the tagcloud is only row by row...
Perhaps there is a another trick to disable this refresh ...
Any idea?

Regards
Poul

**Comment by poulpoulsen** [comment]
Hello,
for your information:
Here is a snapshot of my desktop with the lefthand missing tagcloud.
Hope it helps :-)
![bootstrap-template](https://cloud.githubusercontent.com/assets/8409515/8025268/6b26c43e-0d4f-11e5-9c53-fd4e528cd148.jpg)

**Comment by LotarProject** [comment]
Hi! Which plugin uses for the cloud? I have tested the template with dokuwiki.org/plugin:cloud.

Best regards,
Joseph

**Comment by poulpoulsen** [comment]
Hello,

thanks for your info.
I use plugin:tagging.
This plugin could act as tagclouding included.
My usual template is vector. Inside this template all tags are shown 
with the same fontsize.
But only inside the sidebar. If i use the cloud on top of a page, then 
it works perfect.
As wrote in my last mail, inside your template the view is different.
During pageload the tagcloud looks correct, but after the complete 
pageload the navigation area has been refreshed and unfortunately all 
tags are shown in same fontsize and row by row.
Strange :-(

Regards,
Poul


Am 08.06.2015 um 11:10 schrieb Giuseppe Di Terlizzi:

**Comment by LotarProject** [comment]
Hi! I have fixed the issue in my last commit. This plugin is very useful :) Thanks!

Best regards,
Joseph

**Comment by poulpoulsen** [comment]
Hello,
i just downloaded your most recent version and IT WORKS!

Thanks a lot :-)

But unfortunately i found another bug:
The Admin TOC has no scroll bar. I have too many entries (loaded 
plugins, loaded templates and so on), so they won`t fit on one page.
Therefore i cannot access e.g. the template section to configure something.
Is it possible to change this behavior ?

Regards
Poul


Am 11.06.2015 um 18:01 schrieb Giuseppe Di Terlizzi:

**Comment by Juergen-aus-Koeln** [comment]
I have the same problem

Regards Juergen

**Comment by poulpoulsen** [comment]
Hello,
my problem is gone with the newest version from git.
Developer has bugfixed very fast!

Regards
Poul


Am 12.06.2015 um 21:19 schrieb Juergen-aus-Koeln:

**Comment by LotarProject** [comment]
Hi @poulpoulsen, see the last commit d82a276 for TOC issue.

Best regards,
Joseph

**Comment by poulpoulsen** [comment]
Wonderful!
it's gone also.
You are very fast in bughunting :-)
Best regards
Poul
