### ISSUE TITLE
Make tools icons on right fixed size

### ISSUE THREAD

**Issue by macau23** [LotarProject/dokuwiki-template-bootstrap3#363]
### Description

Could you make the icons on the right hand side (edit/revisions/backlinks) a fixed size, or have the option to have them a fixed size?

Currently they grow when you mouse over them and I've noticed that people wait until they are at full size before clicking them.

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
* [DokuWiki]
* [Plugins]
* [Browser]

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by MvErven** [comment]
You could try the configuration option:  "Enable the tool page animation"

**Comment by macau23** [comment]
Thanks.
