### ISSUE TITLE
Feature: pageId with double brackets

### ISSUE THREAD

**Issue by onkobu** [LotarProject/dokuwiki-template-bootstrap3#364]
### Description

Add double brackets to the pageId so that copy+paste of the pageId text turns automagically into a valid wiki link.

### Steps to reproduce

1. Open any page
2. pageId (top right, blue background) displays without double brackets

**Expected behavior:** pageId is rendered with double brackets

**Actual behavior:** pageId is rendered without double brackets

**Comment by LotarProject** [comment]
This feature will be added in next release of template.

Thanks for your idea.
