### ISSUE TITLE
Update 2018-04-22 "Greebo" shows debug error for _search.css

### ISSUE THREAD

**Issue by n1trux** [LotarProject/dokuwiki-template-bootstrap3#367]
### Description

Error message

>Stylesheet ../dokuwiki/css/_search.css not found, using ../dokuwiki/css/_search.less instead. Please contact developer of "bootstrap3" template.

is shown in the header after upgrading to 2018-04-22 "Greebo".

### Steps to reproduce

1. Update to 2018-04-22 "Greebo"
2. set option "allowdebug"

**Expected behavior:** The error shouldn't appear

**Actual behavior:** The error appears

### Versions

* dokuwiki-template-bootstrap3 2018-02-16
* DokuWiki 2018-04-22 "Greebo"

**Comment by LotarProject** [comment]
Hi, i have added all DokuWiki core styles into Bootstrap3 template to prevent this issue with new DokuWiki release.

Please reinstall the template again.

At your disposal,
Joseph
