### ISSUE TITLE
Darkly theme woes

### ISSUE THREAD

**Issue by Aidolii** [LotarProject/dokuwiki-template-bootstrap3#368]
Bootstrap3 is currently the most up to date theme that supports all the new features and offers dark themes, however there are some gaps.

Media Manager's highlighting does not seem to abide by the Bootswatch theming, nor the Template Style Settings.

Much of the admin section, configuration in particular, also displays a lot of black text.

Obviously this is not ideal since on a dark theme, you can't really read any of it.

**Comment by Miro-Collas** [comment]
FWIW, I have the same issue with Darkly. I haven't yet tried others.

**Comment by Miro-Collas** [comment]
To fix the Extension manager colors, I stuck this in userstyle.css:
```
#extension__list {
    ul.extensionList li {
        color: inherit;
    }
    .legend {
        color: inherit;
    }
    p {
        color: inherit;
    }
}

```
Not looked at the rest yet.

**Comment by LotarProject** [comment]
I have added @Miro-Collas patch in develop branch.

I have extended this patch FIX this issue for this themes:
- cyborg
- darkly
- slate
- superhero
- solar

**NOTE** Clear browser and DokuWiki cache, after the patch installation.

Thanks!!!
