### ISSUE TITLE
CSS error after last version upgrade

### ISSUE THREAD

**Issue by tkrameral** [LotarProject/dokuwiki-template-bootstrap3#370]
### Description

Dokuwiki show warning error after upgrade to new version (2018-04-22 "Greebo"):

Stylesheet ../dokuwiki/css/_search.css not found, using ../dokuwiki/css/_search.less instead. Please contact developer of "bootstrap3" template. 

### Versions

* [DokuWiki] 2018-04-22 "Greebo"

**Comment by LotarProject** [comment]
Hi @tkrameral, i have fixed this issue yesterday in master and develop branches. You can reinstall the template again ?

Thanks,
Joseph

**Comment by tkrameral** [comment]
Perfect! Problem solved! Thanks!
