### ISSUE TITLE
Search matching pagenames overlap

### ISSUE THREAD

**Issue by MKCPC** [LotarProject/dokuwiki-template-bootstrap3#375]
### Description

I am using the Vanilla bootstrap theme and when performing a search the pages listed under matching pagenames all overlap each other.  I have tested going back to the default DokuWiki theme and I do not experience this issue.

### Versions

* [Bootstrap3 Template] - 2018-02-16
* [DokuWiki] - 2018-04-22a "Greebo"
* [Plugins] - ACL Manager, Alert Box, ADAuth, Authorstats, Code Prettifier, Color Syntax, indexMenu, Move, Styling, User Manager
* [Browser] - Google Chrome & Internet Explorer

### Screenshots or Logs

![image](https://user-images.githubusercontent.com/33957383/40056091-20b311be-5842-11e8-863e-27f0c71d7bdf.png)

**Comment by graham-macleod** [comment]
I too had this issue. I worked around it by setting the dokuwiki configuration to "Always" which then stops the links being one long string and allows them to line break. Not a fix, but it might be an appropriate work around for you as well. Obviously that is a change in behaviour and might not fly with your users.

https://www.dokuwiki.org/config:useheading

**Comment by LotarProject** [comment]
Hi,
This issue is resolved in "develop" and next release of template.

Joseph
