### ISSUE TITLE
TOC Pushes Down Some Types of Content

### ISSUE THREAD

**Issue by Miro-Collas** [LotarProject/dokuwiki-template-bootstrap3#377]
### Description

If a page has a TOC, and also a callout or an image near the top, the text of the callout (or the image) is pushed down, until you scroll the page such that the TOC collapses. Then the callout/image snaps back up to where it should be.

### Versions

* Bootstrap3 Template: 2018-02-16
* DokuWiki: Greebo
* Browser: Version 66.0.3359.181 (Official Build) (64-bit)

### Sample page or snippet

Compare:
http://wiki.phoenixviewer.com/fs_bake_fail
with
http://wiki.phoenixviewer.com/fs_missing_inventory

**Comment by Miro-Collas** [comment]
Never mind, I see someone reported it https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/issues/99 and a solution was found.

**Comment by Miro-Collas** [comment]
Since you pulled in the Extension Manager fix, might also want to pull in the fix give on https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/issues/99

**Comment by LotarProject** [comment]
Fixed ;)

**Comment by Miro-Collas** [comment]
Many thanks! :-)
