### ISSUE TITLE
Function of Edit-Button 

### ISSUE THREAD

**Issue by nurzu** [LotarProject/dokuwiki-template-bootstrap3#379]
### Description

I just updated from 2017-02-19e “Frusterick Manners” to the 2018-04-22a "Greebo". As everything went fine I just noticed, that the behavior of the Edit-Button changed recently on different settings. 

1. All is fine, when the page already exists. It takes me to **&do=edit** [E] and I can edit the content. 
2. If the page doesn't exists it just takes me to **&do** [V] and no further but blank page [View]. 
3. On Frusterick Manners it took me to the page "This site doesn't exist yet" and the I could klick the Edit-Button again to create/edit a new page. 

### Steps to reproduce

1. Navigate to a page not existing yet
2. Click the Edit-Button

**Expected behavior:** 
Either I see the Edit-Panel an can create the site 
**or** a site saying it "doesn't exist yet" letting me create the page in second step

**Actual behavior:** 
I end up on **&do** [V] an no further. 
Have to change url manually in **&do=edit** [E]

### Versions

[Bootstrap3 Template] v2018-02-16 (version of today 2018-06-09)
[DokuWiki] Release 2018-04-22a "Greebo"
[Plugins] quite some
[Browser] All modern browsers

### Screenshots or Logs

![bildschirmfoto 2018-06-09 um 23 16 29](https://user-images.githubusercontent.com/36882769/41196405-9c42014e-6c3f-11e8-8b51-6371f9a2b9bb.png)
![bildschirmfoto 2018-06-09 um 23 17 29](https://user-images.githubusercontent.com/36882769/41196404-9c109866-6c3f-11e8-9ecd-7c8918135cd4.png)

**Comment by nurzu** [comment]
It works as it should with standard DokuWiki-template.

**Comment by mP-wiki** [comment]
Running on Greebo
I can not reproduce the issue @nurzu . When I click 'edit' button, it takes me to editor and create page...

**Comment by LotarProject** [comment]
I have tested different DokuWiki installation but i don't' see the issue. This issue still persist ?

**Comment by nurzu** [comment]
I finally by surprise found out what caused the problem. It's another Plugin by Andreas (founder of DokuWiki) called "[notfound](http://www.dokuwiki.org/plugin:notfound)". 

For a public wiki this plugin is very useful, so i'd like to ask, if it's possible for someone to solve this issue either in "bootstrap3" or in "notfound", i'd be very happy.
