### ISSUE TITLE
"Show differences" buttons stays disabled

### ISSUE THREAD

**Issue by alphabernd** [LotarProject/dokuwiki-template-bootstrap3#38]
Hi,

on the revisions page of a entry the "Show differences between selected revisions" button stays disabled even if 2 pages are selected.

![diff](https://cloud.githubusercontent.com/assets/3717732/7949022/f7550a8e-0989-11e5-870e-675095ba2a59.png)

**Comment by LotarProject** [comment]
Hi! I have fixed this issue in my last commit.

Best regards,
Joseph

**Comment by alphabernd** [comment]
Thanks! Just installed the updated version and it works as expected
