### ISSUE TITLE
Purging the caches

### ISSUE THREAD

**Issue by trailjeep** [LotarProject/dokuwiki-template-bootstrap3#383]
### Description

Using both Bootstrap3 template and Advanced plugin the shortcuts button to add `?purge=true` do not seem to work.

### Steps to reproduce

Bootstrap3 tpl click on "Purge page cache" icon and page is reloaded with `?purge=true` appended in URL bar, however, page cache is not cleared. If I then click in the URL bar and press enter manually it works?!?!

Advanced plugin seems to behave the same when clicking "Purge CSS cache" button or "Purge JS cache", but the URL isn't exposed.

### Reference

splitbrain/dokuwiki/issues/2435 where splitbrain commented:
>Purging the cache via purge variable only works when manually submitted and is ignored when a referrer header is present.

### Versions

* Dokuwiki: Latest
* Bootstrap3 Template: Latest
* Advanced Plugin: Latest

**Comment by virk** [comment]
I experienced the same behaviour and it was astonishing me; I thought something was wrong with my installation somehow.

**Comment by phy25** [comment]
Are you sure this is not happening when advanced plugin is being used with other templates, by any chance?

**Comment by LotarProject** [comment]
This feature is removed in next version of template.
