### ISSUE TITLE
image scaling in pageheader

### ISSUE THREAD

**Issue by dranjor** [LotarProject/dokuwiki-template-bootstrap3#388]
### Description

Images in pageheader do not scale on mobile, because class `img-responsive` is not available.

### Steps to reproduce

Add `{{ :path:to:img.jpg?nolink |}}` to `:playground:pageheader` => resulting in
 
![bildschirmfoto vom 2018-07-26 um 14 23 41](https://user-images.githubusercontent.com/18162321/43262181-80f0caa0-90df-11e8-8727-9e1f021583de.png)

**Expected behavior:** the image should not damage any margins.

### Versions

* Bootstrap3 Template: 2018-02-16
* DokuWiki: 2018-04-22a "Greebo
* Browser: Firefox 52.8.0

**Comment by mP-wiki** [comment]
Good luck to find solution here bro...

**Comment by LotarProject** [comment]
This is a splendid idea! I have added this feature in develop branch.

Thanks a lot!
