### ISSUE TITLE
Bootstrap Deprecated calls.

### ISSUE THREAD

**Issue by rgleason** [LotarProject/dokuwiki-template-bootstrap3#390]
### Description

[Description of the bug or feature]
Errors,  Deprecated calls. 
### Steps to reproduce

Trying to get SiteExport plugin going, looked in the Apache debug.log
Found lots of these.. do I need to download an updated bootstrap3 or something?

09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:16:09 ::1: tpl_actionlink() is deprecated. It was called from bootstrap3_action() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:379 see devel:menus should be used instead!
09:16:09 ::1: tpl_get_action() is deprecated. It was called from tpl_actionlink() in C:\Bitnami\dokuwiki-20180422a-2\apps\dokuwiki\htdocs\lib\tpl\bootstrap3\tpl_functions.php:193 see devel:menus should be used instead!
09:25:24 ::1: checkUpdateMessages(): messages up to date
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
* [DokuWiki]
* [Plugins]
* [Browser]

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by rgleason** [comment]
Why closed? You asked me to post here.

**Comment by LotarProject** [comment]
Hi, this messages are displayed because Bootstrap3 use deprecated functions to maintain the compatibility with old DokuWiki releases.
Now DokuWiki use new Menu classes (https://www.dokuwiki.org/devel:menus) but require a recent DokuWiki and PHP version.

**Comment by LotarProject** [comment]
The next release of template now use the new Menu DokuWiki system (https://www.dokuwiki.org/devel:menus)
