### ISSUE TITLE
Extension Manager hardly readable when using dark theme

### ISSUE THREAD

**Issue by MarcinOrlowski** [LotarProject/dokuwiki-template-bootstrap3#391]
Extension Manager hardlyis  readable when using dark theme. It looks like on picture below. This happens when using recent Bootstrap3 Template plugin with "Darkly" theme.

![manager](https://user-images.githubusercontent.com/8041294/44404443-25d11f80-a557-11e8-8536-830370beea2a.png)

**Comment by Miro-Collas** [comment]
I had to manually fix this by editing userstyle.css

**Comment by LotarProject** [comment]
I have added @Miro-Collas patch in develop branch.

I have extended this patch FIX this issue for this themes:
- cyborg
- darkly
- slate
- superhero
- solar

**NOTE** Clear browser and DokuWiki cache, after the patch installation.

Thanks!!!

**Comment by Miro-Collas** [comment]
Awesome - thank YOU. :-)
