### ISSUE TITLE
search tool is building an outdated search URL

### ISSUE THREAD

**Issue by schplurtz** [LotarProject/dokuwiki-template-bootstrap3#394]
### Description

Hi, this is a 2 in one issue.

[bootstrap3_searchform()](https://github.com/LotarProject/dokuwiki-template-bootstrap3/blob/9a526062c6fcfe3a906189cdf12af96c723f6d3a/tpl_functions.php#L681-L704) builds an outdated search URL. The URL currently built by bootstrap3 uses `id=searched-test&do=search`. Current DokuWiki needs `q=searched-text&do=search`. DokuWiki itself detects this condition and sends a redirect, so most of the time, this goes unnoticed. There are conditions where this can lead to DokuWiki not searching anything, but just showing the start page.

This has been discussed on [DW forum, thread 16375](https://forum.dokuwiki.org/thread/16375) with andi @splitbrain.

Also, this same function `bootstrap3_searchform()` "looses" the current page, since it redirects to the start page of the wiki. Say you are viewing page "some:page", then search something, you get to page "start" and showing search results. Current DokuWiki with its default template would leave you on page "some:page" and show search results.

### Steps to reproduce

1. Install fresh DokuWiki version greebo
2. Add bootstrap3 template, and activate it.
3. use the search tool

**Expected behavior:** 
  browser should send `page:id?q=searched-text&do=search` (or if not using nice URL `doku.php?id=page:id&q=searched-text&do=search`)

**Actual behavior:** [What actually happened]
browser sends `start?id=searched-text&do=search`
### Versions

* [Bootstrap3 Template] current
* [DokuWiki] greebo
* [Plugins] a lot...
* [Browser] FF 62.0.3

### Screenshots or Logs

![image](https://user-images.githubusercontent.com/1008292/47272047-1898d700-d580-11e8-8067-f24c0923d628.png)

**Comment by LotarProject** [comment]
Great job, PR merged :+1: 

Thanks a lot!
