### ISSUE TITLE
Print out signature

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#396]
### Description

The signature that is displayed on the screen isn't printed out

### Steps to reproduce

1. Open a wiki page
2. Print out the wiki page

**Expected behavior:** The signature should be printed out

**Actual behavior:** The signature isn't printed out

### Versions

* [Bootstrap3 Template] 2018-02-16
* [DokuWiki] Release 2018-04-22a "Greebo"
* [Plugins] several
* [Browser] Firefox 63.0 (64-Bit)

**Comment by LotarProject** [comment]
Hi @Juergen-aus-Koeln , the problem still remain ?

You can add a snipped of the page ?

Thanks Joseph
