### ISSUE TITLE
 Cannot use "\w" as the start of a range

### ISSUE THREAD

**Issue by dccafe** [LotarProject/dokuwiki-template-bootstrap3#397]
https://github.com/LotarProject/dokuwiki-template-bootstrap3/blob/119aa216fa8a48d49a1af7c24aa4045ab9f18ed1/inc/simple_html_dom.php#L1438

In PCRE regex expressions, \w cannot be used as the start of a range. This expression needs a rewrite. What are we trying to match here?

**Comment by DonGiotto** [comment]
Look here for a proper solution.
#400

**Comment by LotarProject** [comment]
Hi,
I have fixed this issue in develop branch using this patch #400.
