### ISSUE TITLE
Bootstrap Jquery version error

### ISSUE THREAD

**Issue by parkashairaroma** [LotarProject/dokuwiki-template-bootstrap3#398]
### Description

When clicking settings button or user button, getting the error "Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3" on console after upgrading to latest dokuwiki. 

### Steps to reproduce

Upgrade to latest dokuwiki

### Versions

* Bootstrap version 3.3.6 and Jquery version 3.1.1
* Using Latest version of Dokuwiki
* Using Chrome Browser

**Comment by LotarProject** [comment]
Hi, seems a cache problem because latest DokuWiki version use jQuery v3.1.1

Clear browser cache and purge DokuWiki cache (CSS and JS) using this URL:
- ``https://<dokuwiki>/lib/exe/css.php?purge=true``
- ``https://<dokuwiki>/lib/exe/js.php?purge=true``

Joseph
