### ISSUE TITLE
Glyphicons resulting in 404 Error

### ISSUE THREAD

**Issue by nick2600** [LotarProject/dokuwiki-template-bootstrap3#40]
I noticed today that when viewing my DocuWiki site that all the glyphicons are displaying as squares in Chrome and invisible in Internet Explorer. Using the Network tab under Dev resources on Chrome I discovered that the attempt to load the glyphicons as any of the font formats from https://bootswatch.com/fonts/ results in 404 errors on all of them. In fact attempting to browse to those URLs manually results in the same 404 error.

**Comment by coudot** [comment]
See https://github.com/thomaspark/bootswatch/commit/06885df3cfbb7d498f59dc5ac61a4cc1cc4f6dc2

**Comment by LotarProject** [comment]
Hi! Yes this commit change the Glyphicon font path.

Just a few minutes ago i have committed the patch c83c7c8003405a213c64fac3a64e6310ff114fc3, to use the latest (and working) release of Bootswatch (3.3.4) from the CDN.
