### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by AcaDemIQ** [LotarProject/dokuwiki-template-bootstrap3#400]
### Description

I had compilation errors on each sites

### Steps to reproduce

1. Setup Docker image using offical php image

```
FROM php:7.3.1-apache-stretch
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y wget 
WORKDIR /var/www
RUN wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
RUN tar xvf dokuwiki-stable.tgz
RUN mv ./dokuwiki-*/ ./dokuwiki
RUN chown -R www-data:www-data /var/www/dokuwiki
COPY ./000-default.conf /etc/apache2/sites-enabled
COPY ./apache2.conf /etc/apache2/apache2.conf
RUN service apache2 restart
EXPOSE 80
```

2. Add your template to DokuWiki

3. Get errors 

`Warning: preg_match_all(): Compilation failed: invalid range in character class at offset 4 in /var/www/dokuwiki/lib/tpl/bootstrap3/inc/simple_html_dom.php on line 758`

`Warning: Invalid argument supplied for foreach() in /var/www/dokuwiki/lib/tpl/bootstrap3/inc/simple_html_dom.php on line 765`

`
Warning: preg_match(): Compilation failed: invalid range in character class at offset 4 in /var/www/dokuwiki/lib/tpl/bootstrap3/inc/simple_html_dom.php on line 1438`

### Versions

* [Bootstrap3 Template 2018-02-16]
* [DokuWiki 2018-04-22b ]
* [Plugins standarts]

**Comment by AcaDemIQ** [comment]
I changed  simple_html_dom.php from `if (!preg_match("/^[\w-:]+$/", $tag))` to `if (!preg_match("/^[\w]+$/", $tag))`. Is it correct?

**Comment by Kyushin** [comment]
I changed this : 

1438 -        `if (!preg_match("/^[\w-:]+$/", $tag)) {`
1438 +        `if (!preg_match("/^[\w\-:]+$/", $tag)) {`

757 -        `$pattern = "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";`
757 +        `$pattern = "/([\w\-:\*]*)(?:\#([\w\-]+)|\.([\w\-]+))?(?:\[@?(!?[\w\-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";`

Using PHP 7.3.0 I have to espace `-`.

I hope this could help.

**Comment by dccafe** [comment]
Yep, that works for me. Can you write a patch and submit a pull request for us?

**Comment by LotarProject** [comment]
Hi,
I have fixed this issue in develop branch using @Kyushin patch

**Comment by ihewro** [comment]
thank you !
