### ISSUE TITLE
XSS Vulerability in bootstrap <3.4

### ISSUE THREAD

**Issue by gizmo21** [LotarProject/dokuwiki-template-bootstrap3#402]
Bootstrap <3.4 has new (10 Jan, 2019) XSS vulnerabilities : https://snyk.io/vuln/npm:bootstrap
Perhaps you can think about an update: https://github.com/LotarProject/dokuwiki-template-bootstrap3/blob/master/assets/bootstrap/js/bootstrap.min.js

**Comment by LotarProject** [comment]
Upped to Bootstrap/Bootswatch v 3.4.1

Thanks!

**@all-dokuwiki-users** Please flush browser and DokuWiki cache!
