### ISSUE TITLE
Update dependancy: "PHP Simple HTML DOM Parser" for PHP 7.x support

### ISSUE THREAD

**Issue by TrapSpace** [LotarProject/dokuwiki-template-bootstrap3#404]
### Description
Bootstrap3 template uses the dependancy "PHP Simple HTML DOM Parser" version 1.5 (see /inc/simple_html_dom.php) this version only supports PHP version 5.x, thus breaks Bootstrap3 template when running on a server with PHP 7.x 

The latest version of "PHP Simple HTML DOM Parser" is version 1.8.1 which DOES support PHP 7.x 
Please update this dependancy to the latest version to fix this problem. 

### Steps to reproduce
1. Install Bootstrap3 template on a Dokuwiki "Greebo" version running on PHP 7.3.1 
2. Activate the Bootstrap 3 template in /conf/local.php of Dokuwiki installation 
3. Reload Dokuwiki page and see the warnings of the dependancy appear. 

**Expected behavior:**
Suppose to work without dependancy warnings coming from PHP

**Actual behavior:**
Shows PHP warnings coming from the dependancy of Bootstrap3 template

### Versions

* [Bootstrap3 Template] v2018-02-16
* [DokuWiki] "Greebo" 
* [Plugins] Standard bundled onces 
* [Browser] Chrome latest

### Screenshots or Logs

![image](https://user-images.githubusercontent.com/18451644/52904052-80a5b400-3226-11e9-8037-87682585992b.png)

**Comment by LotarProject** [comment]
Hi,
I have fixed this issue in develop branch using this patch #400.
