### ISSUE TITLE
Tables not styled correctly

### ISSUE THREAD

**Issue by weibell** [LotarProject/dokuwiki-template-bootstrap3#405]
### Description

It appears that tables aren't styled correctly (or rather: at all) in DokuWiki 2018-04-22b "Greebo".

### Steps to reproduce

1. Install stable DokuWiki
2. Add and select Bootstrap3 Template, leave all settings on default
3. Create new page with table or simply visit "wiki:syntax"
4. Observe that tables are not styled at all (e.g. no 100% width, no stripes, etc.)

**Expected behavior:**

Something like this:

![image](https://user-images.githubusercontent.com/13382354/52918805-32121b80-32f3-11e9-9bf4-36d7a610a4a0.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/13382354/52918782-e52e4500-32f2-11e9-8108-2ca2780574a4.png)

### Versions

* [Bootstrap3 Template] v2018-02-16
* [DokuWiki] 2018-04-22b "Greebo"
* [Plugins] none
* [Browser] Firefox, Chromium, Edge, ...

**Comment by phy25** [comment]
I guess table style of Bootstrap will be applied if you use `tableFullWidth` and `tableStyle` in template config.

**Comment by weibell** [comment]
Those options are already enabled by default:

![image](https://user-images.githubusercontent.com/13382354/52918849-ff1c5780-32f3-11e9-894d-d7fc39510c7b.png)

**Comment by phy25** [comment]
I guess code here is not working as expected. If you like you may want to check if any classes have been rewritten to the table:

https://github.com/LotarProject/dokuwiki-template-bootstrap3/blob/119aa216fa8a48d49a1af7c24aa4045ab9f18ed1/tpl_functions.php#L2002-L2029

**Comment by weibell** [comment]
I figured it out. In the PHP 7 environment, the output was
`<div class="table sectionedit22"><table class="inline"> ...`

After I switched to PHP 5.6, it now correctly outputs:
`<div class="table-responsive"><table class="inline table table-striped table-condensed"> ...`

**Comment by weibell** [comment]
Upon closer inspection, the issue appears to have been been with the "PHP Simple HTML DOM Parser" dependency (#404), which is incompatible with PHP 7.

**Comment by LotarProject** [comment]
Hi,
I have fixed this issue in develop branch using this patch #400.

**Comment by ParoTheParrot** [comment]
hoho - waiting for the next release with correct table layout!
