### ISSUE TITLE
[SOLVED] Blank pages - installation broken after template changed

### ISSUE THREAD

**Issue by Aerowinder** [LotarProject/dokuwiki-template-bootstrap3#420]
### Description

Template breaks install. Can't access admin panel (blank page). Can't login. Can't do anything except see wiki articles. I attached screenshot of what I see. I know I can edit local.php manually to revert to default template.

### Steps to reproduce

1. Install Fedora 30.
2. Install and setup Doku Greebo.
3. Working great.
4. Install Bootstrap3 template.
5. Select Bootstrap3 template for use.
6. Installation hosed.

**Expected behavior:** Expected control panels to work.

**Actual behavior:** Control panels did not work.

### Versions

* Bootstrap3 2019-05-22
* Greebo ported from older Debian 9 installation
* Fedora 30 clean install
* Firefox, normal and private browsing, also tried Edge.

### Screenshots or Logs

Attached. This is what I see if I attempt to access admin panel, login, or anything really.

![Annotation 2019-05-27 010344](https://user-images.githubusercontent.com/51070353/58396995-02269280-801d-11e9-88bc-c7d050f3427b.jpg)

**Comment by phy25** [comment]
You should definitely try looking at your PHP logs to see if there's any error occured.

**Comment by LotarProject** [comment]
Which PHP version and modules are installed?

```
php -v
```

```
php -m
```

Thanks!

**Comment by Aerowinder** [comment]
> You should definitely try looking at your PHP logs to see if there's any error occured.

I'm not sure where the logs are located? I tried enabling it in /etc/php.ini > error_log = /var/www/php_errors.log - this directory is writable by the nginx web user, but no log files were created.



> Which PHP version and modules are installed?

**php -v**
PHP 7.3.5 (cli) (built: Apr 30 2019 08:37:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies


**php -m**
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
Phar
readline
Reflection
session
sockets
SPL
standard
tokenizer
zlib

[Zend Modules]

**Comment by LotarProject** [comment]
The Apache error logs are located (generally) in ``/var/log/httpd/error_log``.

I think the problem is a missing PHP module: ``php-xml``.

You can try to install this module via package manager (eg. ``yum install php-xml`` or ``dnf install php-xml``) ?

Joseph

**Comment by Aerowinder** [comment]
Installed php-xml, issue resolved. Thanks much for the help!

**Comment by LotarProject** [comment]
Thanks :smile:
