### ISSUE TITLE
showIndividualTool is not honored in v2019-05-22

### ISSUE THREAD

**Issue by AmritasyaPutra** [LotarProject/dokuwiki-template-bootstrap3#421]
### showIndividualTool is not honored

The setting showIndividualTool is not at all used in rendering.

### Steps to reproduce

Turn on the individualTools option and then select only 'page' in showIndividualTool

**Expected behavior:** Only Page Tools should show up

**Actual behavior:** Irrespective of user setting all three tools, User Tools, Site Tools and Page Tools are shown all the time.

### Versions

* [Bootstrap3 Template] v2019-05-22
* [DokuWiki]  2018-04-22b "Greebo"
* [Plugins]
* [Browser] Any browser

**Comment by LotarProject** [comment]
Hi @AmritasyaPutra,
i have fixed this issue in master branch. Please re-install the v2019-05-22 template version again.

Thanks,
Joseph

**Comment by AmritasyaPutra** [comment]
Thank you Joseph. Verified on my setup wiki.ekvastra.in. I removed my local fix and reinstalled and checked a couple of combinations. I looked at the code change also, it is good. I am closing this issue.

**Comment by LotarProject** [comment]
Thanks :)
