### ISSUE TITLE
Incompatibilty (text instead of icon displayed) between folded-plugin and bootstrap3-template

### ISSUE THREAD

**Issue by virk** [LotarProject/dokuwiki-template-bootstrap3#422]
There seems to be an incompatibility with folded-plugin and new bootstrap3-template. No longer the icon is visible but the text ( "Alles aus-/-einklappen") is displayed instead of the icon.

**Comment by virk** [comment]
I did not want to label the a above as a bug and now I do not know how to cancel this :-)

**Comment by LotarProject** [comment]
Hi,
i have fixed this graphic incompatibility in last commit.

Please reinstall the template again.

Regards,
Joseph
