### ISSUE TITLE
Pagelist tables are missing some formatting

### ISSUE THREAD

**Issue by Hitch42** [LotarProject/dokuwiki-template-bootstrap3#424]
### Description

Using the Pagelist plugin to view lists of pages with a certain tag does not display correctly when using the Bootstrap3 template.

### Steps to reproduce

1. Install the DokuWiki [Tag](https://www.dokuwiki.org/plugin:tag) plugin
2. Install the DokuWiki [Pagelist](https://www.dokuwiki.org/plugin:pagelist) plugin
3. This example also uses the DokuWiki [PageImage](https://www.dokuwiki.org/plugin:pageimage) plugin
4. in Admin/Configuration Settings menu, set Pagelist and Tag to use the default (table) style
5. Create some pages that use similar tags
6. Click on a tag to bring up a page displaying a list of pages that use those tags
7. View the page, switching between the bootstrap3 and dokuwiki templates

**Expected behavior:** The rows should be formatted in a similar style.

**Actual behavior:** The bootstrap3 template does not display the line separating each entry and there is no padding between the columns. Adjusting Bootstrap3's table option does not fix this.

### Versions

* Bootstrap3 Template: 
* DokuWiki: Release 2018-04-22b "Greebo"
* Plugins: Tag and Pagelist - newest versions as of 2019-06-08
* Browser: Chrome and Firefox

### Screenshots or Logs

- DokuWiki template: https://i.imgur.com/5Ux5evP.png
- Bootstrap3 Template https://i.imgur.com/cSJIws2.png

**Comment by LotarProject** [comment]
Hi, i have fixed this issue with a patch in master branch.
Please reinstall the template again.

Thanks,
Joseph
