### ISSUE TITLE
Tag are displayed at bottom of page

### ISSUE THREAD

**Issue by chtiland** [LotarProject/dokuwiki-template-bootstrap3#425]
### Description

Tags are displayed at bottom of the page instead of Title (Option tagsOnTop if set to false).

Note : Caches from browsers and Dokuwiki have been cleaned.

**Expected behavior:** [What you expected to happen]

Tags displayed under title of the section where it's declared (or at top of the page when option tagsOnTop if set to true)

**Actual behavior:** [What actually happened]

Tags are displayed at bottom of the page

### Versions

* [Bootstrap3 Template] : Last stable
* [DokuWiki] : Last stable
* [Plugins] : Last stable for each plugin listed bellow (from extensions manager)
  * 404manager
  * addnewpage
  * advanced
  * authad
  * authldap
  * authpdo
  * authpgsql
  * autolink4
  * autotooltip
  * backlinks
  * blockquote
  * bookcreator
  * bootswrapper
  * cloud
  * codemirror
  * comment
  * custombuttons
  * datatables
  * davcal
  * dir
  * do
  * dw2pdf
  * dwmenu
  * edittable
  * filelist
  * gallery
  * howhard
  * icons
  * iframe
  * imagebox
  * include
  * indexmenu
  * interwiki
  * keyboard
  * konsole
  * langdelete
  * lastmod
  * menu
  * message
  * monthcal
  * move
  * multiorphan
  * namespacesearch
  * note
  * nspages
  * odt
  * orphanswanted
  * pagebreak
  * pagebreak2
  * pagelist
  * pageredirect
  * prettyphoto
  * prettytables
  * searchindex
  * searchpattern
  * showif
  * snippeter
  * snippets
  * sqlite
  * tab
  * tabinclude
  * tag
  * tagalerts
  * templatepagename
  * testing
  * upgrade
  * var
  * webdavclient
  * wikipediasnippet
  * wrap
* [Browser] : 
  * Firefox 67.0
  * Opera 60.0.3255.151

**Comment by LotarProject** [comment]
I have tested this configuration with latest template version and have the expected behavior.
Your template version is v2019-05-22 ?

Joseph

**Comment by chtiland** [comment]
# Description

I updated from Dokuwiki, I had this problem on 4 dokuwiki installations (2 on a distant server, and 2 on a local server) and I encountered this problem on these 4 servers.

As I also had a fifth dokuwiki wich has not been updated since today, I decided to upgrade this one and then I update Bootstrap3 template, and this one has the expected behaviour. Note, this Dokuwiki is installed on the same distant server than previously mentioned.

So there's something wrong elsewhere.

# Checking some files
On a dokuwiki with problem, I open **template.info.txt** from bootstrap3 and I got this (extract) : 
`date     2019-05-22`

So, as it's the same date found on https://www.dokuwiki.org/template:bootstrap3 "Last updated on 2019-05-22", so Dokuwiki's extension manager doesn't mark it as "to update".

In bootstrap3 **manager.dat** I got this : 
`updated=Sat, 25 May 2019 09:25:35 +0200`

When having a look in RELEASED.md first date about release is : 
`## [v2018-05-22]`

Wich is quite different from the one I get today when downloading directly
`## [v2019-05-22]`


So is there a problem with extension manager ?

# What I also tried
(Note : No cache on server side installed - checked twice)

## First test 

Force Bootstrap3 template reinstall from update manager
With caches deletion, DW and Browser between each step (too much than really needed but who knows ?)

=> Still have tag on bottom

## Second : Full reinstall

1. Change template to default DW template
2. _Empty data/cache (DW and Browser)_
3. Remove bootstrap3 template
4. Check if folder /tpl/bootstrap3 is well deleted -> yes
5. _Empty data/cache (DW and Browser)_
6. Check if Dokuwiki default template is well applied -> yes
7. _Empty data/cache (DW and Browser)_
8. Installation of Bootstrap3 template
9. Set bootstrapTheme "Vanilla Bootstrap Theme"
10. Set tagsOnTop to yes.
11. _Empty data/cache (DW and Browser)_
12. Check if Boostrap3 template is well applied -> yes
13. Open a page with tags -> Tags are displayed on top -> OK
14. Back to Administration page
15. Set tagsOnTop to yes.
16. _Empty data/cache (DW and Browser)_
17. Open a page with tags -> Tags are displayed with header (h1/h6) -> NO at bottom. 

# So ? 

As it works on the last wiki I upgraded, may be a specific plugin ? But I use same plugins on the DW installation where there's no problem.

Here is a page where you can see tags at bottom (page.php is a copy of doku.php, but I also have this problem on private DW with doku.php)

https://www.chtiland.fr/page.php?id=informatique:logiciels:internet:firefox

I also still investigate on my side...

Thanks,
Fabrice

**Comment by chtiland** [comment]
I tried today, seems to be solved !
But problem I mentioned a few years ago in #95 is back... a link with #135 ?
