### ISSUE TITLE
Only the first page is printed out

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#427]
When I want to print out a wiki page by firefox, only the first page has content. After this there is a second page, but without any content. Further pages aren't processed

Steps to reproduce

1. Open a wiki quite long page
2. Print out

Versions
* 2019-05-22
* 2018-04-22b "Greebo"
* PHP version 7.1.19
* Firefox 67.0.4 (64-Bit)

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi @Juergen-aus-Koeln,
i have fixed this issue in master branch.

Please reinstall the template from Extension Manager.

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, it works

Best regards
Juergen

**Comment by LotarProject** [comment]
Thanks!
