### ISSUE TITLE
Bootstrap3 not shipped out on mobile device

### ISSUE THREAD

**Issue by fippu** [LotarProject/dokuwiki-template-bootstrap3#429]
### Description

I am using Bootstrap3 template on Dokuwiki v. 2018-04-22b "Greebo" with cerulean theme. It all works fine on the computer. However, on the mobile device, Dokuwiki does not display properly. When checking on Chrome with developer's mobile view, I can see that the style sheets are not included and class definitions (e.g. in body tag) are missing. Dokuwiki obviously ships its default template. 

### Steps to reproduce

1. Install and set up Bootstrap3 template with cerulean theme
2. Open page in Chrome and open Developer tools. 
3. Switch to mobile view and reload page. 
4. Go to elements tab. Body tag has no attributes. Bootstrap3 style sheets are not linked.
5. Go to the sources tab. It shows no files from lib/tpl/bootstrap3, but several files from lib/tpl/dokuwiki

**Expected behavior:** I would expect the page to be displayed in bootstrap3 template.

**Actual behavior:** Default template is used. Settings are not applied, e.g. the buttons at the bottom of the page (donate, css, html5 etc.) are disabled in bootstrap template, but they show up

### Versions

* Bootstrap3 2019-05-22
* 2018-04-22b "Greebo"
* PHP 7
* Chrome

**Comment by LotarProject** [comment]
Hi,
Seems a cache problem.

You can:
- send a screenshot of devtoos ?
- purge DokuWiki cache (via `http://<wiki address>/lib/exe/css.php?purge=true` and  `http://<wiki address>/lib/exe/js.php?purge=true` links)


Best regards,
Joseph

**Comment by fippu** [comment]
Thanks for the links to purge the CSS and JS cache. I did both, but it did not solve my problem.

I also attach two screenshots showing that the CSS is not linked, the body has no attributes and files are loaded from tpl/dokuwiki instead of tpl/bootstrap3.

![image](https://user-images.githubusercontent.com/52650214/60796342-78b2c600-a16d-11e9-93b5-ddd4d5dfc710.png)

![image](https://user-images.githubusercontent.com/52650214/60796431-a4ce4700-a16d-11e9-8fda-2cd01c826d6f.png)

**Comment by fippu** [comment]
Thanks for the links to purge the CSS and JS cache. I did both, but it did not solve my problem.

I also attach two screenshots showing that the CSS is not linked, the body has no attributes and files are loaded from tpl/dokuwiki instead of tpl/bootstrap3.

![image](https://user-images.githubusercontent.com/52650214/60796650-173f2700-a16e-11e9-8e1f-0cb9abe94b15.png)

![image](https://user-images.githubusercontent.com/52650214/60796659-1a3a1780-a16e-11e9-94c9-75385b74cf25.png)

**Comment by fippu** [comment]
I installed the LoadSkin extension. Now, when accessing the wiki through my mobile device, I have a dropdown allowing me to select a template. It defaults to Dokuwiki.

When I explicitly choose bootstrap3, the page reloads and the template is automatically switched back to Dokuwiki

**Comment by LotarProject** [comment]
Hi,
check `$conf['template']` in your `config/local.php`.

Joseph

**Comment by fippu** [comment]
`$conf['template'] = 'bootstrap3';`

This is also what the configuration interface says.

**Comment by LotarProject** [comment]
Loadskin work fine with Bootstrap3 template (via mobile and desktop).
Your DokuWiki is online ?

**Comment by fippu** [comment]
I know it should normally work fine. I will send you a link by e-mail.

**Comment by fippu** [comment]
Thanks to the tremendous help from @LotarProject, the issue is solved. The problem was related to the sectiontoggle plugin, where the `mobile_alt` option was set to `dokuwiki`.
