### ISSUE TITLE
Media Manager "Edit" Does Not Display Properly

### ISSUE THREAD

**Issue by johncourtland** [LotarProject/dokuwiki-template-bootstrap3#43]
First off, thanks so much for such an awesome template! This is an outstanding addition to the Doku Template inventory.
I am having an issue though when I open the media manager, and I then open an image, then I click on the "Edit" tab, and only half the dialogue is displaying. I am running the latest version of DW, and the latest version of this template. I have checked to see if the error is browser related and I am seeing the same thing with Opera, Firefox, IE, and Chrome, latest versions. I have cleared cache and cookies, in all browsers and the issue still persists.
This issue is present in fluid container and default width. 
Is this a bug, or a user error on my part? Thank you so much for looking into this.
John
![capture](https://cloud.githubusercontent.com/assets/12961228/8246707/039b8b86-15f8-11e5-8e0c-53ae900b989b.GIF)

**Comment by johncourtland** [comment]
Thanks Lotar! The world is right at this moment in time!
Great work and thank you once again for a wonderful product.

**Comment by LotarProject** [comment]
:)
