### ISSUE TITLE
Does not allow page editing

### ISSUE THREAD

**Issue by andreamarugeiro** [LotarProject/dokuwiki-template-bootstrap3#434]
### Description
After installing the template, page editing, wiki administration, the media manager stopped working ... any options that change anything in the wiki.
For example, I click to edit a page and it is blank.
To fix it I have to go back to the local.php file for the dokuwiki template.
[Description of the bug or feature]

### Steps to reproduce

1. [First Step] 
I installed the template through the extension manager
2. [Second Step]
I reloaded th Wiki
3. [and so on...]

**Expected behavior:** [What you expected to happen]
The template installed and working all functions
**Actual behavior:** [What actually happened]
Template installs but does not allow page editing, changes by dokuwiki manager
### Versions

* [Bootstrap3 Template]
2019-05-22
* [DokuWiki]
Greebo(2018-04-22)
* [Plugins]
Add New Page
archivegenerator
LDAP Auth
Autolink 4
ckgedit
Comment Synthax Support
Copy Page
Dw2PDF
edittable
FastWiki
fontcolor
Gallery
Icons
ifauthex
imgpaste
include
info
move
nspages
Pagelist
Pagenavigator
revert manager
safefnrecode
tag
dokuwiki upgrade
wrap

* [PHP]
PHP 7-2-19 Ubuntu 18.04.1
* [Browser]
Firefox 60.7.2esr
### Screenshots or Logs
![2019-07-26 11_59_33-Window](https://user-images.githubusercontent.com/42050655/61961031-19421c00-af9d-11e9-8614-c957654c67f2.png)
![2019-07-26 12_00_03-Window](https://user-images.githubusercontent.com/42050655/61961060-26f7a180-af9d-11e9-90b4-8c3423615c24.png)

[Paste your logs or attach the screenshot]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by LotarProject** [comment]
Hi,
can you send me the last line of Apache error_log ?

Thanks,
Joseph

**Comment by andreamarugeiro** [comment]
Hi, Joseph! 

![log apache](https://user-images.githubusercontent.com/42050655/62049733-3d446e00-b1e6-11e9-8b8e-28008d6f20ce.png)

**Comment by andreamarugeiro** [comment]
Hi, Joseph!
I discovered the problem... php-xml module missing. I installed the module and it worked.
Thank's!
