### ISSUE TITLE
White page after changing theme to bootstrap3

### ISSUE THREAD

**Issue by matze18888** [LotarProject/dokuwiki-template-bootstrap3#437]
### Description

If I install bootstrap3 on dokuwiki Release 2018-04-22b "Greebo", I get a white page on admin page or while editing articles.

Log of Lighttpd:

https://pastebin.com/RNHRRWZT

### Versions

* [Bootstrap3 Template] 2019-05-22
* [DokuWiki] Release 2018-04-22b "Greebo"
* [Plugins] all disabled
* [PHP] 7
* [Browser] All
![Anmerkung 2019-09-05 120510](https://user-images.githubusercontent.com/49388544/64332788-789c3e80-cfd5-11e9-9cff-02e37093f62a.png)

**Comment by LotarProject** [comment]
Hi,
seems a problem with SimpleXML PHP module.
Please check if you have "php-xml" package.

Regards,
Joseph

**Comment by matze18888** [comment]
php-xml is installed (its a docker image)

Best regards

Matthias

**Comment by vidschofelix** [comment]
i had the same, already had php-xml installed and had to install php7-simplexml aswell.

**Comment by matze19999** [comment]
Thanks @vidschofelix!! 
Will test it tomorrow and give feedback :)

**Comment by matze19999** [comment]
Unfortunately, it also doesn't work. 

But I think something is just wrong with my image...

**Comment by vidschofelix** [comment]
you could tell us wich docker container you use...

**Comment by matze18888** [comment]
Its a self made dockerfile, thats why this issue can be closed. I will use the official dockerfile now.
