### ISSUE TITLE
Template interpreting referer HTTP header as search query

### ISSUE THREAD

**Issue by jakubklimek** [LotarProject/dokuwiki-template-bootstrap3#438]
### Description

When I access any dokuwiki page on any dokuwiki using bootstrap3 and the HTTP request has `referer` HTTP header set to, e.g. `referer: https://www.google.com/url?q=https://opendata.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig` - this is what Google Forms does when a link to https://opendata.gov.cz/edu:konference:2019 is used - the page has words from the `https://opendata.gov.cz/edu:konference:2019` URL marked as search results, even though I did no search.
### Steps to reproduce

1. See [this](https://www.google.com/url?q=https://opendata.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig) example, or any dokuwiki using bootstrap3 such as
2. `curl https://wiki.bash-hackers.org/ -H 'referer: https://www.google.com/url?q=https://opendata.wiki.gov.cz/edu:konference:2019&sa=D&ust=1567692046621000&usg=AFQjCNG_0v_FF28O_RTQNJ0RZqqp49fGig' | grep mark`

**Expected behavior:** [What you expected to happen]
No search results marked with `<span class="mark">`

**Actual behavior:** [What actually happened]

Words from the `referer` header marked as `<span class="mark">`
### Versions

* [Bootstrap3 Template] in [DokuWiki] Release 2018-04-22b "Greebo"

### Screenshots or Logs

[Paste your logs or attach the screenshot]
![image](https://user-images.githubusercontent.com/718827/64346515-8ca26900-cff2-11e9-8b5c-399ef5f5f449.png)

**Comment by phy25** [comment]
Just want to make sure: This is not happening on other templates, right?

**Comment by jakubklimek** [comment]
@phy25 I checked 3 wikis with bootstrap3 (it is happening on all 3) and 2 with original template, including www.dokuwiki.org - where it is not happening. Not sure about other templates.

**Comment by LotarProject** [comment]
It's a DokuWiki functionality:

https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/common.php.source.html#l1462

The ``getgooglequery`` function parse the ``$_SERVER['HTTP_REFERER']`` variable and return the search term, for highlight the word in the wiki page.

Joseph

**Comment by jakubklimek** [comment]
🤔 ok, I will open the issue at DokuWiki then.
