### ISSUE TITLE
Problem with data plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#44]
Hi,

there is still a little problem remaining with the data plugin:

The code
```
====== Arens, Uwe ======

---- dataentry personendaten ----
Anrede:                Hr.
Nachname:              #####
Vorname:               Uwe
Bereich_tag:           Vertrieb
Abteilung_tag:         SL
Email_mail:            uwe.#####@#####.###
Telefon:               747
Personalfunktion:      Leitung Service
----
```
produces this output on screen:
![fehler](https://cloud.githubusercontent.com/assets/1800472/8248839/ddd31bf0-1663-11e5-9ec7-4361f66544da.png)

But this is the output when printing:
![fehler 2](https://cloud.githubusercontent.com/assets/1800472/8248841/e49e5972-1663-11e5-8b52-5d11a32bd5a3.png)

The red frames show informations of a help text bubble of the tag link that shouldn't be printed:
![fehler 3](https://cloud.githubusercontent.com/assets/1800472/8248844/e9d0b430-1663-11e5-8ee6-476ced6088d9.png)

Regards
Juergen

**Comment by LotarProject** [comment]
Hi! Sorry i have introduced this feature to print the DokuWiki page-id, but the same class ".wikilink1" is used by Data Plugin.

Regards,
Joseph
