### ISSUE TITLE
Media Manager displays blank

### ISSUE THREAD

**Issue by Digitalin** [LotarProject/dokuwiki-template-bootstrap3#45]
Hi Lotar, 

Since the last template update, media manager displays blank, when you call it  in edition mode. I have red the previous similar message, but here it is totally blank.

I repeat the issue with the local wiki  that worked properly before updating it. 
Can come back to the previous template, so it is not a problem for me but  if you need beta test before commit, as I have two wiki in local with your template and different plugin configuration :) 

I add a website in the Bootstrap3 dokuwiki page, not sure if it is the right place below Main. Please to move it if it is not. 

Thanks for all.

**Comment by vbrz** [comment]
I have the same issue :/

**Comment by Digitalin** [comment]
and investigating a little bit more, I deactivate all plugin to see but same issue :(

**Comment by Soeldner** [comment]
change

#mediamgr__aside {
position: absolute;

into 

#mediamgr__aside {
position: relative;

works 4 me. quick and dirty...

**Comment by Digitalin** [comment]
Now, it works but why ..? 
What I have done : rename bootstrap3 in bootstrap3.bak, upload the older one to replace it. 
Ok but lost the icons in the template and finally come back to the newest one, renaming with the right name and it works :) weird 
Something with the rights on files, perhaps ?

**Comment by LotarProject** [comment]
Sometimes it is a cache problem. During the development,  test and deploy in other DokuWiki installation, i empty the cache of DokuWiki and browser.

**Comment by Digitalin** [comment]
A good practice to keep in mind :)
I have noticed that the wrap plugin displays blanck now and there is an empty between its icon and the following (doesn't stuck, fit). Not sure that it is in relation with Bootstrap3 update, but on a other wiki where I haven't yet updated the template, there is no this issue.
