### ISSUE TITLE
not working with plugin explain

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#47]
Hi,

the plugin "explain" enables the possibility to enhance the acronyms functionality. But the tool-tip of this plugin isn't displayed in combination with the bootstrap3 template

Regards
Juergen

**Comment by LotarProject** [comment]
Hi! I have added the support for explain plugin in 2440fa0 commit.

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much for the rapid solution

Best regards,
Juergen

**Comment by LotarProject** [comment]
:+1:
