### ISSUE TITLE
Plugin WRAP with tabs

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#49]
Hi,

in the plugin WRAP the tabs function doesn't work. 
Example:
```
<WRAP tabs>
  * [[start|Allgemein]]
  * [[personal:richtlinien:start|Richtlinien]]
  * [[menue_themenbereiche|Firmenbereiche]]
  * [[menue_details|WIKI-Details]]
</WRAP>
```

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi! Now with this commit, Wrap Plugin Tabs have the same look-and-feel of Bootstrap Tab component.

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, it works.
(And I will test your Bootstrap Tab component soon.)

Best regards
Juergen
