### ISSUE TITLE
Namespace specific sidebar

### ISSUE THREAD

**Issue by neuralyzer** [LotarProject/dokuwiki-template-bootstrap3#51]
We're using your theme and it is really great. Is it possible to have different sidebars for different namespaces? For example if I add a page called "sidebar" to a namespace could that page be automatically used as sidebar for its namespace?

**Comment by LotarProject** [comment]
Hi! Thank you for using my template.
Yes, It's correct. You have the possibility to add different sidebar in different namespaces.
This template have the same behavior of default DokuWiki template.
