### ISSUE TITLE
[Suggestion] Translations should be perform via gettext instead of config files

### ISSUE THREAD

**Issue by nelson6e65** [LotarProject/dokuwiki-template-bootstrap3#54]
The translation job updating files via pull request is great, but it is hard sometimes. You can use code diff, but is not always clear as you expect and you have to re-compare line by line again. :disappointed:

Should be greatest if you implement it using [gettext functions](http://php.net/manual/en/ref.gettext.php) instead, setting a [domain](http://php.net/manual/en/function.bindtextdomain.php) for this template and using [dgettext](http://php.net/manual/en/function.dgettext.php) function.

Then, you can use the [Transifex](https://www.transifex.com/) localization platform to manage translations (or manually, whatever), making easier the translators job. :sunglasses:

**Comment by LotarProject** [comment]
Yes, sometimes it is difficult to compare during the merge :disappointed_relieved: .

Gettext is a library and generally is not installed by default in PHP, but more PHP projects (eg. PHPMyAdmin) use PHP-Gettext (https://launchpad.net/php-gettext/) a pure-PHP implementation of gettext.

At this moment, DokuWiki offer only this method for localization. DokuWiki have this site (http://translate.dokuwiki.org) for localization but is only for plugins and i hope in future a support for the templates.

Best regards,
Joseph
