### ISSUE TITLE
Ordered list overlaps image

### ISSUE THREAD

**Issue by Iwasntthere** [LotarProject/dokuwiki-template-bootstrap3#55]
I'm getting text overlapping an image when I use a left aligned image and an ordered list like this 

{{wiki:image.png?direct&150 }}
  - Step 1
  - Step 2
  - Step 3
  - Step 4

**Comment by LotarProject** [comment]
Hi!
Please send me a screenshot to see the unexpected behavior.

I have replicated your syntax in my DokuWiki installation, and this is the results:

##### Default DokuWiki template:
![image](https://cloud.githubusercontent.com/assets/1824717/8661241/8ea1bcec-29b6-11e5-8a1e-bb6980b1ba58.png)

##### Bootstrap3 Template:
![image](https://cloud.githubusercontent.com/assets/1824717/8661255/b0a3292a-29b6-11e5-82da-7ff34119301c.png)

It's the same behavior ?

Best regards,
Joseph

**Comment by Iwasntthere** [comment]
Whoops it appears I pasted an unodered list instead of an ordered one but it is the same issue. I'll admit I forgot to try the default template before posting. 

Default DokuWiki template:
![](http://i.imgur.com/Q4LawCD.png)

Bootstrap3 Template:
![](http://i.imgur.com/ZggfRzl.png)

**Comment by selfthinker** [comment]
Here is a little background info and the history how I tried to fix this general problem in the old and new default templates and gave up in the end: https://bugs.dokuwiki.org/index.php?do=details&task_id=1950
Please note, even Wikipedia still has that problem and hasn't found a way to fix it yet.

**Comment by LotarProject** [comment]
Hi! This behavior is resolved in last template release.
