### ISSUE TITLE
Plugin move support

### ISSUE THREAD

**Issue by neuralyzer** [LotarProject/dokuwiki-template-bootstrap3#57]
It would be nice to support the plugin move. There could be an item in the drop down menu as it has been added for the plugin export PDF.

**Comment by LotarProject** [comment]
Hi! I have created a pull request to plugin mantainer to add the plugin support for my template.

I have tested the integration and this is the results:

![image](https://cloud.githubusercontent.com/assets/1824717/8837867/094c20a4-30c9-11e5-8db8-27b8d21ab6c2.png)

I'm to work to add an icon.

Best regards,
Joseph

**Comment by LotarProject** [comment]
The author have integrated your plugin with Bootstrap3 Template,

**Comment by neuralyzer** [comment]
Maybe I'm doing something wrong. I can't see the "Rename page" item.

**Comment by LotarProject** [comment]
Sorry, the author did not merge my PR.
If you want to use this plugin with my template use my fork repository.

At your disposal.
Joseph

**Comment by neuralyzer** [comment]
Thanks. Great!

**Comment by naamaan** [comment]
Hi, thanks for the great template.
I'm newly installed the dokuwiki and really liked the rename option in the user page, do you think it's a matter of time till they merge this feature? or it's finished issue, they don't want it?
Regards

**Comment by LotarProject** [comment]
Hi! The "move plugin" author have merged my PR.

**Comment by neuralyzer** [comment]
Works like a charm!
