### ISSUE TITLE
Performance in combination with other plugins

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#59]
Hi,

the performance of the template could be a little bit better in combination with some plugins:

a) The tab function of the wrap plugin:
If a page contains tabs of the wrap plugin, first for a short time these entries are displayed as an unordered list. And only after it the tabs are generated in the screen output.

b) Output of a datatable with the data plugin:
A page with a data table is firstly shown as a list without formatting. Only subsequently the formatting is done, so that the page is displayed correctly. This behaviour can also be observed with large tables.

These point are not essential for the use of the template. But it would be better, if the output were done correctly right from the start.

Best regards
Juergen

**Comment by LotarProject** [comment]
Hi! Is not essential but is a problem.

For this problem i "may" have found a solution to optimize the JS-Template-Engine:

Before the optimization:
![image](https://cloud.githubusercontent.com/assets/1824717/8788110/60cbb390-2f38-11e5-88d1-9e46ce809cd2.png)

After the optimization:
![image](https://cloud.githubusercontent.com/assets/1824717/8788134/925711a2-2f38-11e5-96e7-dfcd288c5dd7.png)

This is two images from the profiling of the page ":wiki:syntax". With the optimization the page is 306ms faster (~53%).

I think to create a "dev" branch to test if this optimization works or make other problems.

Stay tuned ;)

Best regards,
Joseph
