### ISSUE TITLE
Breadcrumb and YouAreHere display error

### ISSUE THREAD

**Issue by SchulSkripts** [LotarProject/dokuwiki-template-bootstrap3#60]
I think there is an display error between the breadcrumb an youarehere line.
![bildschirmfoto 2015-07-20 um 17 15 20](https://cloud.githubusercontent.com/assets/4860984/8779318/1f4ba6ee-2f03-11e5-9ae4-a56b80fa4613.jpg)

**Comment by LotarProject** [comment]
Hi! I have fixed a similar bug in a12fefe commit. Please download latest version of template and flush the DokuWiki cache (and browser cache).

Best regards,
Joseph

**Comment by SchulSkripts** [comment]
Thank you for your response. I've loaded the latest version and flushed the cache but the second line is still intended (in Google Chrome, Safari and Firefox).
I've noticed that without javascript (JS forbidden) both lines are aligned left, which is correct.

**Comment by SchulSkripts** [comment]
Works like a charm.

Thank you!
