### ISSUE TITLE
Problem with encoding.

### ISSUE THREAD

**Issue by legend2360** [LotarProject/dokuwiki-template-bootstrap3#61]
This problem appeared after fa7215579ea10f00d329622fc4d21097fbeca4fa commit and is associated with encoding with russian symbols. It's appears in sidebar, admin-panel(there navigation bar of settings), list of page sections, etc.

**Comment by LotarProject** [comment]
Hi! Can you send a screenshot?
Thanks

Best regards,
Joseph

**Comment by Juergen-aus-Koeln** [comment]
I think I have the same problem:
![schuemmer-2015-07-23 09_16_29-schutte-wiki-hauptmenu test-wiki](https://cloud.githubusercontent.com/assets/1800472/8845053/a2e6701e-311b-11e5-9cad-eaf86204d3a9.jpg)

Best regards
Juergen

**Comment by HavocKKS** [comment]
I have the same problem but on TOC...
Investigating... :)

**Comment by LotarProject** [comment]
Thanks to all for investigating the problem. The problem was only for non-Latin language i have added a utf-8 encoding to solve this inconvenience.

**Comment by Juergen-aus-Koeln** [comment]
For me, now it works again. Thank you for your quick solution

Best regards
Juergen

**Comment by legend2360** [comment]
Thank you.
