### ISSUE TITLE
Template Modification Question

### ISSUE THREAD

**Issue by NoriSilverrage** [LotarProject/dokuwiki-template-bootstrap3#63]
Not sure where questions for help go...

I really like your template but I wanted to add a edit this page button in the top navbar.
I edited the navbar.html file and added: 
<li>
	<?php tpl_action('edit',1)?>
</li>

This has the desired effect of adding the edit option, but I have two issues with it. One, I'm not sure if this is the same edit action as the one in the tools menu. It seems to work, but I just want to make sure I'm doing it right.
The other issue is that I can't figure out how to add the glyphicon icon inline with the edit button as you do for the home button.

Any help on this would be great.

**Comment by HavocKKS** [comment]
Maybe you could use this :

```html
<li>
	<?php echo _tpl_action_item('edit', 'glyphicon glyphicon-pencil')?>
</li>
```

I used function declared in the template.

**Comment by NoriSilverrage** [comment]
Nice! That seems to work. 
One more question. I'm trying to link to the sitemap. I can use the following just fine, but is there a way to grab just the sitemap?
<?php tpl_link("url", '<i class="glyphicon glyphicon-xyz"></i> Sitemap') ?>
Say like this link:
  <?php tpl_link(wl(), '<i class="glyphicon glyphicon-home"></i> Home') ?>
But instead of the wl() something that links to sitemap.

**Comment by HavocKKS** [comment]
This will work, in fact it's used for the Sitemap link in the dropdown (the one in the navbar)
```php
_tpl_action_item('index',  'glyphicon glyphicon-list') // Will take you to the sitemap
```

In dokuwiki style :
```php
 <?php tpl_action('index')?>
```

Note that tpl_link() will only build a link. So if you provide à URL it will work too.
```php
<?php tpl_link("*http://your_sitemap_url*", ' Home') ?>
```

**Comment by NoriSilverrage** [comment]
Spot on. Thanks for the help!
