### ISSUE TITLE
All Wiki pages and Configuration Settings are blank

### ISSUE THREAD

**Issue by quix117** [LotarProject/dokuwiki-template-bootstrap3#65]
After updating to the latest version of bootstrap3, all wiki pages and the Configuration Settings page are blank for me with this template. I've disabled all extensions and still had this problem. Every other template that I've tried is working for me. I am using Dokuwiki Release 2014-09-29d "Hrun". I was able to use bootstrap3 before I updated. I have tried uninstalling and using the manual install option.

![capture](https://cloud.githubusercontent.com/assets/7058227/8966871/bf6c1ea6-3601-11e5-9042-7fcb90e66c72.PNG)

**Comment by quix117** [comment]
Just tried reinstalling Dokuwiki over my previous installation (overwriting files and going to install.php). Still have the same problem.

**Comment by LotarProject** [comment]
Hi! You use a sidebar ?

**Comment by quix117** [comment]
Yes, removing the sidebar fixed the problem. Am I formatting it wrong, or do I need to configure something else?

**Comment by LotarProject** [comment]
Please, you can send me the sidebar code ?

**Comment by quix117** [comment]
It was just a placeholder sidebar, as I'm still setting up the wiki. Even just having "test" as the sidebar makes the page blank.

**Comment by LotarProject** [comment]
If you have a personal webserver and possibility to read the Apache "error_log", place an empty file called "report_e_all" inside the DokuWiki "conf" directory and send via mail the log to investigate this problem.

**Comment by quix117** [comment]
Turns out that it was a problem on my end. I was getting a "Class 'DOMDocument' not found" PHP error, and [this](http://gistpages.com/2014/03/7/php_fatal_error_class_domdocument_not_found) fixed it.

Thanks for the quick support, though!

**Comment by LotarProject** [comment]
Hi! For not rewrite many DokuWiki functions and increase client-side performance, the TOC and Sidebar uses DOMDocument class to manipulate the DOM on server-side.

**Comment by Soeldner** [comment]
the same problem here. I sent you an email with screenshots and logs.

**Comment by Soeldner** [comment]
good job! Thank you for the fast reaction.
