### ISSUE TITLE
Make search bar optional

### ISSUE THREAD

**Issue by polyzen** [LotarProject/dokuwiki-template-bootstrap3#66]
I have the contents of my wiki hidden unless you log in. Nothing can be found from the search bar.

It would be great if there was an option just like showTools: Never/When Logged In/Always

Edit: Also, I never use the search bar.. maybe should

**Comment by polyzen** [comment]
Wow, thanks for the quick work. Beat me to the punch

**Comment by polyzen** [comment]
Maybe there should be a greyed-out option. The navbar looks weird to me with nothing on the right https://ptpb.pw/_gj6.png

**Comment by LotarProject** [comment]
Hi! I have replicated this issue and i have the same behavior only when the option "showTools" is on "never" or "logged".

**Comment by polyzen** [comment]
Right; it might be nice to have a greyed-out/disabled option for showTools as well
