### ISSUE TITLE
Compatibility to Dokuwiki Release 2015-08-10 "Detritus"

### ISSUE THREAD

**Issue by duenni** [LotarProject/dokuwiki-template-bootstrap3#69]
Hi,

is this template yet compatible to DokuWiki 2015-08-10 "Detritus"?
Thanks!

**Comment by LotarProject** [comment]
Hi! Yes, it's compatible with new "Detritus" version.

In the previous commit, i have introduced some feature of "Detritus":
  - Removed IE7 support
  - Page references in media detail

One feature present in my template is introduced in "Detritus": changed all submit buttons from input to button.

Best regards,
Joseph

**Comment by BsNoSi** [comment]
Is there a setting to render german umlauts correctly in sidebar and content dropdown? 

Example: "Tastenkürzel" renders in page index to "TastenkÃ¼rzel", "Pläne" in sidebar to "PlÃ¤ne"

Other templates do well.

**Comment by LotarProject** [comment]
I have created a new commit and new branch (develop) to solve the issue on sidebar and/or toc for non-latin language.

**Comment by BsNoSi** [comment]
Works fine! Thank you!

**Comment by polyzen** [comment]
This can be closed

**Comment by LotarProject** [comment]
:+1:
