### ISSUE TITLE
Possibility to implement a landing page

### ISSUE THREAD

**Issue by pascalschulthess** [LotarProject/dokuwiki-template-bootstrap3#70]
Hi,

is it somehow possible to precede the start page with a landing page? By that I mean just something easy with a big image, a logo and a little text.

Thanks for the help.

-pascal

**Comment by LotarProject** [comment]
Hi! Do you intend disable "temporarily" the sidebars, for start pages? Or remove the panel around the page?

Best regards,
Joseph

**Comment by pascalschulthess** [comment]
Yes, something like that. Basically, I'm looking for a page only harboring the top navigation bar and then one container with a logo, large text and optionally an image as background.

**Comment by pascalschulthess** [comment]
Wow, that was fast. Great! Thanks!
