### ISSUE TITLE
Problem with TOC

### ISSUE THREAD

**Issue by d1p406** [LotarProject/dokuwiki-template-bootstrap3#74]
Hello. Thank you for this nice plugin! I installed it last week and now I'm trying to add links on the navbar.

I have a problem with TOC behaviour. When window width is resized smaller and the navbar uses over two lines, the TOC is not displayed. 
There are some links on the navbar so when the window width is made smaller, the search form moves to next line, which means it moves to under the links.
In this situation, I cannot find the TOC. It seems to hide behind the navbar.
fixedTopNavbar option's value is true in my setting and it's happened at Google Chrome.

![picture1](https://cloud.githubusercontent.com/assets/14065372/9596475/479fcdea-50b0-11e5-9ad2-973e403741fd.JPG)

![picture2](https://cloud.githubusercontent.com/assets/14065372/9596477/4c536e96-50b0-11e5-8204-30a53ea97d69.JPG)

I wonder if you could tell me how to fix it.
Sorry about my poor English and thanks again for your creative work!

**Comment by LotarProject** [comment]
Hi! I have added a workaround to fix the TOC visibility. Thanks to reporting this issue.

**Comment by d1p406** [comment]
Thank you for fixing the issue. Now I can see the TOC!

Sorry I have another question related to this issue.

Is it possible to get the navbar height and change the position of "body"?
I found that "youarehere" is also not displayed in that situation (when the navbar uses over two lines). Sometimes the navbar hides the first heading too.
I tried to edit <head><style> part in main.php to move the position by following window width but it was difficult because all themes have different fontsize and the height of the navbar.

Could you tell me any advise about it?

Thank you.

**Comment by d1p406** [comment]
Thank you for fixing the issue. Now I can see the TOC!

Sorry I have another question related to this issue.

Is it possible to get the navbar height and change the position of "body"?
I found that "youarehere" is also not displayed in that situation (when the navbar uses over two lines). Sometimes the navbar hides the first heading too.
I tried to edit <head><style> part in main.php to move the position by following window width but it was difficult because all themes have different fontsize and the height of the navbar.

Could you tell me any advise about it?
Thank you.
