### ISSUE TITLE
2015-08-10a "Detritus" and current bootstrap3 template

### ISSUE THREAD

**Issue by Funkoverload** [LotarProject/dokuwiki-template-bootstrap3#75]
Hi, 

I have installed a fresh dokuwiki 2015-08-10a "Detritus" and installed the bootstrap3 template, but it seems not to work as it cannot find jQuery (Firefox Console: Error: Bootstrap's JavaScript requires jQuery). Seems that it is not compatible with most recent 2015-08-10a "Detritus" release, any idea?  

Best,
Nils

**Comment by motp** [comment]
Same here (2015-08-10a Hotfix installed) . 
The Page is almost blank, except for logo and home button. 

JS Console Messages:
-----------------------------
SyntaxError: missing ; before statement js.php:24:97809
Error: Bootstrap's JavaScript requires jQuery bootstrap.min.js:6:36

**Comment by aspatric** [comment]
Same here - freshly installed DokuWiki (2015-08-10a Hotfix)

**Comment by Funkoverload** [comment]
Thank you, now it workes perfectly!
