### ISSUE TITLE
Compatibility Jorgchart plugin 

### ISSUE THREAD

**Issue by martk70** [LotarProject/dokuwiki-template-bootstrap3#76]
Not a high prio issue, but this plugin is a quick and useful way to turn a text into a grapic.
https://www.dokuwiki.org/plugin:jorgchart

It seems the template detects the plug-in code has a table inside and therefore throws general template rules into it (distances between rows) which results in disconnections. 

It would be nice if this could be improved - or should I contact the Jorgchart plugin writer?

**Comment by LotarProject** [comment]
Hi! I have added just now an "hack" to integrate jOrg Chart in the template.

Best regards,
Joseph

**Comment by martk70** [comment]
Thanks!

	

	I will check it out. I am using your template and the bootswrapper plugin at my office-intranet to share information with some colleagues. They are a great addition to Dokuwiki, thank you! Very much apart from that I plan to have another personal website with your template - I'll keep you informed.

	

	Regards,

	Martin

	

	 


	Martin van der Knijff, Gouda

	http://www.mvak.nl

	0182-537217




----- Original Message ----

From: Giuseppe Di Terlizzi 

To: LotarProject/dokuwiki-template-bootstrap3 

Cc: martk70 

Sent: Din, 15 Sep 2015 15:44

Subject: Re: [dokuwiki-template-bootstrap3] Compatibility Jorgchart plugin (#76)




	Hi! I have added just now an "hack" to integrate jOrg Chart in the template.

	Best regards,

	Joseph

**Comment by LotarProject** [comment]
:+1:
