### ISSUE TITLE
Dropdown menu not showing

### ISSUE THREAD

**Issue by alexisbory** [LotarProject/dokuwiki-template-bootstrap3#77]
Hi,
On a 2015-08-10a updated dokuwiki an a fresh install of bootstrap3 2015-09-06 :
With Google Chrome and Iceweasel, the menu dropdown don't show when clicked :
  See http://fablab.web-5.org
Browser console says : Uncaught Error: Bootstrap's JavaScript requires jQuery - bootstrap.min.js:6

I'm not sure it's bootstrap3 fault, but every thing else is fine on the web site.

**Comment by alexisbory** [comment]
By the way, there is also a problem with tables --> no borders at all :-/

**Comment by LotarProject** [comment]
Hi! I have solved this issue in 6fe05df commit (see #75 issue).

**Comment by alexisbory** [comment]
I checked the 2 involved files and well, and yes, as mentioned above, I allready have 2015-09-06. Now I'm reverting to the standard template and will probably install (if time permits) a new VH with a completly fresh install so to check if the problem occurs again.
Thanks Giuseppe for your attention,
Alexis

**Comment by LotarProject** [comment]
Hi! Please clear the browser cache and purge the DokuWiki JS (via ``/dokuwiki/lib/exe/js.php?purge=true`` url).

At your disposal,
Joseph
