### ISSUE TITLE
TOC Enhancements.

### ISSUE THREAD

**Issue by Rojoss** [LotarProject/dokuwiki-template-bootstrap3#78]
Currently the TOC isn't very nice in my opinion.
For example that it closes when you scroll down and up again.
It should be an setting that the TOC will remained opened if it's opened and remain closed if it's closed.

It should also be a setting that the fixed TOC gets the opened/closed state from the static TOC.
So if I open the TOC on the page and then scroll down that the TOC stays open.
And then when I scroll up again that the TOC will be opened on the page.

Currently when you open the TOC scroll down it will close the TOC.
And even when you scroll back up the TOC remains closed.

I would just like some more control for the TOC because the current layout isn't that great in my opinion.
It's there to make navigation easier but having to click on it to open every time doesn't make it much faster compared to just scrolling down.

It would also be great that it shows all other headings when you hover over a heading.
Pretty much like what happens when you scroll down but then when you hover over a link/button in the TOC menu that it shows all sub headers.

**Comment by blacklord049** [comment]
This is a good idea. It would also be nice to have a setting that allow to get a closed TOC when opening a page.

**Comment by hvarga** [comment]
I can also agree on this.

**Comment by tysoncecka** [comment]
I'd like to add my vote for features like these. The TOC is especially hard to deal with on mobile devices (where it could potentially be very useful) in that it will auto-collapse too soon and disturbs the page flow a great deal when it does if there are a lot of sections. 

As a quick fix I set it to not disturb the rest of the page on mobile, but I would rather have the option to start collapsed.
` @media only screen and (max-width: 640px) {
   body.lumen #dokuwiki__toc_wrapper.affix-top {
   	position: fixed;
   }}`

**Comment by issmirnov** [comment]
Could we extend the same logic to the admin menu? See #200

**Comment by teatall** [comment]
I still think the current TOC could be better if it could be integrated into nav#dw__pagetools and made into a popover element as in [Bootstrap3](https://getbootstrap.com/docs/3.3/javascript/#popovers). What do you think?
