### ISSUE TITLE
Anchors with fixed header.

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#79]
When setting the header/navbar to fixed going to a bookmark/anchor it overlaps.

This is what happens now:
http://i.imgur.com/wEi22Mh.png

And it should be like this:
http://i.imgur.com/Ag9GoSz.png

**Comment by LotarProject** [comment]
Hi! The Bootswatch themes use differents navbar height from the default Bootstrap theme. I prepared a patch to solve this behavior.

Stay tuned ;)

**Comment by worstboy32** [comment]
Alright great to hear that this can be fixed. :)

**Comment by worstboy32** [comment]
I've updated but it doesn't seem to be fixed.
For example this URL:
http://mc-essence.info/meta#books
It will still show like this:
http://i.imgur.com/cCHdfFb.png
