### ISSUE TITLE
Theme switcher menu displays empty even when disabled.

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#81]
I've disabled the option to switch themes.
However, it still shows a little icon and when you click on it you get a empty menu.
Here is a screenshot of it including the settings.
http://i.imgur.com/CTvQgGG.png

I've also tried to select hide on all themes but that didn't make any difference.

**Comment by LotarProject** [comment]
Hi! I have replicated your configuration in a fresh DokuWiki installation, but i don't have the same behavior :(
I have already fixed the other bug of theme switcher. Now in my next commit, the menu will be automatically hidden if you disable all themes.

**Comment by worstboy32** [comment]
Hm strange..
It only happens when having split tools selected.
If collapsed in one menu it's working fine for me.

tpl»bootstrap3»individualTools
Split the Tools in individual menu in navbar

You can see it on my wiki here if that helps:
http://mc-essence.info/doku.php/start

**Comment by worstboy32** [comment]
Can confirm that it's fixed.
Thanks!
