### ISSUE TITLE
Icons on buttons with external links.

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#82]
When creating a button with a external link it will add the globe icon even if you specify another icon.
I think the globe icon should be removed if another icon is specified for the button.
If this can't be done the globe icon should at least have the same color formatting as other icons because right now it looks really odd.
http://i.imgur.com/tmu1z3g.png

**Comment by LotarProject** [comment]
Hi! Are You using the "Bootstrap Wrap" plugin ?
Please send me a snippet of the code.

Best regards,
Joseph

**Comment by worstboy32** [comment]
Yeah I do indeed.
This is the code without an extra image:
<button type="warning">[[http://mc-essence.info|Support]]</button>

And with a image:
<button type="warning" icon="glyphicon glyphicon-console">[[http://mc-essence.info|Support]]</button>

Those links are just placeholders for now.
