### ISSUE TITLE
Nav bootstrap element in sidebar not behaving properly.

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#84]
There are some bugs with the navbar element when using it in the sidebar.
http://i.imgur.com/TPTOqjy.png

First of all when switching to another page it doesn't make the link active.
Some times a link/button turns active but then it's not even the correct page.
I expect it to be when I go to the commands page that the commands link/button turns dark.

Secondly when using sub menus (dropdown) they don't display at all.
It just displays the dropdown item as text and you can't click it or anything.
All sub menus that would be in the dropdown just disappear completely.

I would love to see some enchancements for the navbar in general.
Like it would be great that if you have a button for a namespace that the button text changes when you switch to another page in the same namespace. But the button would stay active all the time and when clicking on it you would go to the main page of the namespace still.
Maybe even display it like namespace > page or something.

Would also be great if we can put the TOC inside the navbar like <toc></toc>

And some other things like breadcrumbs/trace <crumbs amount="5"></crumbs>
And the you are here path maybe <path></path>
Just more customization for the sidebar would be great.
Maybe it's already possible but I couldn't find any of this.

**Comment by LotarProject** [comment]
Hi! To solve the first problem, add in your "sidebar" page the macro ``~~NOCACHE~~``

This macro disable the DokuWiki cache for a page. This macro is useful for the sidebar because for each "click", you have a fresh sidebar.

For the other enhancements ... stay tuned.

**Comment by worstboy32** [comment]
Alright good to know. Thanks!

**Comment by LotarProject** [comment]
:+1:
