### ISSUE TITLE
Possible to remove doku.php from the url?

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#85]
Currently the link is like:
http://mc-essence.info/doku.php/start

Is it possible to have the link without the doku.php bit like so?
http://mc-essence.info/start

Makes the link a bit shorter for displaying it elsewhere.

**Comment by LotarProject** [comment]
Hi!

For remove the "doku.php" from the  links, set the DokuWiki option, "userewrite" to ".htaccess" (see "http://www.dokuwiki.org/config:userewrite" and "https://www.dokuwiki.org/rewrite#option_1web_server" for more information).

Best regards,
Joseph

**Comment by worstboy32** [comment]
Thanks!
I'll have a look at that.

**Comment by LotarProject** [comment]
:)
