### ISSUE TITLE
bootstrap3 not respecting pixel width in "datatable" of structured data plugin

### ISSUE THREAD

**Issue by virk** [LotarProject/dokuwiki-template-bootstrap3#86]
If "dynfilters: 1" is set and pixel width of the individual columns of a "datatable"-order is given, bootstrap3 does not respect these widths but shows all the columns with same width (, while dokuwiki-template respects these widths well).
I do not know whether this is related to bootstrap3 or something else, but I consider this as a bug somewhere.

**Comment by LotarProject** [comment]
Hi! This is a default behavior of Bootstrap. Bootstrap uses the 100% of width of the page size. To use the default DokuWiki behavior, disable the option "tableFullWidth" in configuration manager.

Best regards,
Joseph

**Comment by virk** [comment]
Hi! You are right :-), but I think that is not what I am talking about. Up to now this behavior, what I consider a bug wherever, has only appeared with the combination of plugins given in my 1st post.

BTW: Very good work in my point of view; congratulations!
