### ISSUE TITLE
Updating the template/plugin. Logo, favicon and other modifications.

### ISSUE THREAD

**Issue by worstboy32** [LotarProject/dokuwiki-template-bootstrap3#87]
I'm not sure if this is something that can be done or maybe I'm just doing something wrong.
But basically every time I update the template all the modified files get reset to default.

For example the logo and favicon change back to the dokuwiki one.
And I modified the navbar to have a different link than home since clicking on the icon/title already sends you to the home page. This also gets resets every time I update the template.

Am I  doing something wrong with updating or is this normal behaviour for templates on DokuWiki?
If it is it would be awesome if you could find a way to solve this so that updating can be done a bit easier. For example things like the title remain through updates.
I assume this is some sort of configuration setting that can be saved but maybe you could have a setting for logo and favicon too and have that saved?
Again, I'm completely new to this wiki system so I have no clue how everything works but it would be great.

**Comment by LotarProject** [comment]
Hi! This template uses the DokuWiki standard configuration for logo and favicon. To preserve the logo and favicons i suggest to use the media manager:

 (excerpt from https://www.dokuwiki.org/template:dokuwiki)
  * The site's logo
    * :wiki:logo.png
    * :logo.png

  * The favicon
    * :wiki:favicon.ico
    * :favicon.ico

  * The bookmark icon used by Apple and Android devices
    * :wiki:apple-touch-icon.png
    * :apple-touch-icon.png

For the navbar i'm working for another solution (see #91)

Best regards,
Joseph
