### ISSUE TITLE
Have a pop-up-index in the top bar

### ISSUE THREAD

**Issue by virk** [LotarProject/dokuwiki-template-bootstrap3#88]
It would be nice, if a pop-up-index would be integrated in the top bar somewhere and somehow. There would be one button, f.e. like the "Administration"-triangle, which opens, when it is clicked and present the top index structure of the wiki. Namespaces are indicated with a triangle. Going there this namespace is opened an so on; just a "normal" index file like in many operating systems for to navigate through directories and files. Some templates like wallpaper (as far as I remember) have already got it.
Having such an index in the top bar, we could avoid the sidebar, which we only need for to navigate through our wiki. Avoiding the sidebar gives more space for content.

What do you think of that idea?

**Comment by LotarProject** [comment]
Hi! I have implemented this,

![schermata1](https://cloud.githubusercontent.com/assets/1824717/10023328/d5911e2c-6151-11e5-9e55-611d8f36f0a9.png)

a drop-down menu with a DokuWiki page.

In this sample i have created a simple page with "Bootstrap Wrapper" plugin to create the columns and "Include" plugin to include a first section of ":wiki:dokuwiki" page and some page links.

I have tested this implementation with different plugins for create a page with namespace lists: nspaged, page list, etc.

![schermata2](https://cloud.githubusercontent.com/assets/1824717/10023652/6d742472-6153-11e5-96b6-8975fc1fee4f.png)

My idea is to create a personalized menu (eg. for every namespace -- like the sidebar) and use specific plugin to create the index of pages.

Best regards,
Joseph!

**Comment by virk** [comment]
Can I already make use of the above. If yes, can you explain, what to do to get a drop-down-page with f.e. the "simplenavi" or the "indexmenu"-plugin?

**Comment by LotarProject** [comment]
It's a simple page. This is the code for the first image:

````
====== Drop-Down Page ======
<row>
<col sm="4">
** Main **
  * [[:start|Home]]
  * [[:playground:playground]]

</col>
<col sm="4">
** DokuWiki **
  * [[:wiki:syntax]]
  * [[:wiki:welcome]]
  * [[:wiki:dokuwiki]]
</col>
<col sm="4">
{{page>:wiki:dokuwiki&firstseconly&nofooter&noheader&inline}}
</col>
</row>
~~NOCACHE~~
````

This is the code for the second:

````
====== Drop-Down Page ======

<nspages :wiki -subns -r>

~~NOCACHE~~
````

**Comment by LotarProject** [comment]
This feature is implemented in my last release. To enable this feature is necesary create a new DokuWiki page called ``:dropdonwpage`` in your preferred namespace location.

**Comment by foosa18** [comment]
How can I create multiple dropdown page on navbar with multiple subsections under it?

**Comment by lexmoe** [comment]
it's possible multiple dropdownpages?

**Comment by UlviShukurzade** [comment]
> it's possible multiple dropdownpages? Would you have some examples?

hello. were you able to do multiple dropdowns? or is it possible to adjust its place?
