### ISSUE TITLE
Support custom menu items with event TEMPLATE_PAGETOOLS_DISPLAY

### ISSUE THREAD

**Issue by jan-tee** [LotarProject/dokuwiki-template-bootstrap3#90]
The template is great but it seems it does not support TEMPLATE_PAGETOOLS_DISPLAY, which menas that plugins like [move](https://www.dokuwiki.org/plugin:move) are not well integrated or easily available for users.

**Comment by LotarProject** [comment]
Hi! This template uses this event since the first commit. Move plugin use this event but is limited for a few templates. I have created a PR few week ago, but is not merged!

At your disposal.

Best regards,
Joseph

**Comment by LotarProject** [comment]
If you want to use this plugin with my template use my fork repository.

**Comment by polyzen** [comment]
It has been merged.
