### ISSUE TITLE
Navbar as a DokuWiki page (like sidebar)

### ISSUE THREAD

**Issue by LotarProject** [LotarProject/dokuwiki-template-bootstrap3#91]
Hi! I'm testing a new solution for the NavBar. Now the NavBar is a static hook, placed in ``<dokuwiki>/lib/tpl/bootstrap3/navbar.html``.
My idea is extend this hook using a standard DokuWiki page with the unordered-list of links (internal or external) like a sidebar page.

```
  * {{fa>home}} [[:start|Home]]
  * [[:foo:start|Foo]]
  * [[:wiki:syntax]]
~~NOCACHE~~
```

This solution offer two benefits:
  * Use DokuWiki to edit the NavBar
  * Create differents NavBar for differents namespaces

Do You like ?

Joseph

**Comment by virk** [comment]
Have a closer look at my #88, where I described, that a popup-index/menu would be of great benefit.

**Comment by Digitalin** [comment]
Hello Joseph, 
What a good idea !
First of all, end of rewrite navbar.html after a Bootstrap3 's update seems a nice upgrade. Moreover, the idea to have different menu by namespace also is attractive. I am used to create submenu for private namespace with plugin include. :privatenamespace:menu thats of course follows the ACL. So, it could be easier to do that way. In this range of ideas, it would be nice to easily create sub menu (and sub sub menu) from a dokuwiki page. 
Cheers.

**Comment by HavocKKS** [comment]
I second that ! It's a great idea !

**Comment by LotarProject** [comment]
Hi! in my last release it's possible to create e submenu directly via the ``:navbar`` hook/page:

````
  * [[:start|Home]]
  * DokuWiki
    * [[:wiki:welcome]]
    * [[:wiki:syntax]]
    * [[:wiki:welcome]]
  * [[:playground:playground]]
~~NOCACHE~~
````

This sample create three navbar items (Home, DokuWiki and Placeholder) with a submenu (DokuWiki).

![bootstrap3-navbar](https://cloud.githubusercontent.com/assets/1824717/10396700/34501cd8-6ea4-11e5-88d2-f82fa8558c09.png)

**Comment by Digitalin** [comment]
Cool, you are an angel, so fast one can't see, just sensing of one's wings movement :-)
I am going to try it on local wiki and come back. I suppose you remove the navbar.html from /lib/tpl/bootstrap3/
Is already implemented the possibility to do so for separate namespace ? 
: navbar for :start 
:private:navbar for private:start
:other:navbar for other:start
keeping a start for each namespace as the hook follows the configuration. 

I imagine something like [[:start|{{start:imagehome.png}}]] should work. 
As I am not far to wiki farm, which is a new step for me, this feature empowers new possibilities really great before diving in a new world with animals.
Thanks for your job in the Dokuwiki community. A Latin creative touch with German rigor :dancer:

**Comment by LotarProject** [comment]
:blush:

The support of ``navbar.html`` hook is still present because many people have customized and remove it would give problems. But if you want to try the new navbar you can remove it.

Yes, it's possible create navbars for separate namespace (``:navbar`` for ``:*``, ``:wiki:navbar`` for ``:wiki:*``, etc).

The icons and image are supported. For example this a DokuWiki port of ``navbar.html`` bundled with the template:

````
  * {{fa>home}} [[:start|Home]]
~~NOCACHE~~
````

And this is an alternative without a label:

````
  * [[:start|{{fa>home}}]]
~~NOCACHE~~
````

:sunglasses:

**Comment by Digitalin** [comment]
After a first artistic try, it works well for the main namespace. An easy way to get sub menu. Great !
Yes, I renamed navbar.html with .old at the end. If not, two menu are displaying. In the case of the wiki I am working on, welcoming others small wikis, it could be interesting to keep above the main menu (navbar.html) and displaying below the (navbar wiki) according to another namespace, for the  hosted wikis. It is special, not sure other people will demand this kind of things. And week-end begins :-)
Thanks.

**Comment by LotarProject** [comment]
With this release there are other DokuWiki hooks:

  * ``:pageheader``
  * ``:pagefooter``

These hooks are placed on top and footer of the wiki content (besides ``pageheader.html`` and ``pagefooter.html``) and have the same behavior of ``:navbar`` and ``:sidebar``.

See live action in http://lotar.altervista.org/dokuwiki/wiki/template/bootstrap3/start

**Comment by zparman** [comment]
HI.  Love your template.  I tried to implement the navbar using the following steps:

1. Renamed ../lib/tpl/bootstrap3/navbar.html to  navbar.html.old
2. Created a page :navbar in dokuwiki.   
3. This is the contents like in the example.  

This works like a champ.

Now I am ready to have customized navbar in my namespace called songbook.
So

4. Created page :songbook:navbar

* [[:start|Home]]
  * [[:songbook:*]]
  * [[:songbook:ukulele]]
  * [[:songbook:guitar]]
   
~~NOCACHE~~

**Comment by duenni** [comment]
Font Awesome icons like `* {{fa>home}} [[:start|Home]]` don't work for me. 
<img width="133" alt="bildschirmfoto 2015-10-30 um 20 15 01" src="https://cloud.githubusercontent.com/assets/4258185/10855618/061c1d80-7f43-11e5-8d65-e103ed8b91f8.png">
Do I have to enable this elsewhere?

**Comment by Digitalin** [comment]
Have you installed [Icons Plugin](https://www.dokuwiki.org/plugin:icons) ? 
As I have the same behavior, I thought to install it but haven't yet checked since :-)
Could be the issue.

**Comment by duenni** [comment]
No, I have not.
After installing this plugin it works. Thanks for pointing this out. @Digitalin

**Comment by Digitalin** [comment]
Hi Joseph,

Do you think I will be possible to have a [topbar](https://www.dokuwiki.org/tips:topbar) as described. I will be cool for additional menu or from time to time put an alert.

As I would like to change the menu color (navbar) with Yeti, I am not sure of the way to do so. As explained, to customize the theme [section](https://www.dokuwiki.org/template:bootstrap3#customize_the_theme)  : 
  * create a userstyle.css in /conf or in lib/tpl/bootstrap3/conf/ ?
  * put which text inside ? 
  * Are Hex color possible ?
I wonder if  adding in the bootstrap3 configuration some features of CSS values could give an hand to make easily changes on the bootstrap default (in the case of a chosen template). 

Thanks.

**Comment by LotarProject** [comment]
Hi @Digitalin if you can:
  * a topbar, the procedure is correct
  * for change the menu color, add a CSS style in ``userstyle.css`` (or ``userall.css``) placed in your ``conf`` DokuWiki directory (eg. ``/var/www/htdocs/dokuwiki/conf``)
  * I'm studying an integration with DokuWiki - LESS - Styling Plugin for change on-the-fly the template (color, font, etc)

At your disposal,
Joseph

**Comment by Digitalin** [comment]
Thanks Joseph for your disposal to improve what is already brilliant
What I can do now ;) is to change color of navbar 
by adding a dokuwiki/conf/userstyle.css with simply inside :
```
.navbar-default {
  color: #ffffff;
  background-color: #143A54;
}
```
I am around to change the dropdown menu's color, looking for example, [here](http://stackoverflow.com/questions/18529274/change-navbar-color-in-twitter-bootstrap-3) for instance.

**Comment by kernam** [comment]
Hello,

first of all I want to thank you for your great work. bootstrap3 is a great theme. I'm currently testing to use it for your company intranet site. At the moment I'm stuck with a problem when using the navbar. I put your example code into navbar.txt in the root namespace but didn't get a hierarchical menu. The entry looks differnet though, which indicates your code is working.
![navbar](https://cloud.githubusercontent.com/assets/15692946/11003243/8fc5f128-84b1-11e5-9a98-65f581d1c4bb.png)

Do you have any tip where to look for the error?

Thanks in advance.

Achim

**Comment by Digitalin** [comment]
Hi Achim,

To my first try, I met some strange behavior too but it was simply a wiki problem. Are you sure there is no some space more that, as you know, express something in wiki syntax. It appears frequently when you copy/paste text. Perhaps, try to write all things.
Hope it will help you.
Digitalin.

**Comment by Soeldner** [comment]
I also have the problem with the navbar and submenus. 
![bildschirmfoto](https://cloud.githubusercontent.com/assets/1868211/11020728/f194f912-8628-11e5-8b1c-da893e09d0b4.png)

**Comment by Digitalin** [comment]
Strange. The only way where I can reproduce this behavior is to put only one space for submenue 1 and 2, but in this case, it appears like 

* Home
* Testmenue
* Submenue 1
* Submenue 2

and I see Testmenue exactly as it is shown on your picture above  but I see Submenue 1 and Submenue 2 as well on the same Home 's line

With 2 or 3 spaces, it works properly for me. 4 spaces and more produces something wrong also but not exactly what you show. Perhaps, try to play with space numbers. No more ideas on this subject. 
Could be antoher problem for you or Achim ?.

**Comment by Soeldner** [comment]
I think that all the spaces have been set correctly. On the website https://collectifdessel.org/doku.php shows Firebug

```
<li class = "level1 node dropdown">
  <a class="dropdown-toggle" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#">
    fonctionnement
    <span class = "caret"> </ span>
  </a>
  <ul class = "dropdown menu" role = "menu">
</ li>
```
On my Webside <a> Tag, class node and dropdown is missing arround the Level 1.

```
<ul class="nav navbar-nav">
  <li class="level1">
    DokuWiki
    <ul class="dropdown-menu" role="menu">
      +<li class="level2">
      +<li class="level2">
    </ul>
  </li>
</ul>
```

![bildschirmfoto-3](https://cloud.githubusercontent.com/assets/1868211/11026992/0fd7b31e-86b1-11e5-9876-d21eaf67d1c8.png)

**Comment by kernam** [comment]
After a little bit of debugging  I think the problem is in tpl_functions.php in function  bootstrap3_navbar(). This function expects a regexp '/<li class="level([0-9]) node"> (.*)/' but the string node is missing in my version. Because of this mismatch there ist no "a href" tag inserted. I attach the result of the call tpl_include_page('navbar', 0, 1) maybe someone can shed some light on where to fix this.
![foo1](https://cloud.githubusercontent.com/assets/15692946/11027906/243dd3b6-86ba-11e5-9cfb-fbd6ad0991e5.png)

**Comment by LotarProject** [comment]
@kernam Hi! Please send your ``:navbar`` page source, for testing this issue.

Joseph

**Comment by kernam** [comment]
Hi Joseph,

the :navbar simply was:
```
  * Listenpunkt
    * [[:it:]]
```
I think the problem could be solved by using a html-parser in bootstrap3-navbar. If you have ul tags within an li tag than we have a sublist the corresponding to a `level[0-9] node` element. But this require much better php knowledge than I have.

Regards Achim

**Comment by Soeldner** [comment]
Is there anything new for this "issue"? If necessary i can provide access to my Test Environment.

sers

**Comment by jERCle** [comment]
I think this is a fantastic idea and am now using it.
The only thing is I was using Fontawesome icons with the html hook and I'm not completely sure of the best way to use them when using a Dokuwiki page.

**Comment by senolv** [comment]
Hi,

And this is an alternative without a label:

```
  * [[:start|{{fa>home}}]]
~~NOCACHE~~

```


Two bugs I recognized.

1. If you use "showHomePageLink"

and do not have home-button in :navbar

the font-sizes differ, items from tpl_navbar.php are smaller


OK, but I would agrre it´s the better way to disable "showHomePageLink" because it´s more clearly if you have all items in one place (:navbar), but here ist a second bug, if you do not label the item (just icon). if the item is selected in menu, it is not presented as selected (with special background).

**Comment by Floffyko** [comment]
![1](https://cloud.githubusercontent.com/assets/11793987/23810532/aa74e82a-05da-11e7-92ac-e77fa5d33555.gif)
![2](https://cloud.githubusercontent.com/assets/11793987/23810573/cb8ae870-05da-11e7-8ff7-baef0d011cb6.gif)

Any solution for this behavior please? I disabled almost all my plugins. Nothing. I made all type of combination possible and.. no drop down behavior. Thank you.

**Comment by NDee303** [comment]
This might work with bootstrapwrapper and <nav></nav> https://www.dokuwiki.org/plugin:bootswrapper#nav

**Comment by Floffyko** [comment]
100 points, you are right. Thanks a lot :)

**Comment by Frosty939** [comment]
Are Sub-Sub menu's possible?

What I've tried:
`  * Help
    * DokuHelp
      * [[:wiki:welcome]]
      * [[:wiki:syntax]]
    * Syn Examples
       * [[:examples:bootstrap_wrapper_plugin|Layout]]
`
I've also tried with 1, 3, and 4 spaces for sub levels, but it just smushes everything onto the same tab

Like so:
![image](https://user-images.githubusercontent.com/26752281/38771171-1edafdfc-3fec-11e8-8c60-7a9ddf378671.png)

**Comment by Eiken** [comment]
Digging this up as I am trying to do the same thing as @Frosty939 anyone got some idea if this can be accomplished?
