### ISSUE TITLE
Back :  On pages with lists of tags, the tags get listed at the top instead of beside the page name #17 

### ISSUE THREAD

**Issue by chtiland** [LotarProject/dokuwiki-template-bootstrap3#95]
I also have this problem with any all boostrap3 templates.
I tried to reinstall bootstrap3 template, but tags are still at the top of the page instead of inside the page (as in default Dokuwiki template).

**Comment by LotarProject** [comment]
Hi! This is the behavior of Bootstrap3 template. This template put all tags (with ``{{tag>..}}``) beside the page-id.

Don't worry, i'm to work to create a flag to enable/disable the normal behavior of tags plugin.

The previous issue (#17) fixes the use of  ``{{tagtopic>...}}``.

Best regards,
Joseph

**Comment by chtiland** [comment]
Works great ! 

Thanks :)
