### ISSUE TITLE
Bootstrap template does not respect table with in structured data plugin

### ISSUE THREAD

**Issue by miocat** [LotarProject/dokuwiki-template-bootstrap3#98]
Hello 

I would like to discuss an issue in conjunction with the structured data plugin.
When a data output is generated with the structured data plugin the genreated table fits within the border limits of the visible area of the wiki. This work o.k. with many of the dokuwiki templates, especially with the default template.
Now if the Bootstrap3 template is used, the structured data plugin genreated table is Extended way out over the right margin of the wiki border. This behaviour is apparently tight to the dynfilters (filter fields on top of the table) parameter of the structured data plugin. If this is set to 1 the table lacks over the right border, if set to 0, it stays within the borders.
![table_over_border](https://cloud.githubusercontent.com/assets/8722384/10367572/933e3faa-6dd1-11e5-8ef5-cbe9dde3e621.png)
![table_within_border](https://cloud.githubusercontent.com/assets/8722384/10367627/d4f0f0dc-6dd1-11e5-8322-98471f5fbf4b.png)

As mentioned this does not happen with the default dokuwiki template and others.
The used Versions of dokuwiki, template etc. are the latest available ones.

I hope I provided enough Information, if not please just ask..
Thank you
Maurizio

**Comment by virk** [comment]
Topic #86 handles the same problem.

**Comment by miocat** [comment]
Thank you for the the hint.
Unfortunatly the disabling of tableFullWidth does not solve the Problem. In my wiki, tableFullWidth is disabled (unchecked) but the table still spans over the right border of the page.
/Maurizio

**Comment by miocat** [comment]
Sorry Need to re-open. I hit the wrong Button
/Maurizio
