### ISSUE TITLE
Disable pageID 

### ISSUE THREAD

**Issue by armanabraham** [LotarProject/dokuwiki-template-bootstrap3#99]
Hi, 

Is there a way to disable pageID through theme settings? It is the little page title displayed in the upper right corner. The html code as follows: 
p class="pageId text-right"
        span class="label label-primary" start /span
/p

Thank you, 
Arman

**Comment by armanabraham** [comment]
Awesome! Thank you!

**Comment by LotarProject** [comment]
:+1:
